services:
  postgres:
    image: postgres:18-alpine
    user: postgres
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_PASSWORD=dev
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  migrations:
    build:
      context: .
      dockerfile: prisma.Dockerfile

    command: migrate dev
    environment:
      - POSTGRES_PRISMA_URL=postgres://postgres:dev@postgres:5432/dev