services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_PRIVATE_API_URL=http://backend:3300

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3300:3300'
    env_file:
      - .env
    links:
      - postgres

  postgres:
    image: postgres:13-alpine
    volumes:
      - pek-postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pek-postgres:
