/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from '@prisma/client/runtime/index-browser';

export type * from '../models.ts';
export type * from './prismaNamespace.ts';

export const Decimal = runtime.Decimal;

export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as new (
    secret: never
  ) => typeof runtime.DbNull,
  JsonNull: runtime.NullTypes.JsonNull as new (
    secret: never
  ) => typeof runtime.JsonNull,
  AnyNull: runtime.NullTypes.AnyNull as new (
    secret: never
  ) => typeof runtime.AnyNull,
};
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull;

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull;

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull;

export const ModelName = {
  Policy: 'Policy',
  Statement: 'Statement',
  PolicyAssignment: 'PolicyAssignment',
  GuidelineCollection: 'GuidelineCollection',
  Guideline: 'Guideline',
  Scoreboard: 'Scoreboard',
  PointRequest: 'PointRequest',
  Evaluation: 'Evaluation',
  EntryAwardRequest: 'EntryAwardRequest',
  PointHistory: 'PointHistory',
  Group: 'Group',
  Membership: 'Membership',
  MembershipStatus: 'MembershipStatus',
  Notification: 'Notification',
  Profile: 'Profile',
  ExternalAccountLink: 'ExternalAccountLink',
  Semester: 'Semester',
  CurrentSemester: 'CurrentSemester',
  User: 'User',
  Username: 'Username',
} as const;

export type ModelName = (typeof ModelName)[keyof typeof ModelName];

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable',
} as const;

export type TransactionIsolationLevel =
  (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel];

export const PolicyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  canIssue: 'canIssue',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type PolicyScalarFieldEnum =
  (typeof PolicyScalarFieldEnum)[keyof typeof PolicyScalarFieldEnum];

export const StatementScalarFieldEnum = {
  id: 'id',
  policyId: 'policyId',
  userIdRestrict: 'userIdRestrict',
  groupIdRestrict: 'groupIdRestrict',
  resource: 'resource',
  viewMembers: 'viewMembers',
  editMembers: 'editMembers',
  viewGroup: 'viewGroup',
  editGroupProfile: 'editGroupProfile',
  moveGroupOwner: 'moveGroupOwner',
  viewScores: 'viewScores',
  editScores: 'editScores',
  evaluateScores: 'evaluateScores',
  viewBasicProfile: 'viewBasicProfile',
  viewFullProfile: 'viewFullProfile',
  editProfile: 'editProfile',
} as const;

export type StatementScalarFieldEnum =
  (typeof StatementScalarFieldEnum)[keyof typeof StatementScalarFieldEnum];

export const PolicyAssignmentScalarFieldEnum = {
  userId: 'userId',
  policyId: 'policyId',
  assignedAt: 'assignedAt',
  assignedBy: 'assignedBy',
} as const;

export type PolicyAssignmentScalarFieldEnum =
  (typeof PolicyAssignmentScalarFieldEnum)[keyof typeof PolicyAssignmentScalarFieldEnum];

export const GuidelineCollectionScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  termId: 'termId',
  semesterId: 'semesterId',
} as const;

export type GuidelineCollectionScalarFieldEnum =
  (typeof GuidelineCollectionScalarFieldEnum)[keyof typeof GuidelineCollectionScalarFieldEnum];

export const GuidelineScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  postCategory: 'postCategory',
  maxPerMember: 'maxPerMember',
  maxPerGuideline: 'maxPerGuideline',
  collectionId: 'collectionId',
} as const;

export type GuidelineScalarFieldEnum =
  (typeof GuidelineScalarFieldEnum)[keyof typeof GuidelineScalarFieldEnum];

export const ScoreboardScalarFieldEnum = {
  id: 'id',
  guidelinesId: 'guidelinesId',
  groupId: 'groupId',
  semesterId: 'semesterId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  submittedAt: 'submittedAt',
  version: 'version',
  discussion: 'discussion',
  previousVersionId: 'previousVersionId',
} as const;

export type ScoreboardScalarFieldEnum =
  (typeof ScoreboardScalarFieldEnum)[keyof typeof ScoreboardScalarFieldEnum];

export const PointRequestScalarFieldEnum = {
  id: 'id',
  scoreboardId: 'scoreboardId',
  membershipId: 'membershipId',
  guidelineId: 'guidelineId',
  points: 'points',
  discussion: 'discussion',
} as const;

export type PointRequestScalarFieldEnum =
  (typeof PointRequestScalarFieldEnum)[keyof typeof PointRequestScalarFieldEnum];

export const EvaluationScalarFieldEnum = {
  scoreboardId: 'scoreboardId',
  createdAt: 'createdAt',
  evaluatorId: 'evaluatorId',
} as const;

export type EvaluationScalarFieldEnum =
  (typeof EvaluationScalarFieldEnum)[keyof typeof EvaluationScalarFieldEnum];

export const EntryAwardRequestScalarFieldEnum = {
  id: 'id',
  type: 'type',
  justification: 'justification',
  membershipId: 'membershipId',
  awardeeId: 'awardeeId',
  semesterId: 'semesterId',
  status: 'status',
  requesterId: 'requesterId',
  evaluatorId: 'evaluatorId',
} as const;

export type EntryAwardRequestScalarFieldEnum =
  (typeof EntryAwardRequestScalarFieldEnum)[keyof typeof EntryAwardRequestScalarFieldEnum];

export const PointHistoryScalarFieldEnum = {
  awardeeId: 'awardeeId',
  semesterId: 'semesterId',
  score: 'score',
} as const;

export type PointHistoryScalarFieldEnum =
  (typeof PointHistoryScalarFieldEnum)[keyof typeof PointHistoryScalarFieldEnum];

export const GroupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  parentId: 'parentId',
  purpose: 'purpose',
  foundationDate: 'foundationDate',
  webpage: 'webpage',
  mail: 'mail',
  isCommunity: 'isCommunity',
  isResort: 'isResort',
  isTaskForce: 'isTaskForce',
  hasTransitiveMembership: 'hasTransitiveMembership',
  isArchived: 'isArchived',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type GroupScalarFieldEnum =
  (typeof GroupScalarFieldEnum)[keyof typeof GroupScalarFieldEnum];

export const MembershipScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  groupId: 'groupId',
  flairs: 'flairs',
} as const;

export type MembershipScalarFieldEnum =
  (typeof MembershipScalarFieldEnum)[keyof typeof MembershipScalarFieldEnum];

export const MembershipStatusScalarFieldEnum = {
  membershipId: 'membershipId',
  start: 'start',
  until: 'until',
  type: 'type',
} as const;

export type MembershipStatusScalarFieldEnum =
  (typeof MembershipStatusScalarFieldEnum)[keyof typeof MembershipStatusScalarFieldEnum];

export const NotificationScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  message: 'message',
  seen: 'seen',
  link: 'link',
  recipientId: 'recipientId',
  senderId: 'senderId',
} as const;

export type NotificationScalarFieldEnum =
  (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum];

export const ProfileScalarFieldEnum = {
  userId: 'userId',
  firstName: 'firstName',
  lastName: 'lastName',
  nickname: 'nickname',
  cellPhone: 'cellPhone',
  room: 'room',
  dormitory: 'dormitory',
  gender: 'gender',
  studentStatus: 'studentStatus',
} as const;

export type ProfileScalarFieldEnum =
  (typeof ProfileScalarFieldEnum)[keyof typeof ProfileScalarFieldEnum];

export const ExternalAccountLinkScalarFieldEnum = {
  id: 'id',
  protocol: 'protocol',
  accountName: 'accountName',
  ownerId: 'ownerId',
} as const;

export type ExternalAccountLinkScalarFieldEnum =
  (typeof ExternalAccountLinkScalarFieldEnum)[keyof typeof ExternalAccountLinkScalarFieldEnum];

export const SemesterScalarFieldEnum = {
  name: 'name',
} as const;

export type SemesterScalarFieldEnum =
  (typeof SemesterScalarFieldEnum)[keyof typeof SemesterScalarFieldEnum];

export const CurrentSemesterScalarFieldEnum = {
  semesterName: 'semesterName',
} as const;

export type CurrentSemesterScalarFieldEnum =
  (typeof CurrentSemesterScalarFieldEnum)[keyof typeof CurrentSemesterScalarFieldEnum];

export const UserScalarFieldEnum = {
  id: 'id',
  authSchId: 'authSchId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastLogin: 'lastLogin',
} as const;

export type UserScalarFieldEnum =
  (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum];

export const UsernameScalarFieldEnum = {
  humanId: 'humanId',
  userId: 'userId',
  createdAt: 'createdAt',
} as const;

export type UsernameScalarFieldEnum =
  (typeof UsernameScalarFieldEnum)[keyof typeof UsernameScalarFieldEnum];

export const SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive',
} as const;

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode];

export const NullsOrder = {
  first: 'first',
  last: 'last',
} as const;

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder];
