/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `CurrentSemester` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.ts';
import type * as Prisma from '../internal/prismaNamespace.ts';

/**
 * Model CurrentSemester
 *
 */
export type CurrentSemesterModel =
  runtime.Types.Result.DefaultSelection<Prisma.$CurrentSemesterPayload>;

export type AggregateCurrentSemester = {
  _count: CurrentSemesterCountAggregateOutputType | null;
  _min: CurrentSemesterMinAggregateOutputType | null;
  _max: CurrentSemesterMaxAggregateOutputType | null;
};

export type CurrentSemesterMinAggregateOutputType = {
  semesterName: string | null;
};

export type CurrentSemesterMaxAggregateOutputType = {
  semesterName: string | null;
};

export type CurrentSemesterCountAggregateOutputType = {
  semesterName: number;
  _all: number;
};

export type CurrentSemesterMinAggregateInputType = {
  semesterName?: true;
};

export type CurrentSemesterMaxAggregateInputType = {
  semesterName?: true;
};

export type CurrentSemesterCountAggregateInputType = {
  semesterName?: true;
  _all?: true;
};

export type CurrentSemesterAggregateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which CurrentSemester to aggregate.
   */
  where?: Prisma.CurrentSemesterWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CurrentSemesters to fetch.
   */
  orderBy?:
    | Prisma.CurrentSemesterOrderByWithRelationInput
    | Prisma.CurrentSemesterOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.CurrentSemesterWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CurrentSemesters from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CurrentSemesters.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned CurrentSemesters
   **/
  _count?: true | CurrentSemesterCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: CurrentSemesterMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: CurrentSemesterMaxAggregateInputType;
};

export type GetCurrentSemesterAggregateType<
  T extends CurrentSemesterAggregateArgs,
> = {
  [P in keyof T & keyof AggregateCurrentSemester]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCurrentSemester[P]>
    : Prisma.GetScalarType<T[P], AggregateCurrentSemester[P]>;
};

export type CurrentSemesterGroupByArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.CurrentSemesterWhereInput;
  orderBy?:
    | Prisma.CurrentSemesterOrderByWithAggregationInput
    | Prisma.CurrentSemesterOrderByWithAggregationInput[];
  by:
    | Prisma.CurrentSemesterScalarFieldEnum[]
    | Prisma.CurrentSemesterScalarFieldEnum;
  having?: Prisma.CurrentSemesterScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: CurrentSemesterCountAggregateInputType | true;
  _min?: CurrentSemesterMinAggregateInputType;
  _max?: CurrentSemesterMaxAggregateInputType;
};

export type CurrentSemesterGroupByOutputType = {
  semesterName: string;
  _count: CurrentSemesterCountAggregateOutputType | null;
  _min: CurrentSemesterMinAggregateOutputType | null;
  _max: CurrentSemesterMaxAggregateOutputType | null;
};

type GetCurrentSemesterGroupByPayload<T extends CurrentSemesterGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<CurrentSemesterGroupByOutputType, T['by']> & {
        [P in keyof T &
          keyof CurrentSemesterGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CurrentSemesterGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CurrentSemesterGroupByOutputType[P]>;
      }
    >
  >;

export type CurrentSemesterWhereInput = {
  AND?: Prisma.CurrentSemesterWhereInput | Prisma.CurrentSemesterWhereInput[];
  OR?: Prisma.CurrentSemesterWhereInput[];
  NOT?: Prisma.CurrentSemesterWhereInput | Prisma.CurrentSemesterWhereInput[];
  semesterName?: Prisma.StringFilter<'CurrentSemester'> | string;
};

export type CurrentSemesterOrderByWithRelationInput = {
  semesterName?: Prisma.SortOrder;
};

export type CurrentSemesterWhereUniqueInput = Prisma.AtLeast<
  {
    semesterName?: string;
    AND?: Prisma.CurrentSemesterWhereInput | Prisma.CurrentSemesterWhereInput[];
    OR?: Prisma.CurrentSemesterWhereInput[];
    NOT?: Prisma.CurrentSemesterWhereInput | Prisma.CurrentSemesterWhereInput[];
  },
  'semesterName'
>;

export type CurrentSemesterOrderByWithAggregationInput = {
  semesterName?: Prisma.SortOrder;
  _count?: Prisma.CurrentSemesterCountOrderByAggregateInput;
  _max?: Prisma.CurrentSemesterMaxOrderByAggregateInput;
  _min?: Prisma.CurrentSemesterMinOrderByAggregateInput;
};

export type CurrentSemesterScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.CurrentSemesterScalarWhereWithAggregatesInput
    | Prisma.CurrentSemesterScalarWhereWithAggregatesInput[];
  OR?: Prisma.CurrentSemesterScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.CurrentSemesterScalarWhereWithAggregatesInput
    | Prisma.CurrentSemesterScalarWhereWithAggregatesInput[];
  semesterName?: Prisma.StringWithAggregatesFilter<'CurrentSemester'> | string;
};

export type CurrentSemesterCreateInput = {
  semesterName: string;
};

export type CurrentSemesterUncheckedCreateInput = {
  semesterName: string;
};

export type CurrentSemesterUpdateInput = {
  semesterName?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type CurrentSemesterUncheckedUpdateInput = {
  semesterName?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type CurrentSemesterCreateManyInput = {
  semesterName: string;
};

export type CurrentSemesterUpdateManyMutationInput = {
  semesterName?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type CurrentSemesterUncheckedUpdateManyInput = {
  semesterName?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type CurrentSemesterCountOrderByAggregateInput = {
  semesterName?: Prisma.SortOrder;
};

export type CurrentSemesterMaxOrderByAggregateInput = {
  semesterName?: Prisma.SortOrder;
};

export type CurrentSemesterMinOrderByAggregateInput = {
  semesterName?: Prisma.SortOrder;
};

export type CurrentSemesterSelect<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    semesterName?: boolean;
  },
  ExtArgs['result']['currentSemester']
>;

export type CurrentSemesterSelectCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    semesterName?: boolean;
  },
  ExtArgs['result']['currentSemester']
>;

export type CurrentSemesterSelectUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    semesterName?: boolean;
  },
  ExtArgs['result']['currentSemester']
>;

export type CurrentSemesterSelectScalar = {
  semesterName?: boolean;
};

export type CurrentSemesterOmit<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'semesterName',
  ExtArgs['result']['currentSemester']
>;

export type $CurrentSemesterPayload<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'CurrentSemester';
  objects: {};
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      semesterName: string;
    },
    ExtArgs['result']['currentSemester']
  >;
  composites: {};
};

export type CurrentSemesterGetPayload<
  S extends boolean | null | undefined | CurrentSemesterDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$CurrentSemesterPayload, S>;

export type CurrentSemesterCountArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<
  CurrentSemesterFindManyArgs,
  'select' | 'include' | 'distinct' | 'omit'
> & {
  select?: CurrentSemesterCountAggregateInputType | true;
};

export interface CurrentSemesterDelegate<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['CurrentSemester'];
    meta: { name: 'CurrentSemester' };
  };
  /**
   * Find zero or one CurrentSemester that matches the filter.
   * @param {CurrentSemesterFindUniqueArgs} args - Arguments to find a CurrentSemester
   * @example
   * // Get one CurrentSemester
   * const currentSemester = await prisma.currentSemester.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CurrentSemesterFindUniqueArgs>(
    args: Prisma.SelectSubset<T, CurrentSemesterFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__CurrentSemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$CurrentSemesterPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one CurrentSemester that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CurrentSemesterFindUniqueOrThrowArgs} args - Arguments to find a CurrentSemester
   * @example
   * // Get one CurrentSemester
   * const currentSemester = await prisma.currentSemester.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CurrentSemesterFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, CurrentSemesterFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__CurrentSemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$CurrentSemesterPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first CurrentSemester that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurrentSemesterFindFirstArgs} args - Arguments to find a CurrentSemester
   * @example
   * // Get one CurrentSemester
   * const currentSemester = await prisma.currentSemester.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CurrentSemesterFindFirstArgs>(
    args?: Prisma.SelectSubset<T, CurrentSemesterFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__CurrentSemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$CurrentSemesterPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first CurrentSemester that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurrentSemesterFindFirstOrThrowArgs} args - Arguments to find a CurrentSemester
   * @example
   * // Get one CurrentSemester
   * const currentSemester = await prisma.currentSemester.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CurrentSemesterFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, CurrentSemesterFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__CurrentSemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$CurrentSemesterPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more CurrentSemesters that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurrentSemesterFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CurrentSemesters
   * const currentSemesters = await prisma.currentSemester.findMany()
   *
   * // Get first 10 CurrentSemesters
   * const currentSemesters = await prisma.currentSemester.findMany({ take: 10 })
   *
   * // Only select the `semesterName`
   * const currentSemesterWithSemesterNameOnly = await prisma.currentSemester.findMany({ select: { semesterName: true } })
   *
   */
  findMany<T extends CurrentSemesterFindManyArgs>(
    args?: Prisma.SelectSubset<T, CurrentSemesterFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$CurrentSemesterPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a CurrentSemester.
   * @param {CurrentSemesterCreateArgs} args - Arguments to create a CurrentSemester.
   * @example
   * // Create one CurrentSemester
   * const CurrentSemester = await prisma.currentSemester.create({
   *   data: {
   *     // ... data to create a CurrentSemester
   *   }
   * })
   *
   */
  create<T extends CurrentSemesterCreateArgs>(
    args: Prisma.SelectSubset<T, CurrentSemesterCreateArgs<ExtArgs>>
  ): Prisma.Prisma__CurrentSemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$CurrentSemesterPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many CurrentSemesters.
   * @param {CurrentSemesterCreateManyArgs} args - Arguments to create many CurrentSemesters.
   * @example
   * // Create many CurrentSemesters
   * const currentSemester = await prisma.currentSemester.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends CurrentSemesterCreateManyArgs>(
    args?: Prisma.SelectSubset<T, CurrentSemesterCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many CurrentSemesters and returns the data saved in the database.
   * @param {CurrentSemesterCreateManyAndReturnArgs} args - Arguments to create many CurrentSemesters.
   * @example
   * // Create many CurrentSemesters
   * const currentSemester = await prisma.currentSemester.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many CurrentSemesters and only return the `semesterName`
   * const currentSemesterWithSemesterNameOnly = await prisma.currentSemester.createManyAndReturn({
   *   select: { semesterName: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends CurrentSemesterCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<
      T,
      CurrentSemesterCreateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$CurrentSemesterPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a CurrentSemester.
   * @param {CurrentSemesterDeleteArgs} args - Arguments to delete one CurrentSemester.
   * @example
   * // Delete one CurrentSemester
   * const CurrentSemester = await prisma.currentSemester.delete({
   *   where: {
   *     // ... filter to delete one CurrentSemester
   *   }
   * })
   *
   */
  delete<T extends CurrentSemesterDeleteArgs>(
    args: Prisma.SelectSubset<T, CurrentSemesterDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__CurrentSemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$CurrentSemesterPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one CurrentSemester.
   * @param {CurrentSemesterUpdateArgs} args - Arguments to update one CurrentSemester.
   * @example
   * // Update one CurrentSemester
   * const currentSemester = await prisma.currentSemester.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends CurrentSemesterUpdateArgs>(
    args: Prisma.SelectSubset<T, CurrentSemesterUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__CurrentSemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$CurrentSemesterPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more CurrentSemesters.
   * @param {CurrentSemesterDeleteManyArgs} args - Arguments to filter CurrentSemesters to delete.
   * @example
   * // Delete a few CurrentSemesters
   * const { count } = await prisma.currentSemester.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends CurrentSemesterDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, CurrentSemesterDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more CurrentSemesters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurrentSemesterUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CurrentSemesters
   * const currentSemester = await prisma.currentSemester.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends CurrentSemesterUpdateManyArgs>(
    args: Prisma.SelectSubset<T, CurrentSemesterUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more CurrentSemesters and returns the data updated in the database.
   * @param {CurrentSemesterUpdateManyAndReturnArgs} args - Arguments to update many CurrentSemesters.
   * @example
   * // Update many CurrentSemesters
   * const currentSemester = await prisma.currentSemester.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more CurrentSemesters and only return the `semesterName`
   * const currentSemesterWithSemesterNameOnly = await prisma.currentSemester.updateManyAndReturn({
   *   select: { semesterName: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends CurrentSemesterUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<
      T,
      CurrentSemesterUpdateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$CurrentSemesterPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one CurrentSemester.
   * @param {CurrentSemesterUpsertArgs} args - Arguments to update or create a CurrentSemester.
   * @example
   * // Update or create a CurrentSemester
   * const currentSemester = await prisma.currentSemester.upsert({
   *   create: {
   *     // ... data to create a CurrentSemester
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CurrentSemester we want to update
   *   }
   * })
   */
  upsert<T extends CurrentSemesterUpsertArgs>(
    args: Prisma.SelectSubset<T, CurrentSemesterUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__CurrentSemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$CurrentSemesterPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of CurrentSemesters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurrentSemesterCountArgs} args - Arguments to filter CurrentSemesters to count.
   * @example
   * // Count the number of CurrentSemesters
   * const count = await prisma.currentSemester.count({
   *   where: {
   *     // ... the filter for the CurrentSemesters we want to count
   *   }
   * })
   **/
  count<T extends CurrentSemesterCountArgs>(
    args?: Prisma.Subset<T, CurrentSemesterCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<
            T['select'],
            CurrentSemesterCountAggregateOutputType
          >
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a CurrentSemester.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurrentSemesterAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends CurrentSemesterAggregateArgs>(
    args: Prisma.Subset<T, CurrentSemesterAggregateArgs>
  ): Prisma.PrismaPromise<GetCurrentSemesterAggregateType<T>>;

  /**
   * Group by CurrentSemester.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CurrentSemesterGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends CurrentSemesterGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CurrentSemesterGroupByArgs['orderBy'] }
      : { orderBy?: CurrentSemesterGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, CurrentSemesterGroupByArgs, OrderByArg> &
      InputErrors
  ): {} extends InputErrors
    ? GetCurrentSemesterGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the CurrentSemester model
   */
  readonly fields: CurrentSemesterFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CurrentSemester.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CurrentSemesterClient<
  T,
  Null = never,
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the CurrentSemester model
 */
export interface CurrentSemesterFieldRefs {
  readonly semesterName: Prisma.FieldRef<'CurrentSemester', 'String'>;
}

// Custom InputTypes
/**
 * CurrentSemester findUnique
 */
export type CurrentSemesterFindUniqueArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CurrentSemester
   */
  select?: Prisma.CurrentSemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CurrentSemester
   */
  omit?: Prisma.CurrentSemesterOmit<ExtArgs> | null;
  /**
   * Filter, which CurrentSemester to fetch.
   */
  where: Prisma.CurrentSemesterWhereUniqueInput;
};

/**
 * CurrentSemester findUniqueOrThrow
 */
export type CurrentSemesterFindUniqueOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CurrentSemester
   */
  select?: Prisma.CurrentSemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CurrentSemester
   */
  omit?: Prisma.CurrentSemesterOmit<ExtArgs> | null;
  /**
   * Filter, which CurrentSemester to fetch.
   */
  where: Prisma.CurrentSemesterWhereUniqueInput;
};

/**
 * CurrentSemester findFirst
 */
export type CurrentSemesterFindFirstArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CurrentSemester
   */
  select?: Prisma.CurrentSemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CurrentSemester
   */
  omit?: Prisma.CurrentSemesterOmit<ExtArgs> | null;
  /**
   * Filter, which CurrentSemester to fetch.
   */
  where?: Prisma.CurrentSemesterWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CurrentSemesters to fetch.
   */
  orderBy?:
    | Prisma.CurrentSemesterOrderByWithRelationInput
    | Prisma.CurrentSemesterOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for CurrentSemesters.
   */
  cursor?: Prisma.CurrentSemesterWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CurrentSemesters from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CurrentSemesters.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of CurrentSemesters.
   */
  distinct?:
    | Prisma.CurrentSemesterScalarFieldEnum
    | Prisma.CurrentSemesterScalarFieldEnum[];
};

/**
 * CurrentSemester findFirstOrThrow
 */
export type CurrentSemesterFindFirstOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CurrentSemester
   */
  select?: Prisma.CurrentSemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CurrentSemester
   */
  omit?: Prisma.CurrentSemesterOmit<ExtArgs> | null;
  /**
   * Filter, which CurrentSemester to fetch.
   */
  where?: Prisma.CurrentSemesterWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CurrentSemesters to fetch.
   */
  orderBy?:
    | Prisma.CurrentSemesterOrderByWithRelationInput
    | Prisma.CurrentSemesterOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for CurrentSemesters.
   */
  cursor?: Prisma.CurrentSemesterWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CurrentSemesters from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CurrentSemesters.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of CurrentSemesters.
   */
  distinct?:
    | Prisma.CurrentSemesterScalarFieldEnum
    | Prisma.CurrentSemesterScalarFieldEnum[];
};

/**
 * CurrentSemester findMany
 */
export type CurrentSemesterFindManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CurrentSemester
   */
  select?: Prisma.CurrentSemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CurrentSemester
   */
  omit?: Prisma.CurrentSemesterOmit<ExtArgs> | null;
  /**
   * Filter, which CurrentSemesters to fetch.
   */
  where?: Prisma.CurrentSemesterWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CurrentSemesters to fetch.
   */
  orderBy?:
    | Prisma.CurrentSemesterOrderByWithRelationInput
    | Prisma.CurrentSemesterOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing CurrentSemesters.
   */
  cursor?: Prisma.CurrentSemesterWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CurrentSemesters from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CurrentSemesters.
   */
  skip?: number;
  distinct?:
    | Prisma.CurrentSemesterScalarFieldEnum
    | Prisma.CurrentSemesterScalarFieldEnum[];
};

/**
 * CurrentSemester create
 */
export type CurrentSemesterCreateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CurrentSemester
   */
  select?: Prisma.CurrentSemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CurrentSemester
   */
  omit?: Prisma.CurrentSemesterOmit<ExtArgs> | null;
  /**
   * The data needed to create a CurrentSemester.
   */
  data: Prisma.XOR<
    Prisma.CurrentSemesterCreateInput,
    Prisma.CurrentSemesterUncheckedCreateInput
  >;
};

/**
 * CurrentSemester createMany
 */
export type CurrentSemesterCreateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many CurrentSemesters.
   */
  data:
    | Prisma.CurrentSemesterCreateManyInput
    | Prisma.CurrentSemesterCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * CurrentSemester createManyAndReturn
 */
export type CurrentSemesterCreateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CurrentSemester
   */
  select?: Prisma.CurrentSemesterSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the CurrentSemester
   */
  omit?: Prisma.CurrentSemesterOmit<ExtArgs> | null;
  /**
   * The data used to create many CurrentSemesters.
   */
  data:
    | Prisma.CurrentSemesterCreateManyInput
    | Prisma.CurrentSemesterCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * CurrentSemester update
 */
export type CurrentSemesterUpdateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CurrentSemester
   */
  select?: Prisma.CurrentSemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CurrentSemester
   */
  omit?: Prisma.CurrentSemesterOmit<ExtArgs> | null;
  /**
   * The data needed to update a CurrentSemester.
   */
  data: Prisma.XOR<
    Prisma.CurrentSemesterUpdateInput,
    Prisma.CurrentSemesterUncheckedUpdateInput
  >;
  /**
   * Choose, which CurrentSemester to update.
   */
  where: Prisma.CurrentSemesterWhereUniqueInput;
};

/**
 * CurrentSemester updateMany
 */
export type CurrentSemesterUpdateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update CurrentSemesters.
   */
  data: Prisma.XOR<
    Prisma.CurrentSemesterUpdateManyMutationInput,
    Prisma.CurrentSemesterUncheckedUpdateManyInput
  >;
  /**
   * Filter which CurrentSemesters to update
   */
  where?: Prisma.CurrentSemesterWhereInput;
  /**
   * Limit how many CurrentSemesters to update.
   */
  limit?: number;
};

/**
 * CurrentSemester updateManyAndReturn
 */
export type CurrentSemesterUpdateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CurrentSemester
   */
  select?: Prisma.CurrentSemesterSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the CurrentSemester
   */
  omit?: Prisma.CurrentSemesterOmit<ExtArgs> | null;
  /**
   * The data used to update CurrentSemesters.
   */
  data: Prisma.XOR<
    Prisma.CurrentSemesterUpdateManyMutationInput,
    Prisma.CurrentSemesterUncheckedUpdateManyInput
  >;
  /**
   * Filter which CurrentSemesters to update
   */
  where?: Prisma.CurrentSemesterWhereInput;
  /**
   * Limit how many CurrentSemesters to update.
   */
  limit?: number;
};

/**
 * CurrentSemester upsert
 */
export type CurrentSemesterUpsertArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CurrentSemester
   */
  select?: Prisma.CurrentSemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CurrentSemester
   */
  omit?: Prisma.CurrentSemesterOmit<ExtArgs> | null;
  /**
   * The filter to search for the CurrentSemester to update in case it exists.
   */
  where: Prisma.CurrentSemesterWhereUniqueInput;
  /**
   * In case the CurrentSemester found by the `where` argument doesn't exist, create a new CurrentSemester with this data.
   */
  create: Prisma.XOR<
    Prisma.CurrentSemesterCreateInput,
    Prisma.CurrentSemesterUncheckedCreateInput
  >;
  /**
   * In case the CurrentSemester was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.CurrentSemesterUpdateInput,
    Prisma.CurrentSemesterUncheckedUpdateInput
  >;
};

/**
 * CurrentSemester delete
 */
export type CurrentSemesterDeleteArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CurrentSemester
   */
  select?: Prisma.CurrentSemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CurrentSemester
   */
  omit?: Prisma.CurrentSemesterOmit<ExtArgs> | null;
  /**
   * Filter which CurrentSemester to delete.
   */
  where: Prisma.CurrentSemesterWhereUniqueInput;
};

/**
 * CurrentSemester deleteMany
 */
export type CurrentSemesterDeleteManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which CurrentSemesters to delete
   */
  where?: Prisma.CurrentSemesterWhereInput;
  /**
   * Limit how many CurrentSemesters to delete.
   */
  limit?: number;
};

/**
 * CurrentSemester without action
 */
export type CurrentSemesterDefaultArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CurrentSemester
   */
  select?: Prisma.CurrentSemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the CurrentSemester
   */
  omit?: Prisma.CurrentSemesterOmit<ExtArgs> | null;
};
