/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `PolicyAssignment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.ts';
import type * as Prisma from '../internal/prismaNamespace.ts';

/**
 * Model PolicyAssignment
 *
 */
export type PolicyAssignmentModel =
  runtime.Types.Result.DefaultSelection<Prisma.$PolicyAssignmentPayload>;

export type AggregatePolicyAssignment = {
  _count: PolicyAssignmentCountAggregateOutputType | null;
  _avg: PolicyAssignmentAvgAggregateOutputType | null;
  _sum: PolicyAssignmentSumAggregateOutputType | null;
  _min: PolicyAssignmentMinAggregateOutputType | null;
  _max: PolicyAssignmentMaxAggregateOutputType | null;
};

export type PolicyAssignmentAvgAggregateOutputType = {
  policyId: number | null;
};

export type PolicyAssignmentSumAggregateOutputType = {
  policyId: number | null;
};

export type PolicyAssignmentMinAggregateOutputType = {
  userId: string | null;
  policyId: number | null;
  assignedAt: Date | null;
  assignedBy: string | null;
};

export type PolicyAssignmentMaxAggregateOutputType = {
  userId: string | null;
  policyId: number | null;
  assignedAt: Date | null;
  assignedBy: string | null;
};

export type PolicyAssignmentCountAggregateOutputType = {
  userId: number;
  policyId: number;
  assignedAt: number;
  assignedBy: number;
  _all: number;
};

export type PolicyAssignmentAvgAggregateInputType = {
  policyId?: true;
};

export type PolicyAssignmentSumAggregateInputType = {
  policyId?: true;
};

export type PolicyAssignmentMinAggregateInputType = {
  userId?: true;
  policyId?: true;
  assignedAt?: true;
  assignedBy?: true;
};

export type PolicyAssignmentMaxAggregateInputType = {
  userId?: true;
  policyId?: true;
  assignedAt?: true;
  assignedBy?: true;
};

export type PolicyAssignmentCountAggregateInputType = {
  userId?: true;
  policyId?: true;
  assignedAt?: true;
  assignedBy?: true;
  _all?: true;
};

export type PolicyAssignmentAggregateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which PolicyAssignment to aggregate.
   */
  where?: Prisma.PolicyAssignmentWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of PolicyAssignments to fetch.
   */
  orderBy?:
    | Prisma.PolicyAssignmentOrderByWithRelationInput
    | Prisma.PolicyAssignmentOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.PolicyAssignmentWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` PolicyAssignments from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` PolicyAssignments.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned PolicyAssignments
   **/
  _count?: true | PolicyAssignmentCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: PolicyAssignmentAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: PolicyAssignmentSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: PolicyAssignmentMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: PolicyAssignmentMaxAggregateInputType;
};

export type GetPolicyAssignmentAggregateType<
  T extends PolicyAssignmentAggregateArgs,
> = {
  [P in keyof T & keyof AggregatePolicyAssignment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePolicyAssignment[P]>
    : Prisma.GetScalarType<T[P], AggregatePolicyAssignment[P]>;
};

export type PolicyAssignmentGroupByArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.PolicyAssignmentWhereInput;
  orderBy?:
    | Prisma.PolicyAssignmentOrderByWithAggregationInput
    | Prisma.PolicyAssignmentOrderByWithAggregationInput[];
  by:
    | Prisma.PolicyAssignmentScalarFieldEnum[]
    | Prisma.PolicyAssignmentScalarFieldEnum;
  having?: Prisma.PolicyAssignmentScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: PolicyAssignmentCountAggregateInputType | true;
  _avg?: PolicyAssignmentAvgAggregateInputType;
  _sum?: PolicyAssignmentSumAggregateInputType;
  _min?: PolicyAssignmentMinAggregateInputType;
  _max?: PolicyAssignmentMaxAggregateInputType;
};

export type PolicyAssignmentGroupByOutputType = {
  userId: string;
  policyId: number;
  assignedAt: Date;
  assignedBy: string | null;
  _count: PolicyAssignmentCountAggregateOutputType | null;
  _avg: PolicyAssignmentAvgAggregateOutputType | null;
  _sum: PolicyAssignmentSumAggregateOutputType | null;
  _min: PolicyAssignmentMinAggregateOutputType | null;
  _max: PolicyAssignmentMaxAggregateOutputType | null;
};

type GetPolicyAssignmentGroupByPayload<T extends PolicyAssignmentGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<PolicyAssignmentGroupByOutputType, T['by']> & {
        [P in keyof T &
          keyof PolicyAssignmentGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PolicyAssignmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PolicyAssignmentGroupByOutputType[P]>;
      }
    >
  >;

export type PolicyAssignmentWhereInput = {
  AND?: Prisma.PolicyAssignmentWhereInput | Prisma.PolicyAssignmentWhereInput[];
  OR?: Prisma.PolicyAssignmentWhereInput[];
  NOT?: Prisma.PolicyAssignmentWhereInput | Prisma.PolicyAssignmentWhereInput[];
  userId?: Prisma.StringFilter<'PolicyAssignment'> | string;
  policyId?: Prisma.IntFilter<'PolicyAssignment'> | number;
  assignedAt?: Prisma.DateTimeFilter<'PolicyAssignment'> | Date | string;
  assignedBy?: Prisma.StringNullableFilter<'PolicyAssignment'> | string | null;
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
  policy?: Prisma.XOR<
    Prisma.PolicyScalarRelationFilter,
    Prisma.PolicyWhereInput
  >;
  assignedByUser?: Prisma.XOR<
    Prisma.UserNullableScalarRelationFilter,
    Prisma.UserWhereInput
  > | null;
};

export type PolicyAssignmentOrderByWithRelationInput = {
  userId?: Prisma.SortOrder;
  policyId?: Prisma.SortOrder;
  assignedAt?: Prisma.SortOrder;
  assignedBy?: Prisma.SortOrderInput | Prisma.SortOrder;
  user?: Prisma.UserOrderByWithRelationInput;
  policy?: Prisma.PolicyOrderByWithRelationInput;
  assignedByUser?: Prisma.UserOrderByWithRelationInput;
};

export type PolicyAssignmentWhereUniqueInput = Prisma.AtLeast<
  {
    userId_policyId?: Prisma.PolicyAssignmentUserIdPolicyIdCompoundUniqueInput;
    AND?:
      | Prisma.PolicyAssignmentWhereInput
      | Prisma.PolicyAssignmentWhereInput[];
    OR?: Prisma.PolicyAssignmentWhereInput[];
    NOT?:
      | Prisma.PolicyAssignmentWhereInput
      | Prisma.PolicyAssignmentWhereInput[];
    userId?: Prisma.StringFilter<'PolicyAssignment'> | string;
    policyId?: Prisma.IntFilter<'PolicyAssignment'> | number;
    assignedAt?: Prisma.DateTimeFilter<'PolicyAssignment'> | Date | string;
    assignedBy?:
      | Prisma.StringNullableFilter<'PolicyAssignment'>
      | string
      | null;
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
    policy?: Prisma.XOR<
      Prisma.PolicyScalarRelationFilter,
      Prisma.PolicyWhereInput
    >;
    assignedByUser?: Prisma.XOR<
      Prisma.UserNullableScalarRelationFilter,
      Prisma.UserWhereInput
    > | null;
  },
  'userId_policyId'
>;

export type PolicyAssignmentOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder;
  policyId?: Prisma.SortOrder;
  assignedAt?: Prisma.SortOrder;
  assignedBy?: Prisma.SortOrderInput | Prisma.SortOrder;
  _count?: Prisma.PolicyAssignmentCountOrderByAggregateInput;
  _avg?: Prisma.PolicyAssignmentAvgOrderByAggregateInput;
  _max?: Prisma.PolicyAssignmentMaxOrderByAggregateInput;
  _min?: Prisma.PolicyAssignmentMinOrderByAggregateInput;
  _sum?: Prisma.PolicyAssignmentSumOrderByAggregateInput;
};

export type PolicyAssignmentScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.PolicyAssignmentScalarWhereWithAggregatesInput
    | Prisma.PolicyAssignmentScalarWhereWithAggregatesInput[];
  OR?: Prisma.PolicyAssignmentScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.PolicyAssignmentScalarWhereWithAggregatesInput
    | Prisma.PolicyAssignmentScalarWhereWithAggregatesInput[];
  userId?: Prisma.StringWithAggregatesFilter<'PolicyAssignment'> | string;
  policyId?: Prisma.IntWithAggregatesFilter<'PolicyAssignment'> | number;
  assignedAt?:
    | Prisma.DateTimeWithAggregatesFilter<'PolicyAssignment'>
    | Date
    | string;
  assignedBy?:
    | Prisma.StringNullableWithAggregatesFilter<'PolicyAssignment'>
    | string
    | null;
};

export type PolicyAssignmentCreateInput = {
  assignedAt?: Date | string;
  user: Prisma.UserCreateNestedOneWithoutPermissionInput;
  policy: Prisma.PolicyCreateNestedOneWithoutPolicyAssignmentInput;
  assignedByUser?: Prisma.UserCreateNestedOneWithoutAssignedPermissionInput;
};

export type PolicyAssignmentUncheckedCreateInput = {
  userId: string;
  policyId: number;
  assignedAt?: Date | string;
  assignedBy?: string | null;
};

export type PolicyAssignmentUpdateInput = {
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  user?: Prisma.UserUpdateOneRequiredWithoutPermissionNestedInput;
  policy?: Prisma.PolicyUpdateOneRequiredWithoutPolicyAssignmentNestedInput;
  assignedByUser?: Prisma.UserUpdateOneWithoutAssignedPermissionNestedInput;
};

export type PolicyAssignmentUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  policyId?: Prisma.IntFieldUpdateOperationsInput | number;
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  assignedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type PolicyAssignmentCreateManyInput = {
  userId: string;
  policyId: number;
  assignedAt?: Date | string;
  assignedBy?: string | null;
};

export type PolicyAssignmentUpdateManyMutationInput = {
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type PolicyAssignmentUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  policyId?: Prisma.IntFieldUpdateOperationsInput | number;
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  assignedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type PolicyAssignmentListRelationFilter = {
  every?: Prisma.PolicyAssignmentWhereInput;
  some?: Prisma.PolicyAssignmentWhereInput;
  none?: Prisma.PolicyAssignmentWhereInput;
};

export type PolicyAssignmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type PolicyAssignmentUserIdPolicyIdCompoundUniqueInput = {
  userId: string;
  policyId: number;
};

export type PolicyAssignmentCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder;
  policyId?: Prisma.SortOrder;
  assignedAt?: Prisma.SortOrder;
  assignedBy?: Prisma.SortOrder;
};

export type PolicyAssignmentAvgOrderByAggregateInput = {
  policyId?: Prisma.SortOrder;
};

export type PolicyAssignmentMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder;
  policyId?: Prisma.SortOrder;
  assignedAt?: Prisma.SortOrder;
  assignedBy?: Prisma.SortOrder;
};

export type PolicyAssignmentMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder;
  policyId?: Prisma.SortOrder;
  assignedAt?: Prisma.SortOrder;
  assignedBy?: Prisma.SortOrder;
};

export type PolicyAssignmentSumOrderByAggregateInput = {
  policyId?: Prisma.SortOrder;
};

export type PolicyAssignmentCreateNestedManyWithoutPolicyInput = {
  create?:
    | Prisma.XOR<
        Prisma.PolicyAssignmentCreateWithoutPolicyInput,
        Prisma.PolicyAssignmentUncheckedCreateWithoutPolicyInput
      >
    | Prisma.PolicyAssignmentCreateWithoutPolicyInput[]
    | Prisma.PolicyAssignmentUncheckedCreateWithoutPolicyInput[];
  connectOrCreate?:
    | Prisma.PolicyAssignmentCreateOrConnectWithoutPolicyInput
    | Prisma.PolicyAssignmentCreateOrConnectWithoutPolicyInput[];
  createMany?: Prisma.PolicyAssignmentCreateManyPolicyInputEnvelope;
  connect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
};

export type PolicyAssignmentUncheckedCreateNestedManyWithoutPolicyInput = {
  create?:
    | Prisma.XOR<
        Prisma.PolicyAssignmentCreateWithoutPolicyInput,
        Prisma.PolicyAssignmentUncheckedCreateWithoutPolicyInput
      >
    | Prisma.PolicyAssignmentCreateWithoutPolicyInput[]
    | Prisma.PolicyAssignmentUncheckedCreateWithoutPolicyInput[];
  connectOrCreate?:
    | Prisma.PolicyAssignmentCreateOrConnectWithoutPolicyInput
    | Prisma.PolicyAssignmentCreateOrConnectWithoutPolicyInput[];
  createMany?: Prisma.PolicyAssignmentCreateManyPolicyInputEnvelope;
  connect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
};

export type PolicyAssignmentUpdateManyWithoutPolicyNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.PolicyAssignmentCreateWithoutPolicyInput,
        Prisma.PolicyAssignmentUncheckedCreateWithoutPolicyInput
      >
    | Prisma.PolicyAssignmentCreateWithoutPolicyInput[]
    | Prisma.PolicyAssignmentUncheckedCreateWithoutPolicyInput[];
  connectOrCreate?:
    | Prisma.PolicyAssignmentCreateOrConnectWithoutPolicyInput
    | Prisma.PolicyAssignmentCreateOrConnectWithoutPolicyInput[];
  upsert?:
    | Prisma.PolicyAssignmentUpsertWithWhereUniqueWithoutPolicyInput
    | Prisma.PolicyAssignmentUpsertWithWhereUniqueWithoutPolicyInput[];
  createMany?: Prisma.PolicyAssignmentCreateManyPolicyInputEnvelope;
  set?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  disconnect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  delete?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  connect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  update?:
    | Prisma.PolicyAssignmentUpdateWithWhereUniqueWithoutPolicyInput
    | Prisma.PolicyAssignmentUpdateWithWhereUniqueWithoutPolicyInput[];
  updateMany?:
    | Prisma.PolicyAssignmentUpdateManyWithWhereWithoutPolicyInput
    | Prisma.PolicyAssignmentUpdateManyWithWhereWithoutPolicyInput[];
  deleteMany?:
    | Prisma.PolicyAssignmentScalarWhereInput
    | Prisma.PolicyAssignmentScalarWhereInput[];
};

export type PolicyAssignmentUncheckedUpdateManyWithoutPolicyNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.PolicyAssignmentCreateWithoutPolicyInput,
        Prisma.PolicyAssignmentUncheckedCreateWithoutPolicyInput
      >
    | Prisma.PolicyAssignmentCreateWithoutPolicyInput[]
    | Prisma.PolicyAssignmentUncheckedCreateWithoutPolicyInput[];
  connectOrCreate?:
    | Prisma.PolicyAssignmentCreateOrConnectWithoutPolicyInput
    | Prisma.PolicyAssignmentCreateOrConnectWithoutPolicyInput[];
  upsert?:
    | Prisma.PolicyAssignmentUpsertWithWhereUniqueWithoutPolicyInput
    | Prisma.PolicyAssignmentUpsertWithWhereUniqueWithoutPolicyInput[];
  createMany?: Prisma.PolicyAssignmentCreateManyPolicyInputEnvelope;
  set?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  disconnect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  delete?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  connect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  update?:
    | Prisma.PolicyAssignmentUpdateWithWhereUniqueWithoutPolicyInput
    | Prisma.PolicyAssignmentUpdateWithWhereUniqueWithoutPolicyInput[];
  updateMany?:
    | Prisma.PolicyAssignmentUpdateManyWithWhereWithoutPolicyInput
    | Prisma.PolicyAssignmentUpdateManyWithWhereWithoutPolicyInput[];
  deleteMany?:
    | Prisma.PolicyAssignmentScalarWhereInput
    | Prisma.PolicyAssignmentScalarWhereInput[];
};

export type PolicyAssignmentCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.PolicyAssignmentCreateWithoutUserInput,
        Prisma.PolicyAssignmentUncheckedCreateWithoutUserInput
      >
    | Prisma.PolicyAssignmentCreateWithoutUserInput[]
    | Prisma.PolicyAssignmentUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.PolicyAssignmentCreateOrConnectWithoutUserInput
    | Prisma.PolicyAssignmentCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.PolicyAssignmentCreateManyUserInputEnvelope;
  connect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
};

export type PolicyAssignmentCreateNestedManyWithoutAssignedByUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.PolicyAssignmentCreateWithoutAssignedByUserInput,
        Prisma.PolicyAssignmentUncheckedCreateWithoutAssignedByUserInput
      >
    | Prisma.PolicyAssignmentCreateWithoutAssignedByUserInput[]
    | Prisma.PolicyAssignmentUncheckedCreateWithoutAssignedByUserInput[];
  connectOrCreate?:
    | Prisma.PolicyAssignmentCreateOrConnectWithoutAssignedByUserInput
    | Prisma.PolicyAssignmentCreateOrConnectWithoutAssignedByUserInput[];
  createMany?: Prisma.PolicyAssignmentCreateManyAssignedByUserInputEnvelope;
  connect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
};

export type PolicyAssignmentUncheckedCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.PolicyAssignmentCreateWithoutUserInput,
        Prisma.PolicyAssignmentUncheckedCreateWithoutUserInput
      >
    | Prisma.PolicyAssignmentCreateWithoutUserInput[]
    | Prisma.PolicyAssignmentUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.PolicyAssignmentCreateOrConnectWithoutUserInput
    | Prisma.PolicyAssignmentCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.PolicyAssignmentCreateManyUserInputEnvelope;
  connect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
};

export type PolicyAssignmentUncheckedCreateNestedManyWithoutAssignedByUserInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.PolicyAssignmentCreateWithoutAssignedByUserInput,
          Prisma.PolicyAssignmentUncheckedCreateWithoutAssignedByUserInput
        >
      | Prisma.PolicyAssignmentCreateWithoutAssignedByUserInput[]
      | Prisma.PolicyAssignmentUncheckedCreateWithoutAssignedByUserInput[];
    connectOrCreate?:
      | Prisma.PolicyAssignmentCreateOrConnectWithoutAssignedByUserInput
      | Prisma.PolicyAssignmentCreateOrConnectWithoutAssignedByUserInput[];
    createMany?: Prisma.PolicyAssignmentCreateManyAssignedByUserInputEnvelope;
    connect?:
      | Prisma.PolicyAssignmentWhereUniqueInput
      | Prisma.PolicyAssignmentWhereUniqueInput[];
  };

export type PolicyAssignmentUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.PolicyAssignmentCreateWithoutUserInput,
        Prisma.PolicyAssignmentUncheckedCreateWithoutUserInput
      >
    | Prisma.PolicyAssignmentCreateWithoutUserInput[]
    | Prisma.PolicyAssignmentUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.PolicyAssignmentCreateOrConnectWithoutUserInput
    | Prisma.PolicyAssignmentCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.PolicyAssignmentUpsertWithWhereUniqueWithoutUserInput
    | Prisma.PolicyAssignmentUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.PolicyAssignmentCreateManyUserInputEnvelope;
  set?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  disconnect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  delete?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  connect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  update?:
    | Prisma.PolicyAssignmentUpdateWithWhereUniqueWithoutUserInput
    | Prisma.PolicyAssignmentUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.PolicyAssignmentUpdateManyWithWhereWithoutUserInput
    | Prisma.PolicyAssignmentUpdateManyWithWhereWithoutUserInput[];
  deleteMany?:
    | Prisma.PolicyAssignmentScalarWhereInput
    | Prisma.PolicyAssignmentScalarWhereInput[];
};

export type PolicyAssignmentUpdateManyWithoutAssignedByUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.PolicyAssignmentCreateWithoutAssignedByUserInput,
        Prisma.PolicyAssignmentUncheckedCreateWithoutAssignedByUserInput
      >
    | Prisma.PolicyAssignmentCreateWithoutAssignedByUserInput[]
    | Prisma.PolicyAssignmentUncheckedCreateWithoutAssignedByUserInput[];
  connectOrCreate?:
    | Prisma.PolicyAssignmentCreateOrConnectWithoutAssignedByUserInput
    | Prisma.PolicyAssignmentCreateOrConnectWithoutAssignedByUserInput[];
  upsert?:
    | Prisma.PolicyAssignmentUpsertWithWhereUniqueWithoutAssignedByUserInput
    | Prisma.PolicyAssignmentUpsertWithWhereUniqueWithoutAssignedByUserInput[];
  createMany?: Prisma.PolicyAssignmentCreateManyAssignedByUserInputEnvelope;
  set?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  disconnect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  delete?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  connect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  update?:
    | Prisma.PolicyAssignmentUpdateWithWhereUniqueWithoutAssignedByUserInput
    | Prisma.PolicyAssignmentUpdateWithWhereUniqueWithoutAssignedByUserInput[];
  updateMany?:
    | Prisma.PolicyAssignmentUpdateManyWithWhereWithoutAssignedByUserInput
    | Prisma.PolicyAssignmentUpdateManyWithWhereWithoutAssignedByUserInput[];
  deleteMany?:
    | Prisma.PolicyAssignmentScalarWhereInput
    | Prisma.PolicyAssignmentScalarWhereInput[];
};

export type PolicyAssignmentUncheckedUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.PolicyAssignmentCreateWithoutUserInput,
        Prisma.PolicyAssignmentUncheckedCreateWithoutUserInput
      >
    | Prisma.PolicyAssignmentCreateWithoutUserInput[]
    | Prisma.PolicyAssignmentUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.PolicyAssignmentCreateOrConnectWithoutUserInput
    | Prisma.PolicyAssignmentCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.PolicyAssignmentUpsertWithWhereUniqueWithoutUserInput
    | Prisma.PolicyAssignmentUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.PolicyAssignmentCreateManyUserInputEnvelope;
  set?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  disconnect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  delete?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  connect?:
    | Prisma.PolicyAssignmentWhereUniqueInput
    | Prisma.PolicyAssignmentWhereUniqueInput[];
  update?:
    | Prisma.PolicyAssignmentUpdateWithWhereUniqueWithoutUserInput
    | Prisma.PolicyAssignmentUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.PolicyAssignmentUpdateManyWithWhereWithoutUserInput
    | Prisma.PolicyAssignmentUpdateManyWithWhereWithoutUserInput[];
  deleteMany?:
    | Prisma.PolicyAssignmentScalarWhereInput
    | Prisma.PolicyAssignmentScalarWhereInput[];
};

export type PolicyAssignmentUncheckedUpdateManyWithoutAssignedByUserNestedInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.PolicyAssignmentCreateWithoutAssignedByUserInput,
          Prisma.PolicyAssignmentUncheckedCreateWithoutAssignedByUserInput
        >
      | Prisma.PolicyAssignmentCreateWithoutAssignedByUserInput[]
      | Prisma.PolicyAssignmentUncheckedCreateWithoutAssignedByUserInput[];
    connectOrCreate?:
      | Prisma.PolicyAssignmentCreateOrConnectWithoutAssignedByUserInput
      | Prisma.PolicyAssignmentCreateOrConnectWithoutAssignedByUserInput[];
    upsert?:
      | Prisma.PolicyAssignmentUpsertWithWhereUniqueWithoutAssignedByUserInput
      | Prisma.PolicyAssignmentUpsertWithWhereUniqueWithoutAssignedByUserInput[];
    createMany?: Prisma.PolicyAssignmentCreateManyAssignedByUserInputEnvelope;
    set?:
      | Prisma.PolicyAssignmentWhereUniqueInput
      | Prisma.PolicyAssignmentWhereUniqueInput[];
    disconnect?:
      | Prisma.PolicyAssignmentWhereUniqueInput
      | Prisma.PolicyAssignmentWhereUniqueInput[];
    delete?:
      | Prisma.PolicyAssignmentWhereUniqueInput
      | Prisma.PolicyAssignmentWhereUniqueInput[];
    connect?:
      | Prisma.PolicyAssignmentWhereUniqueInput
      | Prisma.PolicyAssignmentWhereUniqueInput[];
    update?:
      | Prisma.PolicyAssignmentUpdateWithWhereUniqueWithoutAssignedByUserInput
      | Prisma.PolicyAssignmentUpdateWithWhereUniqueWithoutAssignedByUserInput[];
    updateMany?:
      | Prisma.PolicyAssignmentUpdateManyWithWhereWithoutAssignedByUserInput
      | Prisma.PolicyAssignmentUpdateManyWithWhereWithoutAssignedByUserInput[];
    deleteMany?:
      | Prisma.PolicyAssignmentScalarWhereInput
      | Prisma.PolicyAssignmentScalarWhereInput[];
  };

export type PolicyAssignmentCreateWithoutPolicyInput = {
  assignedAt?: Date | string;
  user: Prisma.UserCreateNestedOneWithoutPermissionInput;
  assignedByUser?: Prisma.UserCreateNestedOneWithoutAssignedPermissionInput;
};

export type PolicyAssignmentUncheckedCreateWithoutPolicyInput = {
  userId: string;
  assignedAt?: Date | string;
  assignedBy?: string | null;
};

export type PolicyAssignmentCreateOrConnectWithoutPolicyInput = {
  where: Prisma.PolicyAssignmentWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.PolicyAssignmentCreateWithoutPolicyInput,
    Prisma.PolicyAssignmentUncheckedCreateWithoutPolicyInput
  >;
};

export type PolicyAssignmentCreateManyPolicyInputEnvelope = {
  data:
    | Prisma.PolicyAssignmentCreateManyPolicyInput
    | Prisma.PolicyAssignmentCreateManyPolicyInput[];
  skipDuplicates?: boolean;
};

export type PolicyAssignmentUpsertWithWhereUniqueWithoutPolicyInput = {
  where: Prisma.PolicyAssignmentWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateWithoutPolicyInput,
    Prisma.PolicyAssignmentUncheckedUpdateWithoutPolicyInput
  >;
  create: Prisma.XOR<
    Prisma.PolicyAssignmentCreateWithoutPolicyInput,
    Prisma.PolicyAssignmentUncheckedCreateWithoutPolicyInput
  >;
};

export type PolicyAssignmentUpdateWithWhereUniqueWithoutPolicyInput = {
  where: Prisma.PolicyAssignmentWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateWithoutPolicyInput,
    Prisma.PolicyAssignmentUncheckedUpdateWithoutPolicyInput
  >;
};

export type PolicyAssignmentUpdateManyWithWhereWithoutPolicyInput = {
  where: Prisma.PolicyAssignmentScalarWhereInput;
  data: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateManyMutationInput,
    Prisma.PolicyAssignmentUncheckedUpdateManyWithoutPolicyInput
  >;
};

export type PolicyAssignmentScalarWhereInput = {
  AND?:
    | Prisma.PolicyAssignmentScalarWhereInput
    | Prisma.PolicyAssignmentScalarWhereInput[];
  OR?: Prisma.PolicyAssignmentScalarWhereInput[];
  NOT?:
    | Prisma.PolicyAssignmentScalarWhereInput
    | Prisma.PolicyAssignmentScalarWhereInput[];
  userId?: Prisma.StringFilter<'PolicyAssignment'> | string;
  policyId?: Prisma.IntFilter<'PolicyAssignment'> | number;
  assignedAt?: Prisma.DateTimeFilter<'PolicyAssignment'> | Date | string;
  assignedBy?: Prisma.StringNullableFilter<'PolicyAssignment'> | string | null;
};

export type PolicyAssignmentCreateWithoutUserInput = {
  assignedAt?: Date | string;
  policy: Prisma.PolicyCreateNestedOneWithoutPolicyAssignmentInput;
  assignedByUser?: Prisma.UserCreateNestedOneWithoutAssignedPermissionInput;
};

export type PolicyAssignmentUncheckedCreateWithoutUserInput = {
  policyId: number;
  assignedAt?: Date | string;
  assignedBy?: string | null;
};

export type PolicyAssignmentCreateOrConnectWithoutUserInput = {
  where: Prisma.PolicyAssignmentWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.PolicyAssignmentCreateWithoutUserInput,
    Prisma.PolicyAssignmentUncheckedCreateWithoutUserInput
  >;
};

export type PolicyAssignmentCreateManyUserInputEnvelope = {
  data:
    | Prisma.PolicyAssignmentCreateManyUserInput
    | Prisma.PolicyAssignmentCreateManyUserInput[];
  skipDuplicates?: boolean;
};

export type PolicyAssignmentCreateWithoutAssignedByUserInput = {
  assignedAt?: Date | string;
  user: Prisma.UserCreateNestedOneWithoutPermissionInput;
  policy: Prisma.PolicyCreateNestedOneWithoutPolicyAssignmentInput;
};

export type PolicyAssignmentUncheckedCreateWithoutAssignedByUserInput = {
  userId: string;
  policyId: number;
  assignedAt?: Date | string;
};

export type PolicyAssignmentCreateOrConnectWithoutAssignedByUserInput = {
  where: Prisma.PolicyAssignmentWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.PolicyAssignmentCreateWithoutAssignedByUserInput,
    Prisma.PolicyAssignmentUncheckedCreateWithoutAssignedByUserInput
  >;
};

export type PolicyAssignmentCreateManyAssignedByUserInputEnvelope = {
  data:
    | Prisma.PolicyAssignmentCreateManyAssignedByUserInput
    | Prisma.PolicyAssignmentCreateManyAssignedByUserInput[];
  skipDuplicates?: boolean;
};

export type PolicyAssignmentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PolicyAssignmentWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateWithoutUserInput,
    Prisma.PolicyAssignmentUncheckedUpdateWithoutUserInput
  >;
  create: Prisma.XOR<
    Prisma.PolicyAssignmentCreateWithoutUserInput,
    Prisma.PolicyAssignmentUncheckedCreateWithoutUserInput
  >;
};

export type PolicyAssignmentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PolicyAssignmentWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateWithoutUserInput,
    Prisma.PolicyAssignmentUncheckedUpdateWithoutUserInput
  >;
};

export type PolicyAssignmentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PolicyAssignmentScalarWhereInput;
  data: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateManyMutationInput,
    Prisma.PolicyAssignmentUncheckedUpdateManyWithoutUserInput
  >;
};

export type PolicyAssignmentUpsertWithWhereUniqueWithoutAssignedByUserInput = {
  where: Prisma.PolicyAssignmentWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateWithoutAssignedByUserInput,
    Prisma.PolicyAssignmentUncheckedUpdateWithoutAssignedByUserInput
  >;
  create: Prisma.XOR<
    Prisma.PolicyAssignmentCreateWithoutAssignedByUserInput,
    Prisma.PolicyAssignmentUncheckedCreateWithoutAssignedByUserInput
  >;
};

export type PolicyAssignmentUpdateWithWhereUniqueWithoutAssignedByUserInput = {
  where: Prisma.PolicyAssignmentWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateWithoutAssignedByUserInput,
    Prisma.PolicyAssignmentUncheckedUpdateWithoutAssignedByUserInput
  >;
};

export type PolicyAssignmentUpdateManyWithWhereWithoutAssignedByUserInput = {
  where: Prisma.PolicyAssignmentScalarWhereInput;
  data: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateManyMutationInput,
    Prisma.PolicyAssignmentUncheckedUpdateManyWithoutAssignedByUserInput
  >;
};

export type PolicyAssignmentCreateManyPolicyInput = {
  userId: string;
  assignedAt?: Date | string;
  assignedBy?: string | null;
};

export type PolicyAssignmentUpdateWithoutPolicyInput = {
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  user?: Prisma.UserUpdateOneRequiredWithoutPermissionNestedInput;
  assignedByUser?: Prisma.UserUpdateOneWithoutAssignedPermissionNestedInput;
};

export type PolicyAssignmentUncheckedUpdateWithoutPolicyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  assignedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type PolicyAssignmentUncheckedUpdateManyWithoutPolicyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  assignedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type PolicyAssignmentCreateManyUserInput = {
  policyId: number;
  assignedAt?: Date | string;
  assignedBy?: string | null;
};

export type PolicyAssignmentCreateManyAssignedByUserInput = {
  userId: string;
  policyId: number;
  assignedAt?: Date | string;
};

export type PolicyAssignmentUpdateWithoutUserInput = {
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  policy?: Prisma.PolicyUpdateOneRequiredWithoutPolicyAssignmentNestedInput;
  assignedByUser?: Prisma.UserUpdateOneWithoutAssignedPermissionNestedInput;
};

export type PolicyAssignmentUncheckedUpdateWithoutUserInput = {
  policyId?: Prisma.IntFieldUpdateOperationsInput | number;
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  assignedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type PolicyAssignmentUncheckedUpdateManyWithoutUserInput = {
  policyId?: Prisma.IntFieldUpdateOperationsInput | number;
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  assignedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
};

export type PolicyAssignmentUpdateWithoutAssignedByUserInput = {
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  user?: Prisma.UserUpdateOneRequiredWithoutPermissionNestedInput;
  policy?: Prisma.PolicyUpdateOneRequiredWithoutPolicyAssignmentNestedInput;
};

export type PolicyAssignmentUncheckedUpdateWithoutAssignedByUserInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  policyId?: Prisma.IntFieldUpdateOperationsInput | number;
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type PolicyAssignmentUncheckedUpdateManyWithoutAssignedByUserInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string;
  policyId?: Prisma.IntFieldUpdateOperationsInput | number;
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type PolicyAssignmentSelect<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    userId?: boolean;
    policyId?: boolean;
    assignedAt?: boolean;
    assignedBy?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    policy?: boolean | Prisma.PolicyDefaultArgs<ExtArgs>;
    assignedByUser?:
      | boolean
      | Prisma.PolicyAssignment$assignedByUserArgs<ExtArgs>;
  },
  ExtArgs['result']['policyAssignment']
>;

export type PolicyAssignmentSelectCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    userId?: boolean;
    policyId?: boolean;
    assignedAt?: boolean;
    assignedBy?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    policy?: boolean | Prisma.PolicyDefaultArgs<ExtArgs>;
    assignedByUser?:
      | boolean
      | Prisma.PolicyAssignment$assignedByUserArgs<ExtArgs>;
  },
  ExtArgs['result']['policyAssignment']
>;

export type PolicyAssignmentSelectUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    userId?: boolean;
    policyId?: boolean;
    assignedAt?: boolean;
    assignedBy?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    policy?: boolean | Prisma.PolicyDefaultArgs<ExtArgs>;
    assignedByUser?:
      | boolean
      | Prisma.PolicyAssignment$assignedByUserArgs<ExtArgs>;
  },
  ExtArgs['result']['policyAssignment']
>;

export type PolicyAssignmentSelectScalar = {
  userId?: boolean;
  policyId?: boolean;
  assignedAt?: boolean;
  assignedBy?: boolean;
};

export type PolicyAssignmentOmit<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'userId' | 'policyId' | 'assignedAt' | 'assignedBy',
  ExtArgs['result']['policyAssignment']
>;
export type PolicyAssignmentInclude<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  policy?: boolean | Prisma.PolicyDefaultArgs<ExtArgs>;
  assignedByUser?:
    | boolean
    | Prisma.PolicyAssignment$assignedByUserArgs<ExtArgs>;
};
export type PolicyAssignmentIncludeCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  policy?: boolean | Prisma.PolicyDefaultArgs<ExtArgs>;
  assignedByUser?:
    | boolean
    | Prisma.PolicyAssignment$assignedByUserArgs<ExtArgs>;
};
export type PolicyAssignmentIncludeUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  policy?: boolean | Prisma.PolicyDefaultArgs<ExtArgs>;
  assignedByUser?:
    | boolean
    | Prisma.PolicyAssignment$assignedByUserArgs<ExtArgs>;
};

export type $PolicyAssignmentPayload<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'PolicyAssignment';
  objects: {
    user: Prisma.$UserPayload<ExtArgs>;
    policy: Prisma.$PolicyPayload<ExtArgs>;
    assignedByUser: Prisma.$UserPayload<ExtArgs> | null;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      userId: string;
      policyId: number;
      assignedAt: Date;
      assignedBy: string | null;
    },
    ExtArgs['result']['policyAssignment']
  >;
  composites: {};
};

export type PolicyAssignmentGetPayload<
  S extends boolean | null | undefined | PolicyAssignmentDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$PolicyAssignmentPayload, S>;

export type PolicyAssignmentCountArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<
  PolicyAssignmentFindManyArgs,
  'select' | 'include' | 'distinct' | 'omit'
> & {
  select?: PolicyAssignmentCountAggregateInputType | true;
};

export interface PolicyAssignmentDelegate<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['PolicyAssignment'];
    meta: { name: 'PolicyAssignment' };
  };
  /**
   * Find zero or one PolicyAssignment that matches the filter.
   * @param {PolicyAssignmentFindUniqueArgs} args - Arguments to find a PolicyAssignment
   * @example
   * // Get one PolicyAssignment
   * const policyAssignment = await prisma.policyAssignment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PolicyAssignmentFindUniqueArgs>(
    args: Prisma.SelectSubset<T, PolicyAssignmentFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__PolicyAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$PolicyAssignmentPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one PolicyAssignment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PolicyAssignmentFindUniqueOrThrowArgs} args - Arguments to find a PolicyAssignment
   * @example
   * // Get one PolicyAssignment
   * const policyAssignment = await prisma.policyAssignment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PolicyAssignmentFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, PolicyAssignmentFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__PolicyAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$PolicyAssignmentPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first PolicyAssignment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyAssignmentFindFirstArgs} args - Arguments to find a PolicyAssignment
   * @example
   * // Get one PolicyAssignment
   * const policyAssignment = await prisma.policyAssignment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PolicyAssignmentFindFirstArgs>(
    args?: Prisma.SelectSubset<T, PolicyAssignmentFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__PolicyAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$PolicyAssignmentPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first PolicyAssignment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyAssignmentFindFirstOrThrowArgs} args - Arguments to find a PolicyAssignment
   * @example
   * // Get one PolicyAssignment
   * const policyAssignment = await prisma.policyAssignment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PolicyAssignmentFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, PolicyAssignmentFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__PolicyAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$PolicyAssignmentPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more PolicyAssignments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyAssignmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PolicyAssignments
   * const policyAssignments = await prisma.policyAssignment.findMany()
   *
   * // Get first 10 PolicyAssignments
   * const policyAssignments = await prisma.policyAssignment.findMany({ take: 10 })
   *
   * // Only select the `userId`
   * const policyAssignmentWithUserIdOnly = await prisma.policyAssignment.findMany({ select: { userId: true } })
   *
   */
  findMany<T extends PolicyAssignmentFindManyArgs>(
    args?: Prisma.SelectSubset<T, PolicyAssignmentFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$PolicyAssignmentPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a PolicyAssignment.
   * @param {PolicyAssignmentCreateArgs} args - Arguments to create a PolicyAssignment.
   * @example
   * // Create one PolicyAssignment
   * const PolicyAssignment = await prisma.policyAssignment.create({
   *   data: {
   *     // ... data to create a PolicyAssignment
   *   }
   * })
   *
   */
  create<T extends PolicyAssignmentCreateArgs>(
    args: Prisma.SelectSubset<T, PolicyAssignmentCreateArgs<ExtArgs>>
  ): Prisma.Prisma__PolicyAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$PolicyAssignmentPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many PolicyAssignments.
   * @param {PolicyAssignmentCreateManyArgs} args - Arguments to create many PolicyAssignments.
   * @example
   * // Create many PolicyAssignments
   * const policyAssignment = await prisma.policyAssignment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends PolicyAssignmentCreateManyArgs>(
    args?: Prisma.SelectSubset<T, PolicyAssignmentCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many PolicyAssignments and returns the data saved in the database.
   * @param {PolicyAssignmentCreateManyAndReturnArgs} args - Arguments to create many PolicyAssignments.
   * @example
   * // Create many PolicyAssignments
   * const policyAssignment = await prisma.policyAssignment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many PolicyAssignments and only return the `userId`
   * const policyAssignmentWithUserIdOnly = await prisma.policyAssignment.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends PolicyAssignmentCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<
      T,
      PolicyAssignmentCreateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$PolicyAssignmentPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a PolicyAssignment.
   * @param {PolicyAssignmentDeleteArgs} args - Arguments to delete one PolicyAssignment.
   * @example
   * // Delete one PolicyAssignment
   * const PolicyAssignment = await prisma.policyAssignment.delete({
   *   where: {
   *     // ... filter to delete one PolicyAssignment
   *   }
   * })
   *
   */
  delete<T extends PolicyAssignmentDeleteArgs>(
    args: Prisma.SelectSubset<T, PolicyAssignmentDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__PolicyAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$PolicyAssignmentPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one PolicyAssignment.
   * @param {PolicyAssignmentUpdateArgs} args - Arguments to update one PolicyAssignment.
   * @example
   * // Update one PolicyAssignment
   * const policyAssignment = await prisma.policyAssignment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends PolicyAssignmentUpdateArgs>(
    args: Prisma.SelectSubset<T, PolicyAssignmentUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__PolicyAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$PolicyAssignmentPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more PolicyAssignments.
   * @param {PolicyAssignmentDeleteManyArgs} args - Arguments to filter PolicyAssignments to delete.
   * @example
   * // Delete a few PolicyAssignments
   * const { count } = await prisma.policyAssignment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends PolicyAssignmentDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, PolicyAssignmentDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more PolicyAssignments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyAssignmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PolicyAssignments
   * const policyAssignment = await prisma.policyAssignment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends PolicyAssignmentUpdateManyArgs>(
    args: Prisma.SelectSubset<T, PolicyAssignmentUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more PolicyAssignments and returns the data updated in the database.
   * @param {PolicyAssignmentUpdateManyAndReturnArgs} args - Arguments to update many PolicyAssignments.
   * @example
   * // Update many PolicyAssignments
   * const policyAssignment = await prisma.policyAssignment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more PolicyAssignments and only return the `userId`
   * const policyAssignmentWithUserIdOnly = await prisma.policyAssignment.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends PolicyAssignmentUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<
      T,
      PolicyAssignmentUpdateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$PolicyAssignmentPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one PolicyAssignment.
   * @param {PolicyAssignmentUpsertArgs} args - Arguments to update or create a PolicyAssignment.
   * @example
   * // Update or create a PolicyAssignment
   * const policyAssignment = await prisma.policyAssignment.upsert({
   *   create: {
   *     // ... data to create a PolicyAssignment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PolicyAssignment we want to update
   *   }
   * })
   */
  upsert<T extends PolicyAssignmentUpsertArgs>(
    args: Prisma.SelectSubset<T, PolicyAssignmentUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__PolicyAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$PolicyAssignmentPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of PolicyAssignments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyAssignmentCountArgs} args - Arguments to filter PolicyAssignments to count.
   * @example
   * // Count the number of PolicyAssignments
   * const count = await prisma.policyAssignment.count({
   *   where: {
   *     // ... the filter for the PolicyAssignments we want to count
   *   }
   * })
   **/
  count<T extends PolicyAssignmentCountArgs>(
    args?: Prisma.Subset<T, PolicyAssignmentCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<
            T['select'],
            PolicyAssignmentCountAggregateOutputType
          >
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a PolicyAssignment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyAssignmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends PolicyAssignmentAggregateArgs>(
    args: Prisma.Subset<T, PolicyAssignmentAggregateArgs>
  ): Prisma.PrismaPromise<GetPolicyAssignmentAggregateType<T>>;

  /**
   * Group by PolicyAssignment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PolicyAssignmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends PolicyAssignmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PolicyAssignmentGroupByArgs['orderBy'] }
      : { orderBy?: PolicyAssignmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<
      T,
      PolicyAssignmentGroupByArgs,
      OrderByArg
    > &
      InputErrors
  ): {} extends InputErrors
    ? GetPolicyAssignmentGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the PolicyAssignment model
   */
  readonly fields: PolicyAssignmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PolicyAssignment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PolicyAssignmentClient<
  T,
  Null = never,
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  policy<T extends Prisma.PolicyDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.PolicyDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__PolicyClient<
    | runtime.Types.Result.GetResult<
        Prisma.$PolicyPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  assignedByUser<
    T extends Prisma.PolicyAssignment$assignedByUserArgs<ExtArgs> = {},
  >(
    args?: Prisma.Subset<T, Prisma.PolicyAssignment$assignedByUserArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the PolicyAssignment model
 */
export interface PolicyAssignmentFieldRefs {
  readonly userId: Prisma.FieldRef<'PolicyAssignment', 'String'>;
  readonly policyId: Prisma.FieldRef<'PolicyAssignment', 'Int'>;
  readonly assignedAt: Prisma.FieldRef<'PolicyAssignment', 'DateTime'>;
  readonly assignedBy: Prisma.FieldRef<'PolicyAssignment', 'String'>;
}

// Custom InputTypes
/**
 * PolicyAssignment findUnique
 */
export type PolicyAssignmentFindUniqueArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PolicyAssignment
   */
  select?: Prisma.PolicyAssignmentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the PolicyAssignment
   */
  omit?: Prisma.PolicyAssignmentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyAssignmentInclude<ExtArgs> | null;
  /**
   * Filter, which PolicyAssignment to fetch.
   */
  where: Prisma.PolicyAssignmentWhereUniqueInput;
};

/**
 * PolicyAssignment findUniqueOrThrow
 */
export type PolicyAssignmentFindUniqueOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PolicyAssignment
   */
  select?: Prisma.PolicyAssignmentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the PolicyAssignment
   */
  omit?: Prisma.PolicyAssignmentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyAssignmentInclude<ExtArgs> | null;
  /**
   * Filter, which PolicyAssignment to fetch.
   */
  where: Prisma.PolicyAssignmentWhereUniqueInput;
};

/**
 * PolicyAssignment findFirst
 */
export type PolicyAssignmentFindFirstArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PolicyAssignment
   */
  select?: Prisma.PolicyAssignmentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the PolicyAssignment
   */
  omit?: Prisma.PolicyAssignmentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyAssignmentInclude<ExtArgs> | null;
  /**
   * Filter, which PolicyAssignment to fetch.
   */
  where?: Prisma.PolicyAssignmentWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of PolicyAssignments to fetch.
   */
  orderBy?:
    | Prisma.PolicyAssignmentOrderByWithRelationInput
    | Prisma.PolicyAssignmentOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for PolicyAssignments.
   */
  cursor?: Prisma.PolicyAssignmentWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` PolicyAssignments from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` PolicyAssignments.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of PolicyAssignments.
   */
  distinct?:
    | Prisma.PolicyAssignmentScalarFieldEnum
    | Prisma.PolicyAssignmentScalarFieldEnum[];
};

/**
 * PolicyAssignment findFirstOrThrow
 */
export type PolicyAssignmentFindFirstOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PolicyAssignment
   */
  select?: Prisma.PolicyAssignmentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the PolicyAssignment
   */
  omit?: Prisma.PolicyAssignmentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyAssignmentInclude<ExtArgs> | null;
  /**
   * Filter, which PolicyAssignment to fetch.
   */
  where?: Prisma.PolicyAssignmentWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of PolicyAssignments to fetch.
   */
  orderBy?:
    | Prisma.PolicyAssignmentOrderByWithRelationInput
    | Prisma.PolicyAssignmentOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for PolicyAssignments.
   */
  cursor?: Prisma.PolicyAssignmentWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` PolicyAssignments from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` PolicyAssignments.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of PolicyAssignments.
   */
  distinct?:
    | Prisma.PolicyAssignmentScalarFieldEnum
    | Prisma.PolicyAssignmentScalarFieldEnum[];
};

/**
 * PolicyAssignment findMany
 */
export type PolicyAssignmentFindManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PolicyAssignment
   */
  select?: Prisma.PolicyAssignmentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the PolicyAssignment
   */
  omit?: Prisma.PolicyAssignmentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyAssignmentInclude<ExtArgs> | null;
  /**
   * Filter, which PolicyAssignments to fetch.
   */
  where?: Prisma.PolicyAssignmentWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of PolicyAssignments to fetch.
   */
  orderBy?:
    | Prisma.PolicyAssignmentOrderByWithRelationInput
    | Prisma.PolicyAssignmentOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing PolicyAssignments.
   */
  cursor?: Prisma.PolicyAssignmentWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` PolicyAssignments from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` PolicyAssignments.
   */
  skip?: number;
  distinct?:
    | Prisma.PolicyAssignmentScalarFieldEnum
    | Prisma.PolicyAssignmentScalarFieldEnum[];
};

/**
 * PolicyAssignment create
 */
export type PolicyAssignmentCreateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PolicyAssignment
   */
  select?: Prisma.PolicyAssignmentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the PolicyAssignment
   */
  omit?: Prisma.PolicyAssignmentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyAssignmentInclude<ExtArgs> | null;
  /**
   * The data needed to create a PolicyAssignment.
   */
  data: Prisma.XOR<
    Prisma.PolicyAssignmentCreateInput,
    Prisma.PolicyAssignmentUncheckedCreateInput
  >;
};

/**
 * PolicyAssignment createMany
 */
export type PolicyAssignmentCreateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many PolicyAssignments.
   */
  data:
    | Prisma.PolicyAssignmentCreateManyInput
    | Prisma.PolicyAssignmentCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * PolicyAssignment createManyAndReturn
 */
export type PolicyAssignmentCreateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PolicyAssignment
   */
  select?: Prisma.PolicyAssignmentSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the PolicyAssignment
   */
  omit?: Prisma.PolicyAssignmentOmit<ExtArgs> | null;
  /**
   * The data used to create many PolicyAssignments.
   */
  data:
    | Prisma.PolicyAssignmentCreateManyInput
    | Prisma.PolicyAssignmentCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyAssignmentIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * PolicyAssignment update
 */
export type PolicyAssignmentUpdateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PolicyAssignment
   */
  select?: Prisma.PolicyAssignmentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the PolicyAssignment
   */
  omit?: Prisma.PolicyAssignmentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyAssignmentInclude<ExtArgs> | null;
  /**
   * The data needed to update a PolicyAssignment.
   */
  data: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateInput,
    Prisma.PolicyAssignmentUncheckedUpdateInput
  >;
  /**
   * Choose, which PolicyAssignment to update.
   */
  where: Prisma.PolicyAssignmentWhereUniqueInput;
};

/**
 * PolicyAssignment updateMany
 */
export type PolicyAssignmentUpdateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update PolicyAssignments.
   */
  data: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateManyMutationInput,
    Prisma.PolicyAssignmentUncheckedUpdateManyInput
  >;
  /**
   * Filter which PolicyAssignments to update
   */
  where?: Prisma.PolicyAssignmentWhereInput;
  /**
   * Limit how many PolicyAssignments to update.
   */
  limit?: number;
};

/**
 * PolicyAssignment updateManyAndReturn
 */
export type PolicyAssignmentUpdateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PolicyAssignment
   */
  select?: Prisma.PolicyAssignmentSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the PolicyAssignment
   */
  omit?: Prisma.PolicyAssignmentOmit<ExtArgs> | null;
  /**
   * The data used to update PolicyAssignments.
   */
  data: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateManyMutationInput,
    Prisma.PolicyAssignmentUncheckedUpdateManyInput
  >;
  /**
   * Filter which PolicyAssignments to update
   */
  where?: Prisma.PolicyAssignmentWhereInput;
  /**
   * Limit how many PolicyAssignments to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyAssignmentIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * PolicyAssignment upsert
 */
export type PolicyAssignmentUpsertArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PolicyAssignment
   */
  select?: Prisma.PolicyAssignmentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the PolicyAssignment
   */
  omit?: Prisma.PolicyAssignmentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyAssignmentInclude<ExtArgs> | null;
  /**
   * The filter to search for the PolicyAssignment to update in case it exists.
   */
  where: Prisma.PolicyAssignmentWhereUniqueInput;
  /**
   * In case the PolicyAssignment found by the `where` argument doesn't exist, create a new PolicyAssignment with this data.
   */
  create: Prisma.XOR<
    Prisma.PolicyAssignmentCreateInput,
    Prisma.PolicyAssignmentUncheckedCreateInput
  >;
  /**
   * In case the PolicyAssignment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.PolicyAssignmentUpdateInput,
    Prisma.PolicyAssignmentUncheckedUpdateInput
  >;
};

/**
 * PolicyAssignment delete
 */
export type PolicyAssignmentDeleteArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PolicyAssignment
   */
  select?: Prisma.PolicyAssignmentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the PolicyAssignment
   */
  omit?: Prisma.PolicyAssignmentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyAssignmentInclude<ExtArgs> | null;
  /**
   * Filter which PolicyAssignment to delete.
   */
  where: Prisma.PolicyAssignmentWhereUniqueInput;
};

/**
 * PolicyAssignment deleteMany
 */
export type PolicyAssignmentDeleteManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which PolicyAssignments to delete
   */
  where?: Prisma.PolicyAssignmentWhereInput;
  /**
   * Limit how many PolicyAssignments to delete.
   */
  limit?: number;
};

/**
 * PolicyAssignment.assignedByUser
 */
export type PolicyAssignment$assignedByUserArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null;
  where?: Prisma.UserWhereInput;
};

/**
 * PolicyAssignment without action
 */
export type PolicyAssignmentDefaultArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PolicyAssignment
   */
  select?: Prisma.PolicyAssignmentSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the PolicyAssignment
   */
  omit?: Prisma.PolicyAssignmentOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PolicyAssignmentInclude<ExtArgs> | null;
};
