/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Semester` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.ts';
import type * as Prisma from '../internal/prismaNamespace.ts';

/**
 * Model Semester
 *
 */
export type SemesterModel =
  runtime.Types.Result.DefaultSelection<Prisma.$SemesterPayload>;

export type AggregateSemester = {
  _count: SemesterCountAggregateOutputType | null;
  _min: SemesterMinAggregateOutputType | null;
  _max: SemesterMaxAggregateOutputType | null;
};

export type SemesterMinAggregateOutputType = {
  name: string | null;
};

export type SemesterMaxAggregateOutputType = {
  name: string | null;
};

export type SemesterCountAggregateOutputType = {
  name: number;
  _all: number;
};

export type SemesterMinAggregateInputType = {
  name?: true;
};

export type SemesterMaxAggregateInputType = {
  name?: true;
};

export type SemesterCountAggregateInputType = {
  name?: true;
  _all?: true;
};

export type SemesterAggregateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Semester to aggregate.
   */
  where?: Prisma.SemesterWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Semesters to fetch.
   */
  orderBy?:
    | Prisma.SemesterOrderByWithRelationInput
    | Prisma.SemesterOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.SemesterWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Semesters from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Semesters.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned Semesters
   **/
  _count?: true | SemesterCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: SemesterMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: SemesterMaxAggregateInputType;
};

export type GetSemesterAggregateType<T extends SemesterAggregateArgs> = {
  [P in keyof T & keyof AggregateSemester]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSemester[P]>
    : Prisma.GetScalarType<T[P], AggregateSemester[P]>;
};

export type SemesterGroupByArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.SemesterWhereInput;
  orderBy?:
    | Prisma.SemesterOrderByWithAggregationInput
    | Prisma.SemesterOrderByWithAggregationInput[];
  by: Prisma.SemesterScalarFieldEnum[] | Prisma.SemesterScalarFieldEnum;
  having?: Prisma.SemesterScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: SemesterCountAggregateInputType | true;
  _min?: SemesterMinAggregateInputType;
  _max?: SemesterMaxAggregateInputType;
};

export type SemesterGroupByOutputType = {
  name: string;
  _count: SemesterCountAggregateOutputType | null;
  _min: SemesterMinAggregateOutputType | null;
  _max: SemesterMaxAggregateOutputType | null;
};

type GetSemesterGroupByPayload<T extends SemesterGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<SemesterGroupByOutputType, T['by']> & {
        [P in keyof T & keyof SemesterGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SemesterGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SemesterGroupByOutputType[P]>;
      }
    >
  >;

export type SemesterWhereInput = {
  AND?: Prisma.SemesterWhereInput | Prisma.SemesterWhereInput[];
  OR?: Prisma.SemesterWhereInput[];
  NOT?: Prisma.SemesterWhereInput | Prisma.SemesterWhereInput[];
  name?: Prisma.StringFilter<'Semester'> | string;
  guidelines?: Prisma.GuidelineCollectionListRelationFilter;
  scoreboards?: Prisma.ScoreboardListRelationFilter;
  entryAwardRequests?: Prisma.EntryAwardRequestListRelationFilter;
  pointHistories?: Prisma.PointHistoryListRelationFilter;
};

export type SemesterOrderByWithRelationInput = {
  name?: Prisma.SortOrder;
  guidelines?: Prisma.GuidelineCollectionOrderByRelationAggregateInput;
  scoreboards?: Prisma.ScoreboardOrderByRelationAggregateInput;
  entryAwardRequests?: Prisma.EntryAwardRequestOrderByRelationAggregateInput;
  pointHistories?: Prisma.PointHistoryOrderByRelationAggregateInput;
};

export type SemesterWhereUniqueInput = Prisma.AtLeast<
  {
    name?: string;
    AND?: Prisma.SemesterWhereInput | Prisma.SemesterWhereInput[];
    OR?: Prisma.SemesterWhereInput[];
    NOT?: Prisma.SemesterWhereInput | Prisma.SemesterWhereInput[];
    guidelines?: Prisma.GuidelineCollectionListRelationFilter;
    scoreboards?: Prisma.ScoreboardListRelationFilter;
    entryAwardRequests?: Prisma.EntryAwardRequestListRelationFilter;
    pointHistories?: Prisma.PointHistoryListRelationFilter;
  },
  'name'
>;

export type SemesterOrderByWithAggregationInput = {
  name?: Prisma.SortOrder;
  _count?: Prisma.SemesterCountOrderByAggregateInput;
  _max?: Prisma.SemesterMaxOrderByAggregateInput;
  _min?: Prisma.SemesterMinOrderByAggregateInput;
};

export type SemesterScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.SemesterScalarWhereWithAggregatesInput
    | Prisma.SemesterScalarWhereWithAggregatesInput[];
  OR?: Prisma.SemesterScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.SemesterScalarWhereWithAggregatesInput
    | Prisma.SemesterScalarWhereWithAggregatesInput[];
  name?: Prisma.StringWithAggregatesFilter<'Semester'> | string;
};

export type SemesterCreateInput = {
  name: string;
  guidelines?: Prisma.GuidelineCollectionCreateNestedManyWithoutSemesterInput;
  scoreboards?: Prisma.ScoreboardCreateNestedManyWithoutSemesterInput;
  entryAwardRequests?: Prisma.EntryAwardRequestCreateNestedManyWithoutSemesterInput;
  pointHistories?: Prisma.PointHistoryCreateNestedManyWithoutSemesterInput;
};

export type SemesterUncheckedCreateInput = {
  name: string;
  guidelines?: Prisma.GuidelineCollectionUncheckedCreateNestedManyWithoutSemesterInput;
  scoreboards?: Prisma.ScoreboardUncheckedCreateNestedManyWithoutSemesterInput;
  entryAwardRequests?: Prisma.EntryAwardRequestUncheckedCreateNestedManyWithoutSemesterInput;
  pointHistories?: Prisma.PointHistoryUncheckedCreateNestedManyWithoutSemesterInput;
};

export type SemesterUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  guidelines?: Prisma.GuidelineCollectionUpdateManyWithoutSemesterNestedInput;
  scoreboards?: Prisma.ScoreboardUpdateManyWithoutSemesterNestedInput;
  entryAwardRequests?: Prisma.EntryAwardRequestUpdateManyWithoutSemesterNestedInput;
  pointHistories?: Prisma.PointHistoryUpdateManyWithoutSemesterNestedInput;
};

export type SemesterUncheckedUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  guidelines?: Prisma.GuidelineCollectionUncheckedUpdateManyWithoutSemesterNestedInput;
  scoreboards?: Prisma.ScoreboardUncheckedUpdateManyWithoutSemesterNestedInput;
  entryAwardRequests?: Prisma.EntryAwardRequestUncheckedUpdateManyWithoutSemesterNestedInput;
  pointHistories?: Prisma.PointHistoryUncheckedUpdateManyWithoutSemesterNestedInput;
};

export type SemesterCreateManyInput = {
  name: string;
};

export type SemesterUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type SemesterUncheckedUpdateManyInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string;
};

export type SemesterScalarRelationFilter = {
  is?: Prisma.SemesterWhereInput;
  isNot?: Prisma.SemesterWhereInput;
};

export type SemesterCountOrderByAggregateInput = {
  name?: Prisma.SortOrder;
};

export type SemesterMaxOrderByAggregateInput = {
  name?: Prisma.SortOrder;
};

export type SemesterMinOrderByAggregateInput = {
  name?: Prisma.SortOrder;
};

export type SemesterCreateNestedOneWithoutGuidelinesInput = {
  create?: Prisma.XOR<
    Prisma.SemesterCreateWithoutGuidelinesInput,
    Prisma.SemesterUncheckedCreateWithoutGuidelinesInput
  >;
  connectOrCreate?: Prisma.SemesterCreateOrConnectWithoutGuidelinesInput;
  connect?: Prisma.SemesterWhereUniqueInput;
};

export type SemesterUpdateOneRequiredWithoutGuidelinesNestedInput = {
  create?: Prisma.XOR<
    Prisma.SemesterCreateWithoutGuidelinesInput,
    Prisma.SemesterUncheckedCreateWithoutGuidelinesInput
  >;
  connectOrCreate?: Prisma.SemesterCreateOrConnectWithoutGuidelinesInput;
  upsert?: Prisma.SemesterUpsertWithoutGuidelinesInput;
  connect?: Prisma.SemesterWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.SemesterUpdateToOneWithWhereWithoutGuidelinesInput,
      Prisma.SemesterUpdateWithoutGuidelinesInput
    >,
    Prisma.SemesterUncheckedUpdateWithoutGuidelinesInput
  >;
};

export type SemesterCreateNestedOneWithoutScoreboardsInput = {
  create?: Prisma.XOR<
    Prisma.SemesterCreateWithoutScoreboardsInput,
    Prisma.SemesterUncheckedCreateWithoutScoreboardsInput
  >;
  connectOrCreate?: Prisma.SemesterCreateOrConnectWithoutScoreboardsInput;
  connect?: Prisma.SemesterWhereUniqueInput;
};

export type SemesterUpdateOneRequiredWithoutScoreboardsNestedInput = {
  create?: Prisma.XOR<
    Prisma.SemesterCreateWithoutScoreboardsInput,
    Prisma.SemesterUncheckedCreateWithoutScoreboardsInput
  >;
  connectOrCreate?: Prisma.SemesterCreateOrConnectWithoutScoreboardsInput;
  upsert?: Prisma.SemesterUpsertWithoutScoreboardsInput;
  connect?: Prisma.SemesterWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.SemesterUpdateToOneWithWhereWithoutScoreboardsInput,
      Prisma.SemesterUpdateWithoutScoreboardsInput
    >,
    Prisma.SemesterUncheckedUpdateWithoutScoreboardsInput
  >;
};

export type SemesterCreateNestedOneWithoutEntryAwardRequestsInput = {
  create?: Prisma.XOR<
    Prisma.SemesterCreateWithoutEntryAwardRequestsInput,
    Prisma.SemesterUncheckedCreateWithoutEntryAwardRequestsInput
  >;
  connectOrCreate?: Prisma.SemesterCreateOrConnectWithoutEntryAwardRequestsInput;
  connect?: Prisma.SemesterWhereUniqueInput;
};

export type SemesterUpdateOneRequiredWithoutEntryAwardRequestsNestedInput = {
  create?: Prisma.XOR<
    Prisma.SemesterCreateWithoutEntryAwardRequestsInput,
    Prisma.SemesterUncheckedCreateWithoutEntryAwardRequestsInput
  >;
  connectOrCreate?: Prisma.SemesterCreateOrConnectWithoutEntryAwardRequestsInput;
  upsert?: Prisma.SemesterUpsertWithoutEntryAwardRequestsInput;
  connect?: Prisma.SemesterWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.SemesterUpdateToOneWithWhereWithoutEntryAwardRequestsInput,
      Prisma.SemesterUpdateWithoutEntryAwardRequestsInput
    >,
    Prisma.SemesterUncheckedUpdateWithoutEntryAwardRequestsInput
  >;
};

export type SemesterCreateNestedOneWithoutPointHistoriesInput = {
  create?: Prisma.XOR<
    Prisma.SemesterCreateWithoutPointHistoriesInput,
    Prisma.SemesterUncheckedCreateWithoutPointHistoriesInput
  >;
  connectOrCreate?: Prisma.SemesterCreateOrConnectWithoutPointHistoriesInput;
  connect?: Prisma.SemesterWhereUniqueInput;
};

export type SemesterUpdateOneRequiredWithoutPointHistoriesNestedInput = {
  create?: Prisma.XOR<
    Prisma.SemesterCreateWithoutPointHistoriesInput,
    Prisma.SemesterUncheckedCreateWithoutPointHistoriesInput
  >;
  connectOrCreate?: Prisma.SemesterCreateOrConnectWithoutPointHistoriesInput;
  upsert?: Prisma.SemesterUpsertWithoutPointHistoriesInput;
  connect?: Prisma.SemesterWhereUniqueInput;
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.SemesterUpdateToOneWithWhereWithoutPointHistoriesInput,
      Prisma.SemesterUpdateWithoutPointHistoriesInput
    >,
    Prisma.SemesterUncheckedUpdateWithoutPointHistoriesInput
  >;
};

export type SemesterCreateWithoutGuidelinesInput = {
  name: string;
  scoreboards?: Prisma.ScoreboardCreateNestedManyWithoutSemesterInput;
  entryAwardRequests?: Prisma.EntryAwardRequestCreateNestedManyWithoutSemesterInput;
  pointHistories?: Prisma.PointHistoryCreateNestedManyWithoutSemesterInput;
};

export type SemesterUncheckedCreateWithoutGuidelinesInput = {
  name: string;
  scoreboards?: Prisma.ScoreboardUncheckedCreateNestedManyWithoutSemesterInput;
  entryAwardRequests?: Prisma.EntryAwardRequestUncheckedCreateNestedManyWithoutSemesterInput;
  pointHistories?: Prisma.PointHistoryUncheckedCreateNestedManyWithoutSemesterInput;
};

export type SemesterCreateOrConnectWithoutGuidelinesInput = {
  where: Prisma.SemesterWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.SemesterCreateWithoutGuidelinesInput,
    Prisma.SemesterUncheckedCreateWithoutGuidelinesInput
  >;
};

export type SemesterUpsertWithoutGuidelinesInput = {
  update: Prisma.XOR<
    Prisma.SemesterUpdateWithoutGuidelinesInput,
    Prisma.SemesterUncheckedUpdateWithoutGuidelinesInput
  >;
  create: Prisma.XOR<
    Prisma.SemesterCreateWithoutGuidelinesInput,
    Prisma.SemesterUncheckedCreateWithoutGuidelinesInput
  >;
  where?: Prisma.SemesterWhereInput;
};

export type SemesterUpdateToOneWithWhereWithoutGuidelinesInput = {
  where?: Prisma.SemesterWhereInput;
  data: Prisma.XOR<
    Prisma.SemesterUpdateWithoutGuidelinesInput,
    Prisma.SemesterUncheckedUpdateWithoutGuidelinesInput
  >;
};

export type SemesterUpdateWithoutGuidelinesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  scoreboards?: Prisma.ScoreboardUpdateManyWithoutSemesterNestedInput;
  entryAwardRequests?: Prisma.EntryAwardRequestUpdateManyWithoutSemesterNestedInput;
  pointHistories?: Prisma.PointHistoryUpdateManyWithoutSemesterNestedInput;
};

export type SemesterUncheckedUpdateWithoutGuidelinesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  scoreboards?: Prisma.ScoreboardUncheckedUpdateManyWithoutSemesterNestedInput;
  entryAwardRequests?: Prisma.EntryAwardRequestUncheckedUpdateManyWithoutSemesterNestedInput;
  pointHistories?: Prisma.PointHistoryUncheckedUpdateManyWithoutSemesterNestedInput;
};

export type SemesterCreateWithoutScoreboardsInput = {
  name: string;
  guidelines?: Prisma.GuidelineCollectionCreateNestedManyWithoutSemesterInput;
  entryAwardRequests?: Prisma.EntryAwardRequestCreateNestedManyWithoutSemesterInput;
  pointHistories?: Prisma.PointHistoryCreateNestedManyWithoutSemesterInput;
};

export type SemesterUncheckedCreateWithoutScoreboardsInput = {
  name: string;
  guidelines?: Prisma.GuidelineCollectionUncheckedCreateNestedManyWithoutSemesterInput;
  entryAwardRequests?: Prisma.EntryAwardRequestUncheckedCreateNestedManyWithoutSemesterInput;
  pointHistories?: Prisma.PointHistoryUncheckedCreateNestedManyWithoutSemesterInput;
};

export type SemesterCreateOrConnectWithoutScoreboardsInput = {
  where: Prisma.SemesterWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.SemesterCreateWithoutScoreboardsInput,
    Prisma.SemesterUncheckedCreateWithoutScoreboardsInput
  >;
};

export type SemesterUpsertWithoutScoreboardsInput = {
  update: Prisma.XOR<
    Prisma.SemesterUpdateWithoutScoreboardsInput,
    Prisma.SemesterUncheckedUpdateWithoutScoreboardsInput
  >;
  create: Prisma.XOR<
    Prisma.SemesterCreateWithoutScoreboardsInput,
    Prisma.SemesterUncheckedCreateWithoutScoreboardsInput
  >;
  where?: Prisma.SemesterWhereInput;
};

export type SemesterUpdateToOneWithWhereWithoutScoreboardsInput = {
  where?: Prisma.SemesterWhereInput;
  data: Prisma.XOR<
    Prisma.SemesterUpdateWithoutScoreboardsInput,
    Prisma.SemesterUncheckedUpdateWithoutScoreboardsInput
  >;
};

export type SemesterUpdateWithoutScoreboardsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  guidelines?: Prisma.GuidelineCollectionUpdateManyWithoutSemesterNestedInput;
  entryAwardRequests?: Prisma.EntryAwardRequestUpdateManyWithoutSemesterNestedInput;
  pointHistories?: Prisma.PointHistoryUpdateManyWithoutSemesterNestedInput;
};

export type SemesterUncheckedUpdateWithoutScoreboardsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  guidelines?: Prisma.GuidelineCollectionUncheckedUpdateManyWithoutSemesterNestedInput;
  entryAwardRequests?: Prisma.EntryAwardRequestUncheckedUpdateManyWithoutSemesterNestedInput;
  pointHistories?: Prisma.PointHistoryUncheckedUpdateManyWithoutSemesterNestedInput;
};

export type SemesterCreateWithoutEntryAwardRequestsInput = {
  name: string;
  guidelines?: Prisma.GuidelineCollectionCreateNestedManyWithoutSemesterInput;
  scoreboards?: Prisma.ScoreboardCreateNestedManyWithoutSemesterInput;
  pointHistories?: Prisma.PointHistoryCreateNestedManyWithoutSemesterInput;
};

export type SemesterUncheckedCreateWithoutEntryAwardRequestsInput = {
  name: string;
  guidelines?: Prisma.GuidelineCollectionUncheckedCreateNestedManyWithoutSemesterInput;
  scoreboards?: Prisma.ScoreboardUncheckedCreateNestedManyWithoutSemesterInput;
  pointHistories?: Prisma.PointHistoryUncheckedCreateNestedManyWithoutSemesterInput;
};

export type SemesterCreateOrConnectWithoutEntryAwardRequestsInput = {
  where: Prisma.SemesterWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.SemesterCreateWithoutEntryAwardRequestsInput,
    Prisma.SemesterUncheckedCreateWithoutEntryAwardRequestsInput
  >;
};

export type SemesterUpsertWithoutEntryAwardRequestsInput = {
  update: Prisma.XOR<
    Prisma.SemesterUpdateWithoutEntryAwardRequestsInput,
    Prisma.SemesterUncheckedUpdateWithoutEntryAwardRequestsInput
  >;
  create: Prisma.XOR<
    Prisma.SemesterCreateWithoutEntryAwardRequestsInput,
    Prisma.SemesterUncheckedCreateWithoutEntryAwardRequestsInput
  >;
  where?: Prisma.SemesterWhereInput;
};

export type SemesterUpdateToOneWithWhereWithoutEntryAwardRequestsInput = {
  where?: Prisma.SemesterWhereInput;
  data: Prisma.XOR<
    Prisma.SemesterUpdateWithoutEntryAwardRequestsInput,
    Prisma.SemesterUncheckedUpdateWithoutEntryAwardRequestsInput
  >;
};

export type SemesterUpdateWithoutEntryAwardRequestsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  guidelines?: Prisma.GuidelineCollectionUpdateManyWithoutSemesterNestedInput;
  scoreboards?: Prisma.ScoreboardUpdateManyWithoutSemesterNestedInput;
  pointHistories?: Prisma.PointHistoryUpdateManyWithoutSemesterNestedInput;
};

export type SemesterUncheckedUpdateWithoutEntryAwardRequestsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  guidelines?: Prisma.GuidelineCollectionUncheckedUpdateManyWithoutSemesterNestedInput;
  scoreboards?: Prisma.ScoreboardUncheckedUpdateManyWithoutSemesterNestedInput;
  pointHistories?: Prisma.PointHistoryUncheckedUpdateManyWithoutSemesterNestedInput;
};

export type SemesterCreateWithoutPointHistoriesInput = {
  name: string;
  guidelines?: Prisma.GuidelineCollectionCreateNestedManyWithoutSemesterInput;
  scoreboards?: Prisma.ScoreboardCreateNestedManyWithoutSemesterInput;
  entryAwardRequests?: Prisma.EntryAwardRequestCreateNestedManyWithoutSemesterInput;
};

export type SemesterUncheckedCreateWithoutPointHistoriesInput = {
  name: string;
  guidelines?: Prisma.GuidelineCollectionUncheckedCreateNestedManyWithoutSemesterInput;
  scoreboards?: Prisma.ScoreboardUncheckedCreateNestedManyWithoutSemesterInput;
  entryAwardRequests?: Prisma.EntryAwardRequestUncheckedCreateNestedManyWithoutSemesterInput;
};

export type SemesterCreateOrConnectWithoutPointHistoriesInput = {
  where: Prisma.SemesterWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.SemesterCreateWithoutPointHistoriesInput,
    Prisma.SemesterUncheckedCreateWithoutPointHistoriesInput
  >;
};

export type SemesterUpsertWithoutPointHistoriesInput = {
  update: Prisma.XOR<
    Prisma.SemesterUpdateWithoutPointHistoriesInput,
    Prisma.SemesterUncheckedUpdateWithoutPointHistoriesInput
  >;
  create: Prisma.XOR<
    Prisma.SemesterCreateWithoutPointHistoriesInput,
    Prisma.SemesterUncheckedCreateWithoutPointHistoriesInput
  >;
  where?: Prisma.SemesterWhereInput;
};

export type SemesterUpdateToOneWithWhereWithoutPointHistoriesInput = {
  where?: Prisma.SemesterWhereInput;
  data: Prisma.XOR<
    Prisma.SemesterUpdateWithoutPointHistoriesInput,
    Prisma.SemesterUncheckedUpdateWithoutPointHistoriesInput
  >;
};

export type SemesterUpdateWithoutPointHistoriesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  guidelines?: Prisma.GuidelineCollectionUpdateManyWithoutSemesterNestedInput;
  scoreboards?: Prisma.ScoreboardUpdateManyWithoutSemesterNestedInput;
  entryAwardRequests?: Prisma.EntryAwardRequestUpdateManyWithoutSemesterNestedInput;
};

export type SemesterUncheckedUpdateWithoutPointHistoriesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string;
  guidelines?: Prisma.GuidelineCollectionUncheckedUpdateManyWithoutSemesterNestedInput;
  scoreboards?: Prisma.ScoreboardUncheckedUpdateManyWithoutSemesterNestedInput;
  entryAwardRequests?: Prisma.EntryAwardRequestUncheckedUpdateManyWithoutSemesterNestedInput;
};

/**
 * Count Type SemesterCountOutputType
 */

export type SemesterCountOutputType = {
  guidelines: number;
  scoreboards: number;
  entryAwardRequests: number;
  pointHistories: number;
};

export type SemesterCountOutputTypeSelect<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  guidelines?: boolean | SemesterCountOutputTypeCountGuidelinesArgs;
  scoreboards?: boolean | SemesterCountOutputTypeCountScoreboardsArgs;
  entryAwardRequests?:
    | boolean
    | SemesterCountOutputTypeCountEntryAwardRequestsArgs;
  pointHistories?: boolean | SemesterCountOutputTypeCountPointHistoriesArgs;
};

/**
 * SemesterCountOutputType without action
 */
export type SemesterCountOutputTypeDefaultArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SemesterCountOutputType
   */
  select?: Prisma.SemesterCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * SemesterCountOutputType without action
 */
export type SemesterCountOutputTypeCountGuidelinesArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.GuidelineCollectionWhereInput;
};

/**
 * SemesterCountOutputType without action
 */
export type SemesterCountOutputTypeCountScoreboardsArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ScoreboardWhereInput;
};

/**
 * SemesterCountOutputType without action
 */
export type SemesterCountOutputTypeCountEntryAwardRequestsArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.EntryAwardRequestWhereInput;
};

/**
 * SemesterCountOutputType without action
 */
export type SemesterCountOutputTypeCountPointHistoriesArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.PointHistoryWhereInput;
};

export type SemesterSelect<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    name?: boolean;
    guidelines?: boolean | Prisma.Semester$guidelinesArgs<ExtArgs>;
    scoreboards?: boolean | Prisma.Semester$scoreboardsArgs<ExtArgs>;
    entryAwardRequests?:
      | boolean
      | Prisma.Semester$entryAwardRequestsArgs<ExtArgs>;
    pointHistories?: boolean | Prisma.Semester$pointHistoriesArgs<ExtArgs>;
    _count?: boolean | Prisma.SemesterCountOutputTypeDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['semester']
>;

export type SemesterSelectCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    name?: boolean;
  },
  ExtArgs['result']['semester']
>;

export type SemesterSelectUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    name?: boolean;
  },
  ExtArgs['result']['semester']
>;

export type SemesterSelectScalar = {
  name?: boolean;
};

export type SemesterOmit<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<'name', ExtArgs['result']['semester']>;
export type SemesterInclude<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  guidelines?: boolean | Prisma.Semester$guidelinesArgs<ExtArgs>;
  scoreboards?: boolean | Prisma.Semester$scoreboardsArgs<ExtArgs>;
  entryAwardRequests?:
    | boolean
    | Prisma.Semester$entryAwardRequestsArgs<ExtArgs>;
  pointHistories?: boolean | Prisma.Semester$pointHistoriesArgs<ExtArgs>;
  _count?: boolean | Prisma.SemesterCountOutputTypeDefaultArgs<ExtArgs>;
};
export type SemesterIncludeCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};
export type SemesterIncludeUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {};

export type $SemesterPayload<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'Semester';
  objects: {
    guidelines: Prisma.$GuidelineCollectionPayload<ExtArgs>[];
    scoreboards: Prisma.$ScoreboardPayload<ExtArgs>[];
    entryAwardRequests: Prisma.$EntryAwardRequestPayload<ExtArgs>[];
    pointHistories: Prisma.$PointHistoryPayload<ExtArgs>[];
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      name: string;
    },
    ExtArgs['result']['semester']
  >;
  composites: {};
};

export type SemesterGetPayload<
  S extends boolean | null | undefined | SemesterDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$SemesterPayload, S>;

export type SemesterCountArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<SemesterFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: SemesterCountAggregateInputType | true;
};

export interface SemesterDelegate<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['Semester'];
    meta: { name: 'Semester' };
  };
  /**
   * Find zero or one Semester that matches the filter.
   * @param {SemesterFindUniqueArgs} args - Arguments to find a Semester
   * @example
   * // Get one Semester
   * const semester = await prisma.semester.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SemesterFindUniqueArgs>(
    args: Prisma.SelectSubset<T, SemesterFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__SemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$SemesterPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one Semester that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SemesterFindUniqueOrThrowArgs} args - Arguments to find a Semester
   * @example
   * // Get one Semester
   * const semester = await prisma.semester.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SemesterFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, SemesterFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__SemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$SemesterPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first Semester that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SemesterFindFirstArgs} args - Arguments to find a Semester
   * @example
   * // Get one Semester
   * const semester = await prisma.semester.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SemesterFindFirstArgs>(
    args?: Prisma.SelectSubset<T, SemesterFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__SemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$SemesterPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first Semester that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SemesterFindFirstOrThrowArgs} args - Arguments to find a Semester
   * @example
   * // Get one Semester
   * const semester = await prisma.semester.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SemesterFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, SemesterFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__SemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$SemesterPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more Semesters that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SemesterFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Semesters
   * const semesters = await prisma.semester.findMany()
   *
   * // Get first 10 Semesters
   * const semesters = await prisma.semester.findMany({ take: 10 })
   *
   * // Only select the `name`
   * const semesterWithNameOnly = await prisma.semester.findMany({ select: { name: true } })
   *
   */
  findMany<T extends SemesterFindManyArgs>(
    args?: Prisma.SelectSubset<T, SemesterFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$SemesterPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a Semester.
   * @param {SemesterCreateArgs} args - Arguments to create a Semester.
   * @example
   * // Create one Semester
   * const Semester = await prisma.semester.create({
   *   data: {
   *     // ... data to create a Semester
   *   }
   * })
   *
   */
  create<T extends SemesterCreateArgs>(
    args: Prisma.SelectSubset<T, SemesterCreateArgs<ExtArgs>>
  ): Prisma.Prisma__SemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$SemesterPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many Semesters.
   * @param {SemesterCreateManyArgs} args - Arguments to create many Semesters.
   * @example
   * // Create many Semesters
   * const semester = await prisma.semester.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends SemesterCreateManyArgs>(
    args?: Prisma.SelectSubset<T, SemesterCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many Semesters and returns the data saved in the database.
   * @param {SemesterCreateManyAndReturnArgs} args - Arguments to create many Semesters.
   * @example
   * // Create many Semesters
   * const semester = await prisma.semester.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many Semesters and only return the `name`
   * const semesterWithNameOnly = await prisma.semester.createManyAndReturn({
   *   select: { name: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends SemesterCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, SemesterCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$SemesterPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a Semester.
   * @param {SemesterDeleteArgs} args - Arguments to delete one Semester.
   * @example
   * // Delete one Semester
   * const Semester = await prisma.semester.delete({
   *   where: {
   *     // ... filter to delete one Semester
   *   }
   * })
   *
   */
  delete<T extends SemesterDeleteArgs>(
    args: Prisma.SelectSubset<T, SemesterDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__SemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$SemesterPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one Semester.
   * @param {SemesterUpdateArgs} args - Arguments to update one Semester.
   * @example
   * // Update one Semester
   * const semester = await prisma.semester.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends SemesterUpdateArgs>(
    args: Prisma.SelectSubset<T, SemesterUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__SemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$SemesterPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more Semesters.
   * @param {SemesterDeleteManyArgs} args - Arguments to filter Semesters to delete.
   * @example
   * // Delete a few Semesters
   * const { count } = await prisma.semester.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends SemesterDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, SemesterDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more Semesters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SemesterUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Semesters
   * const semester = await prisma.semester.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends SemesterUpdateManyArgs>(
    args: Prisma.SelectSubset<T, SemesterUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more Semesters and returns the data updated in the database.
   * @param {SemesterUpdateManyAndReturnArgs} args - Arguments to update many Semesters.
   * @example
   * // Update many Semesters
   * const semester = await prisma.semester.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more Semesters and only return the `name`
   * const semesterWithNameOnly = await prisma.semester.updateManyAndReturn({
   *   select: { name: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends SemesterUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, SemesterUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$SemesterPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one Semester.
   * @param {SemesterUpsertArgs} args - Arguments to update or create a Semester.
   * @example
   * // Update or create a Semester
   * const semester = await prisma.semester.upsert({
   *   create: {
   *     // ... data to create a Semester
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Semester we want to update
   *   }
   * })
   */
  upsert<T extends SemesterUpsertArgs>(
    args: Prisma.SelectSubset<T, SemesterUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__SemesterClient<
    runtime.Types.Result.GetResult<
      Prisma.$SemesterPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of Semesters.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SemesterCountArgs} args - Arguments to filter Semesters to count.
   * @example
   * // Count the number of Semesters
   * const count = await prisma.semester.count({
   *   where: {
   *     // ... the filter for the Semesters we want to count
   *   }
   * })
   **/
  count<T extends SemesterCountArgs>(
    args?: Prisma.Subset<T, SemesterCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SemesterCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a Semester.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SemesterAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends SemesterAggregateArgs>(
    args: Prisma.Subset<T, SemesterAggregateArgs>
  ): Prisma.PrismaPromise<GetSemesterAggregateType<T>>;

  /**
   * Group by Semester.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SemesterGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends SemesterGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SemesterGroupByArgs['orderBy'] }
      : { orderBy?: SemesterGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, SemesterGroupByArgs, OrderByArg> &
      InputErrors
  ): {} extends InputErrors
    ? GetSemesterGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the Semester model
   */
  readonly fields: SemesterFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Semester.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SemesterClient<
  T,
  Null = never,
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  guidelines<T extends Prisma.Semester$guidelinesArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.Semester$guidelinesArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$GuidelineCollectionPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >;
  scoreboards<T extends Prisma.Semester$scoreboardsArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.Semester$scoreboardsArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$ScoreboardPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >;
  entryAwardRequests<
    T extends Prisma.Semester$entryAwardRequestsArgs<ExtArgs> = {},
  >(
    args?: Prisma.Subset<T, Prisma.Semester$entryAwardRequestsArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$EntryAwardRequestPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >;
  pointHistories<T extends Prisma.Semester$pointHistoriesArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.Semester$pointHistoriesArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$PointHistoryPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the Semester model
 */
export interface SemesterFieldRefs {
  readonly name: Prisma.FieldRef<'Semester', 'String'>;
}

// Custom InputTypes
/**
 * Semester findUnique
 */
export type SemesterFindUniqueArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Semester
   */
  select?: Prisma.SemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Semester
   */
  omit?: Prisma.SemesterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SemesterInclude<ExtArgs> | null;
  /**
   * Filter, which Semester to fetch.
   */
  where: Prisma.SemesterWhereUniqueInput;
};

/**
 * Semester findUniqueOrThrow
 */
export type SemesterFindUniqueOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Semester
   */
  select?: Prisma.SemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Semester
   */
  omit?: Prisma.SemesterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SemesterInclude<ExtArgs> | null;
  /**
   * Filter, which Semester to fetch.
   */
  where: Prisma.SemesterWhereUniqueInput;
};

/**
 * Semester findFirst
 */
export type SemesterFindFirstArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Semester
   */
  select?: Prisma.SemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Semester
   */
  omit?: Prisma.SemesterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SemesterInclude<ExtArgs> | null;
  /**
   * Filter, which Semester to fetch.
   */
  where?: Prisma.SemesterWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Semesters to fetch.
   */
  orderBy?:
    | Prisma.SemesterOrderByWithRelationInput
    | Prisma.SemesterOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Semesters.
   */
  cursor?: Prisma.SemesterWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Semesters from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Semesters.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Semesters.
   */
  distinct?: Prisma.SemesterScalarFieldEnum | Prisma.SemesterScalarFieldEnum[];
};

/**
 * Semester findFirstOrThrow
 */
export type SemesterFindFirstOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Semester
   */
  select?: Prisma.SemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Semester
   */
  omit?: Prisma.SemesterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SemesterInclude<ExtArgs> | null;
  /**
   * Filter, which Semester to fetch.
   */
  where?: Prisma.SemesterWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Semesters to fetch.
   */
  orderBy?:
    | Prisma.SemesterOrderByWithRelationInput
    | Prisma.SemesterOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Semesters.
   */
  cursor?: Prisma.SemesterWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Semesters from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Semesters.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Semesters.
   */
  distinct?: Prisma.SemesterScalarFieldEnum | Prisma.SemesterScalarFieldEnum[];
};

/**
 * Semester findMany
 */
export type SemesterFindManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Semester
   */
  select?: Prisma.SemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Semester
   */
  omit?: Prisma.SemesterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SemesterInclude<ExtArgs> | null;
  /**
   * Filter, which Semesters to fetch.
   */
  where?: Prisma.SemesterWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Semesters to fetch.
   */
  orderBy?:
    | Prisma.SemesterOrderByWithRelationInput
    | Prisma.SemesterOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing Semesters.
   */
  cursor?: Prisma.SemesterWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Semesters from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Semesters.
   */
  skip?: number;
  distinct?: Prisma.SemesterScalarFieldEnum | Prisma.SemesterScalarFieldEnum[];
};

/**
 * Semester create
 */
export type SemesterCreateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Semester
   */
  select?: Prisma.SemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Semester
   */
  omit?: Prisma.SemesterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SemesterInclude<ExtArgs> | null;
  /**
   * The data needed to create a Semester.
   */
  data: Prisma.XOR<
    Prisma.SemesterCreateInput,
    Prisma.SemesterUncheckedCreateInput
  >;
};

/**
 * Semester createMany
 */
export type SemesterCreateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many Semesters.
   */
  data: Prisma.SemesterCreateManyInput | Prisma.SemesterCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * Semester createManyAndReturn
 */
export type SemesterCreateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Semester
   */
  select?: Prisma.SemesterSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the Semester
   */
  omit?: Prisma.SemesterOmit<ExtArgs> | null;
  /**
   * The data used to create many Semesters.
   */
  data: Prisma.SemesterCreateManyInput | Prisma.SemesterCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * Semester update
 */
export type SemesterUpdateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Semester
   */
  select?: Prisma.SemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Semester
   */
  omit?: Prisma.SemesterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SemesterInclude<ExtArgs> | null;
  /**
   * The data needed to update a Semester.
   */
  data: Prisma.XOR<
    Prisma.SemesterUpdateInput,
    Prisma.SemesterUncheckedUpdateInput
  >;
  /**
   * Choose, which Semester to update.
   */
  where: Prisma.SemesterWhereUniqueInput;
};

/**
 * Semester updateMany
 */
export type SemesterUpdateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update Semesters.
   */
  data: Prisma.XOR<
    Prisma.SemesterUpdateManyMutationInput,
    Prisma.SemesterUncheckedUpdateManyInput
  >;
  /**
   * Filter which Semesters to update
   */
  where?: Prisma.SemesterWhereInput;
  /**
   * Limit how many Semesters to update.
   */
  limit?: number;
};

/**
 * Semester updateManyAndReturn
 */
export type SemesterUpdateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Semester
   */
  select?: Prisma.SemesterSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the Semester
   */
  omit?: Prisma.SemesterOmit<ExtArgs> | null;
  /**
   * The data used to update Semesters.
   */
  data: Prisma.XOR<
    Prisma.SemesterUpdateManyMutationInput,
    Prisma.SemesterUncheckedUpdateManyInput
  >;
  /**
   * Filter which Semesters to update
   */
  where?: Prisma.SemesterWhereInput;
  /**
   * Limit how many Semesters to update.
   */
  limit?: number;
};

/**
 * Semester upsert
 */
export type SemesterUpsertArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Semester
   */
  select?: Prisma.SemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Semester
   */
  omit?: Prisma.SemesterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SemesterInclude<ExtArgs> | null;
  /**
   * The filter to search for the Semester to update in case it exists.
   */
  where: Prisma.SemesterWhereUniqueInput;
  /**
   * In case the Semester found by the `where` argument doesn't exist, create a new Semester with this data.
   */
  create: Prisma.XOR<
    Prisma.SemesterCreateInput,
    Prisma.SemesterUncheckedCreateInput
  >;
  /**
   * In case the Semester was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.SemesterUpdateInput,
    Prisma.SemesterUncheckedUpdateInput
  >;
};

/**
 * Semester delete
 */
export type SemesterDeleteArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Semester
   */
  select?: Prisma.SemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Semester
   */
  omit?: Prisma.SemesterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SemesterInclude<ExtArgs> | null;
  /**
   * Filter which Semester to delete.
   */
  where: Prisma.SemesterWhereUniqueInput;
};

/**
 * Semester deleteMany
 */
export type SemesterDeleteManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Semesters to delete
   */
  where?: Prisma.SemesterWhereInput;
  /**
   * Limit how many Semesters to delete.
   */
  limit?: number;
};

/**
 * Semester.guidelines
 */
export type Semester$guidelinesArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the GuidelineCollection
   */
  select?: Prisma.GuidelineCollectionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the GuidelineCollection
   */
  omit?: Prisma.GuidelineCollectionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuidelineCollectionInclude<ExtArgs> | null;
  where?: Prisma.GuidelineCollectionWhereInput;
  orderBy?:
    | Prisma.GuidelineCollectionOrderByWithRelationInput
    | Prisma.GuidelineCollectionOrderByWithRelationInput[];
  cursor?: Prisma.GuidelineCollectionWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.GuidelineCollectionScalarFieldEnum
    | Prisma.GuidelineCollectionScalarFieldEnum[];
};

/**
 * Semester.scoreboards
 */
export type Semester$scoreboardsArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Scoreboard
   */
  select?: Prisma.ScoreboardSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Scoreboard
   */
  omit?: Prisma.ScoreboardOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScoreboardInclude<ExtArgs> | null;
  where?: Prisma.ScoreboardWhereInput;
  orderBy?:
    | Prisma.ScoreboardOrderByWithRelationInput
    | Prisma.ScoreboardOrderByWithRelationInput[];
  cursor?: Prisma.ScoreboardWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.ScoreboardScalarFieldEnum
    | Prisma.ScoreboardScalarFieldEnum[];
};

/**
 * Semester.entryAwardRequests
 */
export type Semester$entryAwardRequestsArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the EntryAwardRequest
   */
  select?: Prisma.EntryAwardRequestSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the EntryAwardRequest
   */
  omit?: Prisma.EntryAwardRequestOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntryAwardRequestInclude<ExtArgs> | null;
  where?: Prisma.EntryAwardRequestWhereInput;
  orderBy?:
    | Prisma.EntryAwardRequestOrderByWithRelationInput
    | Prisma.EntryAwardRequestOrderByWithRelationInput[];
  cursor?: Prisma.EntryAwardRequestWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.EntryAwardRequestScalarFieldEnum
    | Prisma.EntryAwardRequestScalarFieldEnum[];
};

/**
 * Semester.pointHistories
 */
export type Semester$pointHistoriesArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the PointHistory
   */
  select?: Prisma.PointHistorySelect<ExtArgs> | null;
  /**
   * Omit specific fields from the PointHistory
   */
  omit?: Prisma.PointHistoryOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PointHistoryInclude<ExtArgs> | null;
  where?: Prisma.PointHistoryWhereInput;
  orderBy?:
    | Prisma.PointHistoryOrderByWithRelationInput
    | Prisma.PointHistoryOrderByWithRelationInput[];
  cursor?: Prisma.PointHistoryWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.PointHistoryScalarFieldEnum
    | Prisma.PointHistoryScalarFieldEnum[];
};

/**
 * Semester without action
 */
export type SemesterDefaultArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Semester
   */
  select?: Prisma.SemesterSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Semester
   */
  omit?: Prisma.SemesterOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SemesterInclude<ExtArgs> | null;
};
