/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Statement` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.ts';
import type * as Prisma from '../internal/prismaNamespace.ts';

/**
 * Model Statement
 *
 */
export type StatementModel =
  runtime.Types.Result.DefaultSelection<Prisma.$StatementPayload>;

export type AggregateStatement = {
  _count: StatementCountAggregateOutputType | null;
  _avg: StatementAvgAggregateOutputType | null;
  _sum: StatementSumAggregateOutputType | null;
  _min: StatementMinAggregateOutputType | null;
  _max: StatementMaxAggregateOutputType | null;
};

export type StatementAvgAggregateOutputType = {
  policyId: number | null;
};

export type StatementSumAggregateOutputType = {
  policyId: number | null;
};

export type StatementMinAggregateOutputType = {
  id: string | null;
  policyId: number | null;
  userIdRestrict: string | null;
  groupIdRestrict: string | null;
  resource: string | null;
  viewMembers: boolean | null;
  editMembers: boolean | null;
  viewGroup: boolean | null;
  editGroupProfile: boolean | null;
  moveGroupOwner: boolean | null;
  viewScores: boolean | null;
  editScores: boolean | null;
  evaluateScores: boolean | null;
  viewBasicProfile: boolean | null;
  viewFullProfile: boolean | null;
  editProfile: boolean | null;
};

export type StatementMaxAggregateOutputType = {
  id: string | null;
  policyId: number | null;
  userIdRestrict: string | null;
  groupIdRestrict: string | null;
  resource: string | null;
  viewMembers: boolean | null;
  editMembers: boolean | null;
  viewGroup: boolean | null;
  editGroupProfile: boolean | null;
  moveGroupOwner: boolean | null;
  viewScores: boolean | null;
  editScores: boolean | null;
  evaluateScores: boolean | null;
  viewBasicProfile: boolean | null;
  viewFullProfile: boolean | null;
  editProfile: boolean | null;
};

export type StatementCountAggregateOutputType = {
  id: number;
  policyId: number;
  userIdRestrict: number;
  groupIdRestrict: number;
  resource: number;
  viewMembers: number;
  editMembers: number;
  viewGroup: number;
  editGroupProfile: number;
  moveGroupOwner: number;
  viewScores: number;
  editScores: number;
  evaluateScores: number;
  viewBasicProfile: number;
  viewFullProfile: number;
  editProfile: number;
  _all: number;
};

export type StatementAvgAggregateInputType = {
  policyId?: true;
};

export type StatementSumAggregateInputType = {
  policyId?: true;
};

export type StatementMinAggregateInputType = {
  id?: true;
  policyId?: true;
  userIdRestrict?: true;
  groupIdRestrict?: true;
  resource?: true;
  viewMembers?: true;
  editMembers?: true;
  viewGroup?: true;
  editGroupProfile?: true;
  moveGroupOwner?: true;
  viewScores?: true;
  editScores?: true;
  evaluateScores?: true;
  viewBasicProfile?: true;
  viewFullProfile?: true;
  editProfile?: true;
};

export type StatementMaxAggregateInputType = {
  id?: true;
  policyId?: true;
  userIdRestrict?: true;
  groupIdRestrict?: true;
  resource?: true;
  viewMembers?: true;
  editMembers?: true;
  viewGroup?: true;
  editGroupProfile?: true;
  moveGroupOwner?: true;
  viewScores?: true;
  editScores?: true;
  evaluateScores?: true;
  viewBasicProfile?: true;
  viewFullProfile?: true;
  editProfile?: true;
};

export type StatementCountAggregateInputType = {
  id?: true;
  policyId?: true;
  userIdRestrict?: true;
  groupIdRestrict?: true;
  resource?: true;
  viewMembers?: true;
  editMembers?: true;
  viewGroup?: true;
  editGroupProfile?: true;
  moveGroupOwner?: true;
  viewScores?: true;
  editScores?: true;
  evaluateScores?: true;
  viewBasicProfile?: true;
  viewFullProfile?: true;
  editProfile?: true;
  _all?: true;
};

export type StatementAggregateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Statement to aggregate.
   */
  where?: Prisma.StatementWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Statements to fetch.
   */
  orderBy?:
    | Prisma.StatementOrderByWithRelationInput
    | Prisma.StatementOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.StatementWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Statements from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Statements.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned Statements
   **/
  _count?: true | StatementCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: StatementAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: StatementSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: StatementMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: StatementMaxAggregateInputType;
};

export type GetStatementAggregateType<T extends StatementAggregateArgs> = {
  [P in keyof T & keyof AggregateStatement]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStatement[P]>
    : Prisma.GetScalarType<T[P], AggregateStatement[P]>;
};

export type StatementGroupByArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.StatementWhereInput;
  orderBy?:
    | Prisma.StatementOrderByWithAggregationInput
    | Prisma.StatementOrderByWithAggregationInput[];
  by: Prisma.StatementScalarFieldEnum[] | Prisma.StatementScalarFieldEnum;
  having?: Prisma.StatementScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: StatementCountAggregateInputType | true;
  _avg?: StatementAvgAggregateInputType;
  _sum?: StatementSumAggregateInputType;
  _min?: StatementMinAggregateInputType;
  _max?: StatementMaxAggregateInputType;
};

export type StatementGroupByOutputType = {
  id: string;
  policyId: number;
  userIdRestrict: string | null;
  groupIdRestrict: string | null;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
  _count: StatementCountAggregateOutputType | null;
  _avg: StatementAvgAggregateOutputType | null;
  _sum: StatementSumAggregateOutputType | null;
  _min: StatementMinAggregateOutputType | null;
  _max: StatementMaxAggregateOutputType | null;
};

type GetStatementGroupByPayload<T extends StatementGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<StatementGroupByOutputType, T['by']> & {
        [P in keyof T & keyof StatementGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StatementGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StatementGroupByOutputType[P]>;
      }
    >
  >;

export type StatementWhereInput = {
  AND?: Prisma.StatementWhereInput | Prisma.StatementWhereInput[];
  OR?: Prisma.StatementWhereInput[];
  NOT?: Prisma.StatementWhereInput | Prisma.StatementWhereInput[];
  id?: Prisma.StringFilter<'Statement'> | string;
  policyId?: Prisma.IntFilter<'Statement'> | number;
  userIdRestrict?: Prisma.StringNullableFilter<'Statement'> | string | null;
  groupIdRestrict?: Prisma.StringNullableFilter<'Statement'> | string | null;
  resource?: Prisma.StringFilter<'Statement'> | string;
  viewMembers?: Prisma.BoolFilter<'Statement'> | boolean;
  editMembers?: Prisma.BoolFilter<'Statement'> | boolean;
  viewGroup?: Prisma.BoolFilter<'Statement'> | boolean;
  editGroupProfile?: Prisma.BoolFilter<'Statement'> | boolean;
  moveGroupOwner?: Prisma.BoolFilter<'Statement'> | boolean;
  viewScores?: Prisma.BoolFilter<'Statement'> | boolean;
  editScores?: Prisma.BoolFilter<'Statement'> | boolean;
  evaluateScores?: Prisma.BoolFilter<'Statement'> | boolean;
  viewBasicProfile?: Prisma.BoolFilter<'Statement'> | boolean;
  viewFullProfile?: Prisma.BoolFilter<'Statement'> | boolean;
  editProfile?: Prisma.BoolFilter<'Statement'> | boolean;
  policy?: Prisma.XOR<
    Prisma.PolicyScalarRelationFilter,
    Prisma.PolicyWhereInput
  >;
  userRestriction?: Prisma.XOR<
    Prisma.UserNullableScalarRelationFilter,
    Prisma.UserWhereInput
  > | null;
  groupRestriction?: Prisma.XOR<
    Prisma.GroupNullableScalarRelationFilter,
    Prisma.GroupWhereInput
  > | null;
};

export type StatementOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  policyId?: Prisma.SortOrder;
  userIdRestrict?: Prisma.SortOrderInput | Prisma.SortOrder;
  groupIdRestrict?: Prisma.SortOrderInput | Prisma.SortOrder;
  resource?: Prisma.SortOrder;
  viewMembers?: Prisma.SortOrder;
  editMembers?: Prisma.SortOrder;
  viewGroup?: Prisma.SortOrder;
  editGroupProfile?: Prisma.SortOrder;
  moveGroupOwner?: Prisma.SortOrder;
  viewScores?: Prisma.SortOrder;
  editScores?: Prisma.SortOrder;
  evaluateScores?: Prisma.SortOrder;
  viewBasicProfile?: Prisma.SortOrder;
  viewFullProfile?: Prisma.SortOrder;
  editProfile?: Prisma.SortOrder;
  policy?: Prisma.PolicyOrderByWithRelationInput;
  userRestriction?: Prisma.UserOrderByWithRelationInput;
  groupRestriction?: Prisma.GroupOrderByWithRelationInput;
};

export type StatementWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string;
    AND?: Prisma.StatementWhereInput | Prisma.StatementWhereInput[];
    OR?: Prisma.StatementWhereInput[];
    NOT?: Prisma.StatementWhereInput | Prisma.StatementWhereInput[];
    policyId?: Prisma.IntFilter<'Statement'> | number;
    userIdRestrict?: Prisma.StringNullableFilter<'Statement'> | string | null;
    groupIdRestrict?: Prisma.StringNullableFilter<'Statement'> | string | null;
    resource?: Prisma.StringFilter<'Statement'> | string;
    viewMembers?: Prisma.BoolFilter<'Statement'> | boolean;
    editMembers?: Prisma.BoolFilter<'Statement'> | boolean;
    viewGroup?: Prisma.BoolFilter<'Statement'> | boolean;
    editGroupProfile?: Prisma.BoolFilter<'Statement'> | boolean;
    moveGroupOwner?: Prisma.BoolFilter<'Statement'> | boolean;
    viewScores?: Prisma.BoolFilter<'Statement'> | boolean;
    editScores?: Prisma.BoolFilter<'Statement'> | boolean;
    evaluateScores?: Prisma.BoolFilter<'Statement'> | boolean;
    viewBasicProfile?: Prisma.BoolFilter<'Statement'> | boolean;
    viewFullProfile?: Prisma.BoolFilter<'Statement'> | boolean;
    editProfile?: Prisma.BoolFilter<'Statement'> | boolean;
    policy?: Prisma.XOR<
      Prisma.PolicyScalarRelationFilter,
      Prisma.PolicyWhereInput
    >;
    userRestriction?: Prisma.XOR<
      Prisma.UserNullableScalarRelationFilter,
      Prisma.UserWhereInput
    > | null;
    groupRestriction?: Prisma.XOR<
      Prisma.GroupNullableScalarRelationFilter,
      Prisma.GroupWhereInput
    > | null;
  },
  'id'
>;

export type StatementOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  policyId?: Prisma.SortOrder;
  userIdRestrict?: Prisma.SortOrderInput | Prisma.SortOrder;
  groupIdRestrict?: Prisma.SortOrderInput | Prisma.SortOrder;
  resource?: Prisma.SortOrder;
  viewMembers?: Prisma.SortOrder;
  editMembers?: Prisma.SortOrder;
  viewGroup?: Prisma.SortOrder;
  editGroupProfile?: Prisma.SortOrder;
  moveGroupOwner?: Prisma.SortOrder;
  viewScores?: Prisma.SortOrder;
  editScores?: Prisma.SortOrder;
  evaluateScores?: Prisma.SortOrder;
  viewBasicProfile?: Prisma.SortOrder;
  viewFullProfile?: Prisma.SortOrder;
  editProfile?: Prisma.SortOrder;
  _count?: Prisma.StatementCountOrderByAggregateInput;
  _avg?: Prisma.StatementAvgOrderByAggregateInput;
  _max?: Prisma.StatementMaxOrderByAggregateInput;
  _min?: Prisma.StatementMinOrderByAggregateInput;
  _sum?: Prisma.StatementSumOrderByAggregateInput;
};

export type StatementScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.StatementScalarWhereWithAggregatesInput
    | Prisma.StatementScalarWhereWithAggregatesInput[];
  OR?: Prisma.StatementScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.StatementScalarWhereWithAggregatesInput
    | Prisma.StatementScalarWhereWithAggregatesInput[];
  id?: Prisma.StringWithAggregatesFilter<'Statement'> | string;
  policyId?: Prisma.IntWithAggregatesFilter<'Statement'> | number;
  userIdRestrict?:
    | Prisma.StringNullableWithAggregatesFilter<'Statement'>
    | string
    | null;
  groupIdRestrict?:
    | Prisma.StringNullableWithAggregatesFilter<'Statement'>
    | string
    | null;
  resource?: Prisma.StringWithAggregatesFilter<'Statement'> | string;
  viewMembers?: Prisma.BoolWithAggregatesFilter<'Statement'> | boolean;
  editMembers?: Prisma.BoolWithAggregatesFilter<'Statement'> | boolean;
  viewGroup?: Prisma.BoolWithAggregatesFilter<'Statement'> | boolean;
  editGroupProfile?: Prisma.BoolWithAggregatesFilter<'Statement'> | boolean;
  moveGroupOwner?: Prisma.BoolWithAggregatesFilter<'Statement'> | boolean;
  viewScores?: Prisma.BoolWithAggregatesFilter<'Statement'> | boolean;
  editScores?: Prisma.BoolWithAggregatesFilter<'Statement'> | boolean;
  evaluateScores?: Prisma.BoolWithAggregatesFilter<'Statement'> | boolean;
  viewBasicProfile?: Prisma.BoolWithAggregatesFilter<'Statement'> | boolean;
  viewFullProfile?: Prisma.BoolWithAggregatesFilter<'Statement'> | boolean;
  editProfile?: Prisma.BoolWithAggregatesFilter<'Statement'> | boolean;
};

export type StatementCreateInput = {
  id?: string;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
  policy: Prisma.PolicyCreateNestedOneWithoutStatementsInput;
  userRestriction?: Prisma.UserCreateNestedOneWithoutAppliedStatementsInput;
  groupRestriction?: Prisma.GroupCreateNestedOneWithoutAppliedStatementsInput;
};

export type StatementUncheckedCreateInput = {
  id?: string;
  policyId: number;
  userIdRestrict?: string | null;
  groupIdRestrict?: string | null;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
};

export type StatementUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  policy?: Prisma.PolicyUpdateOneRequiredWithoutStatementsNestedInput;
  userRestriction?: Prisma.UserUpdateOneWithoutAppliedStatementsNestedInput;
  groupRestriction?: Prisma.GroupUpdateOneWithoutAppliedStatementsNestedInput;
};

export type StatementUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  policyId?: Prisma.IntFieldUpdateOperationsInput | number;
  userIdRestrict?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  groupIdRestrict?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type StatementCreateManyInput = {
  id?: string;
  policyId: number;
  userIdRestrict?: string | null;
  groupIdRestrict?: string | null;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
};

export type StatementUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type StatementUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  policyId?: Prisma.IntFieldUpdateOperationsInput | number;
  userIdRestrict?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  groupIdRestrict?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type StatementListRelationFilter = {
  every?: Prisma.StatementWhereInput;
  some?: Prisma.StatementWhereInput;
  none?: Prisma.StatementWhereInput;
};

export type StatementOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type StatementCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  policyId?: Prisma.SortOrder;
  userIdRestrict?: Prisma.SortOrder;
  groupIdRestrict?: Prisma.SortOrder;
  resource?: Prisma.SortOrder;
  viewMembers?: Prisma.SortOrder;
  editMembers?: Prisma.SortOrder;
  viewGroup?: Prisma.SortOrder;
  editGroupProfile?: Prisma.SortOrder;
  moveGroupOwner?: Prisma.SortOrder;
  viewScores?: Prisma.SortOrder;
  editScores?: Prisma.SortOrder;
  evaluateScores?: Prisma.SortOrder;
  viewBasicProfile?: Prisma.SortOrder;
  viewFullProfile?: Prisma.SortOrder;
  editProfile?: Prisma.SortOrder;
};

export type StatementAvgOrderByAggregateInput = {
  policyId?: Prisma.SortOrder;
};

export type StatementMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  policyId?: Prisma.SortOrder;
  userIdRestrict?: Prisma.SortOrder;
  groupIdRestrict?: Prisma.SortOrder;
  resource?: Prisma.SortOrder;
  viewMembers?: Prisma.SortOrder;
  editMembers?: Prisma.SortOrder;
  viewGroup?: Prisma.SortOrder;
  editGroupProfile?: Prisma.SortOrder;
  moveGroupOwner?: Prisma.SortOrder;
  viewScores?: Prisma.SortOrder;
  editScores?: Prisma.SortOrder;
  evaluateScores?: Prisma.SortOrder;
  viewBasicProfile?: Prisma.SortOrder;
  viewFullProfile?: Prisma.SortOrder;
  editProfile?: Prisma.SortOrder;
};

export type StatementMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  policyId?: Prisma.SortOrder;
  userIdRestrict?: Prisma.SortOrder;
  groupIdRestrict?: Prisma.SortOrder;
  resource?: Prisma.SortOrder;
  viewMembers?: Prisma.SortOrder;
  editMembers?: Prisma.SortOrder;
  viewGroup?: Prisma.SortOrder;
  editGroupProfile?: Prisma.SortOrder;
  moveGroupOwner?: Prisma.SortOrder;
  viewScores?: Prisma.SortOrder;
  editScores?: Prisma.SortOrder;
  evaluateScores?: Prisma.SortOrder;
  viewBasicProfile?: Prisma.SortOrder;
  viewFullProfile?: Prisma.SortOrder;
  editProfile?: Prisma.SortOrder;
};

export type StatementSumOrderByAggregateInput = {
  policyId?: Prisma.SortOrder;
};

export type StatementCreateNestedManyWithoutPolicyInput = {
  create?:
    | Prisma.XOR<
        Prisma.StatementCreateWithoutPolicyInput,
        Prisma.StatementUncheckedCreateWithoutPolicyInput
      >
    | Prisma.StatementCreateWithoutPolicyInput[]
    | Prisma.StatementUncheckedCreateWithoutPolicyInput[];
  connectOrCreate?:
    | Prisma.StatementCreateOrConnectWithoutPolicyInput
    | Prisma.StatementCreateOrConnectWithoutPolicyInput[];
  createMany?: Prisma.StatementCreateManyPolicyInputEnvelope;
  connect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
};

export type StatementUncheckedCreateNestedManyWithoutPolicyInput = {
  create?:
    | Prisma.XOR<
        Prisma.StatementCreateWithoutPolicyInput,
        Prisma.StatementUncheckedCreateWithoutPolicyInput
      >
    | Prisma.StatementCreateWithoutPolicyInput[]
    | Prisma.StatementUncheckedCreateWithoutPolicyInput[];
  connectOrCreate?:
    | Prisma.StatementCreateOrConnectWithoutPolicyInput
    | Prisma.StatementCreateOrConnectWithoutPolicyInput[];
  createMany?: Prisma.StatementCreateManyPolicyInputEnvelope;
  connect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
};

export type StatementUpdateManyWithoutPolicyNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.StatementCreateWithoutPolicyInput,
        Prisma.StatementUncheckedCreateWithoutPolicyInput
      >
    | Prisma.StatementCreateWithoutPolicyInput[]
    | Prisma.StatementUncheckedCreateWithoutPolicyInput[];
  connectOrCreate?:
    | Prisma.StatementCreateOrConnectWithoutPolicyInput
    | Prisma.StatementCreateOrConnectWithoutPolicyInput[];
  upsert?:
    | Prisma.StatementUpsertWithWhereUniqueWithoutPolicyInput
    | Prisma.StatementUpsertWithWhereUniqueWithoutPolicyInput[];
  createMany?: Prisma.StatementCreateManyPolicyInputEnvelope;
  set?: Prisma.StatementWhereUniqueInput | Prisma.StatementWhereUniqueInput[];
  disconnect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  delete?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  connect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  update?:
    | Prisma.StatementUpdateWithWhereUniqueWithoutPolicyInput
    | Prisma.StatementUpdateWithWhereUniqueWithoutPolicyInput[];
  updateMany?:
    | Prisma.StatementUpdateManyWithWhereWithoutPolicyInput
    | Prisma.StatementUpdateManyWithWhereWithoutPolicyInput[];
  deleteMany?:
    | Prisma.StatementScalarWhereInput
    | Prisma.StatementScalarWhereInput[];
};

export type StatementUncheckedUpdateManyWithoutPolicyNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.StatementCreateWithoutPolicyInput,
        Prisma.StatementUncheckedCreateWithoutPolicyInput
      >
    | Prisma.StatementCreateWithoutPolicyInput[]
    | Prisma.StatementUncheckedCreateWithoutPolicyInput[];
  connectOrCreate?:
    | Prisma.StatementCreateOrConnectWithoutPolicyInput
    | Prisma.StatementCreateOrConnectWithoutPolicyInput[];
  upsert?:
    | Prisma.StatementUpsertWithWhereUniqueWithoutPolicyInput
    | Prisma.StatementUpsertWithWhereUniqueWithoutPolicyInput[];
  createMany?: Prisma.StatementCreateManyPolicyInputEnvelope;
  set?: Prisma.StatementWhereUniqueInput | Prisma.StatementWhereUniqueInput[];
  disconnect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  delete?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  connect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  update?:
    | Prisma.StatementUpdateWithWhereUniqueWithoutPolicyInput
    | Prisma.StatementUpdateWithWhereUniqueWithoutPolicyInput[];
  updateMany?:
    | Prisma.StatementUpdateManyWithWhereWithoutPolicyInput
    | Prisma.StatementUpdateManyWithWhereWithoutPolicyInput[];
  deleteMany?:
    | Prisma.StatementScalarWhereInput
    | Prisma.StatementScalarWhereInput[];
};

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null;
};

export type StatementCreateNestedManyWithoutGroupRestrictionInput = {
  create?:
    | Prisma.XOR<
        Prisma.StatementCreateWithoutGroupRestrictionInput,
        Prisma.StatementUncheckedCreateWithoutGroupRestrictionInput
      >
    | Prisma.StatementCreateWithoutGroupRestrictionInput[]
    | Prisma.StatementUncheckedCreateWithoutGroupRestrictionInput[];
  connectOrCreate?:
    | Prisma.StatementCreateOrConnectWithoutGroupRestrictionInput
    | Prisma.StatementCreateOrConnectWithoutGroupRestrictionInput[];
  createMany?: Prisma.StatementCreateManyGroupRestrictionInputEnvelope;
  connect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
};

export type StatementUncheckedCreateNestedManyWithoutGroupRestrictionInput = {
  create?:
    | Prisma.XOR<
        Prisma.StatementCreateWithoutGroupRestrictionInput,
        Prisma.StatementUncheckedCreateWithoutGroupRestrictionInput
      >
    | Prisma.StatementCreateWithoutGroupRestrictionInput[]
    | Prisma.StatementUncheckedCreateWithoutGroupRestrictionInput[];
  connectOrCreate?:
    | Prisma.StatementCreateOrConnectWithoutGroupRestrictionInput
    | Prisma.StatementCreateOrConnectWithoutGroupRestrictionInput[];
  createMany?: Prisma.StatementCreateManyGroupRestrictionInputEnvelope;
  connect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
};

export type StatementUpdateManyWithoutGroupRestrictionNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.StatementCreateWithoutGroupRestrictionInput,
        Prisma.StatementUncheckedCreateWithoutGroupRestrictionInput
      >
    | Prisma.StatementCreateWithoutGroupRestrictionInput[]
    | Prisma.StatementUncheckedCreateWithoutGroupRestrictionInput[];
  connectOrCreate?:
    | Prisma.StatementCreateOrConnectWithoutGroupRestrictionInput
    | Prisma.StatementCreateOrConnectWithoutGroupRestrictionInput[];
  upsert?:
    | Prisma.StatementUpsertWithWhereUniqueWithoutGroupRestrictionInput
    | Prisma.StatementUpsertWithWhereUniqueWithoutGroupRestrictionInput[];
  createMany?: Prisma.StatementCreateManyGroupRestrictionInputEnvelope;
  set?: Prisma.StatementWhereUniqueInput | Prisma.StatementWhereUniqueInput[];
  disconnect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  delete?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  connect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  update?:
    | Prisma.StatementUpdateWithWhereUniqueWithoutGroupRestrictionInput
    | Prisma.StatementUpdateWithWhereUniqueWithoutGroupRestrictionInput[];
  updateMany?:
    | Prisma.StatementUpdateManyWithWhereWithoutGroupRestrictionInput
    | Prisma.StatementUpdateManyWithWhereWithoutGroupRestrictionInput[];
  deleteMany?:
    | Prisma.StatementScalarWhereInput
    | Prisma.StatementScalarWhereInput[];
};

export type StatementUncheckedUpdateManyWithoutGroupRestrictionNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.StatementCreateWithoutGroupRestrictionInput,
        Prisma.StatementUncheckedCreateWithoutGroupRestrictionInput
      >
    | Prisma.StatementCreateWithoutGroupRestrictionInput[]
    | Prisma.StatementUncheckedCreateWithoutGroupRestrictionInput[];
  connectOrCreate?:
    | Prisma.StatementCreateOrConnectWithoutGroupRestrictionInput
    | Prisma.StatementCreateOrConnectWithoutGroupRestrictionInput[];
  upsert?:
    | Prisma.StatementUpsertWithWhereUniqueWithoutGroupRestrictionInput
    | Prisma.StatementUpsertWithWhereUniqueWithoutGroupRestrictionInput[];
  createMany?: Prisma.StatementCreateManyGroupRestrictionInputEnvelope;
  set?: Prisma.StatementWhereUniqueInput | Prisma.StatementWhereUniqueInput[];
  disconnect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  delete?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  connect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  update?:
    | Prisma.StatementUpdateWithWhereUniqueWithoutGroupRestrictionInput
    | Prisma.StatementUpdateWithWhereUniqueWithoutGroupRestrictionInput[];
  updateMany?:
    | Prisma.StatementUpdateManyWithWhereWithoutGroupRestrictionInput
    | Prisma.StatementUpdateManyWithWhereWithoutGroupRestrictionInput[];
  deleteMany?:
    | Prisma.StatementScalarWhereInput
    | Prisma.StatementScalarWhereInput[];
};

export type StatementCreateNestedManyWithoutUserRestrictionInput = {
  create?:
    | Prisma.XOR<
        Prisma.StatementCreateWithoutUserRestrictionInput,
        Prisma.StatementUncheckedCreateWithoutUserRestrictionInput
      >
    | Prisma.StatementCreateWithoutUserRestrictionInput[]
    | Prisma.StatementUncheckedCreateWithoutUserRestrictionInput[];
  connectOrCreate?:
    | Prisma.StatementCreateOrConnectWithoutUserRestrictionInput
    | Prisma.StatementCreateOrConnectWithoutUserRestrictionInput[];
  createMany?: Prisma.StatementCreateManyUserRestrictionInputEnvelope;
  connect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
};

export type StatementUncheckedCreateNestedManyWithoutUserRestrictionInput = {
  create?:
    | Prisma.XOR<
        Prisma.StatementCreateWithoutUserRestrictionInput,
        Prisma.StatementUncheckedCreateWithoutUserRestrictionInput
      >
    | Prisma.StatementCreateWithoutUserRestrictionInput[]
    | Prisma.StatementUncheckedCreateWithoutUserRestrictionInput[];
  connectOrCreate?:
    | Prisma.StatementCreateOrConnectWithoutUserRestrictionInput
    | Prisma.StatementCreateOrConnectWithoutUserRestrictionInput[];
  createMany?: Prisma.StatementCreateManyUserRestrictionInputEnvelope;
  connect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
};

export type StatementUpdateManyWithoutUserRestrictionNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.StatementCreateWithoutUserRestrictionInput,
        Prisma.StatementUncheckedCreateWithoutUserRestrictionInput
      >
    | Prisma.StatementCreateWithoutUserRestrictionInput[]
    | Prisma.StatementUncheckedCreateWithoutUserRestrictionInput[];
  connectOrCreate?:
    | Prisma.StatementCreateOrConnectWithoutUserRestrictionInput
    | Prisma.StatementCreateOrConnectWithoutUserRestrictionInput[];
  upsert?:
    | Prisma.StatementUpsertWithWhereUniqueWithoutUserRestrictionInput
    | Prisma.StatementUpsertWithWhereUniqueWithoutUserRestrictionInput[];
  createMany?: Prisma.StatementCreateManyUserRestrictionInputEnvelope;
  set?: Prisma.StatementWhereUniqueInput | Prisma.StatementWhereUniqueInput[];
  disconnect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  delete?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  connect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  update?:
    | Prisma.StatementUpdateWithWhereUniqueWithoutUserRestrictionInput
    | Prisma.StatementUpdateWithWhereUniqueWithoutUserRestrictionInput[];
  updateMany?:
    | Prisma.StatementUpdateManyWithWhereWithoutUserRestrictionInput
    | Prisma.StatementUpdateManyWithWhereWithoutUserRestrictionInput[];
  deleteMany?:
    | Prisma.StatementScalarWhereInput
    | Prisma.StatementScalarWhereInput[];
};

export type StatementUncheckedUpdateManyWithoutUserRestrictionNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.StatementCreateWithoutUserRestrictionInput,
        Prisma.StatementUncheckedCreateWithoutUserRestrictionInput
      >
    | Prisma.StatementCreateWithoutUserRestrictionInput[]
    | Prisma.StatementUncheckedCreateWithoutUserRestrictionInput[];
  connectOrCreate?:
    | Prisma.StatementCreateOrConnectWithoutUserRestrictionInput
    | Prisma.StatementCreateOrConnectWithoutUserRestrictionInput[];
  upsert?:
    | Prisma.StatementUpsertWithWhereUniqueWithoutUserRestrictionInput
    | Prisma.StatementUpsertWithWhereUniqueWithoutUserRestrictionInput[];
  createMany?: Prisma.StatementCreateManyUserRestrictionInputEnvelope;
  set?: Prisma.StatementWhereUniqueInput | Prisma.StatementWhereUniqueInput[];
  disconnect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  delete?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  connect?:
    | Prisma.StatementWhereUniqueInput
    | Prisma.StatementWhereUniqueInput[];
  update?:
    | Prisma.StatementUpdateWithWhereUniqueWithoutUserRestrictionInput
    | Prisma.StatementUpdateWithWhereUniqueWithoutUserRestrictionInput[];
  updateMany?:
    | Prisma.StatementUpdateManyWithWhereWithoutUserRestrictionInput
    | Prisma.StatementUpdateManyWithWhereWithoutUserRestrictionInput[];
  deleteMany?:
    | Prisma.StatementScalarWhereInput
    | Prisma.StatementScalarWhereInput[];
};

export type StatementCreateWithoutPolicyInput = {
  id?: string;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
  userRestriction?: Prisma.UserCreateNestedOneWithoutAppliedStatementsInput;
  groupRestriction?: Prisma.GroupCreateNestedOneWithoutAppliedStatementsInput;
};

export type StatementUncheckedCreateWithoutPolicyInput = {
  id?: string;
  userIdRestrict?: string | null;
  groupIdRestrict?: string | null;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
};

export type StatementCreateOrConnectWithoutPolicyInput = {
  where: Prisma.StatementWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.StatementCreateWithoutPolicyInput,
    Prisma.StatementUncheckedCreateWithoutPolicyInput
  >;
};

export type StatementCreateManyPolicyInputEnvelope = {
  data:
    | Prisma.StatementCreateManyPolicyInput
    | Prisma.StatementCreateManyPolicyInput[];
  skipDuplicates?: boolean;
};

export type StatementUpsertWithWhereUniqueWithoutPolicyInput = {
  where: Prisma.StatementWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.StatementUpdateWithoutPolicyInput,
    Prisma.StatementUncheckedUpdateWithoutPolicyInput
  >;
  create: Prisma.XOR<
    Prisma.StatementCreateWithoutPolicyInput,
    Prisma.StatementUncheckedCreateWithoutPolicyInput
  >;
};

export type StatementUpdateWithWhereUniqueWithoutPolicyInput = {
  where: Prisma.StatementWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.StatementUpdateWithoutPolicyInput,
    Prisma.StatementUncheckedUpdateWithoutPolicyInput
  >;
};

export type StatementUpdateManyWithWhereWithoutPolicyInput = {
  where: Prisma.StatementScalarWhereInput;
  data: Prisma.XOR<
    Prisma.StatementUpdateManyMutationInput,
    Prisma.StatementUncheckedUpdateManyWithoutPolicyInput
  >;
};

export type StatementScalarWhereInput = {
  AND?: Prisma.StatementScalarWhereInput | Prisma.StatementScalarWhereInput[];
  OR?: Prisma.StatementScalarWhereInput[];
  NOT?: Prisma.StatementScalarWhereInput | Prisma.StatementScalarWhereInput[];
  id?: Prisma.StringFilter<'Statement'> | string;
  policyId?: Prisma.IntFilter<'Statement'> | number;
  userIdRestrict?: Prisma.StringNullableFilter<'Statement'> | string | null;
  groupIdRestrict?: Prisma.StringNullableFilter<'Statement'> | string | null;
  resource?: Prisma.StringFilter<'Statement'> | string;
  viewMembers?: Prisma.BoolFilter<'Statement'> | boolean;
  editMembers?: Prisma.BoolFilter<'Statement'> | boolean;
  viewGroup?: Prisma.BoolFilter<'Statement'> | boolean;
  editGroupProfile?: Prisma.BoolFilter<'Statement'> | boolean;
  moveGroupOwner?: Prisma.BoolFilter<'Statement'> | boolean;
  viewScores?: Prisma.BoolFilter<'Statement'> | boolean;
  editScores?: Prisma.BoolFilter<'Statement'> | boolean;
  evaluateScores?: Prisma.BoolFilter<'Statement'> | boolean;
  viewBasicProfile?: Prisma.BoolFilter<'Statement'> | boolean;
  viewFullProfile?: Prisma.BoolFilter<'Statement'> | boolean;
  editProfile?: Prisma.BoolFilter<'Statement'> | boolean;
};

export type StatementCreateWithoutGroupRestrictionInput = {
  id?: string;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
  policy: Prisma.PolicyCreateNestedOneWithoutStatementsInput;
  userRestriction?: Prisma.UserCreateNestedOneWithoutAppliedStatementsInput;
};

export type StatementUncheckedCreateWithoutGroupRestrictionInput = {
  id?: string;
  policyId: number;
  userIdRestrict?: string | null;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
};

export type StatementCreateOrConnectWithoutGroupRestrictionInput = {
  where: Prisma.StatementWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.StatementCreateWithoutGroupRestrictionInput,
    Prisma.StatementUncheckedCreateWithoutGroupRestrictionInput
  >;
};

export type StatementCreateManyGroupRestrictionInputEnvelope = {
  data:
    | Prisma.StatementCreateManyGroupRestrictionInput
    | Prisma.StatementCreateManyGroupRestrictionInput[];
  skipDuplicates?: boolean;
};

export type StatementUpsertWithWhereUniqueWithoutGroupRestrictionInput = {
  where: Prisma.StatementWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.StatementUpdateWithoutGroupRestrictionInput,
    Prisma.StatementUncheckedUpdateWithoutGroupRestrictionInput
  >;
  create: Prisma.XOR<
    Prisma.StatementCreateWithoutGroupRestrictionInput,
    Prisma.StatementUncheckedCreateWithoutGroupRestrictionInput
  >;
};

export type StatementUpdateWithWhereUniqueWithoutGroupRestrictionInput = {
  where: Prisma.StatementWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.StatementUpdateWithoutGroupRestrictionInput,
    Prisma.StatementUncheckedUpdateWithoutGroupRestrictionInput
  >;
};

export type StatementUpdateManyWithWhereWithoutGroupRestrictionInput = {
  where: Prisma.StatementScalarWhereInput;
  data: Prisma.XOR<
    Prisma.StatementUpdateManyMutationInput,
    Prisma.StatementUncheckedUpdateManyWithoutGroupRestrictionInput
  >;
};

export type StatementCreateWithoutUserRestrictionInput = {
  id?: string;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
  policy: Prisma.PolicyCreateNestedOneWithoutStatementsInput;
  groupRestriction?: Prisma.GroupCreateNestedOneWithoutAppliedStatementsInput;
};

export type StatementUncheckedCreateWithoutUserRestrictionInput = {
  id?: string;
  policyId: number;
  groupIdRestrict?: string | null;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
};

export type StatementCreateOrConnectWithoutUserRestrictionInput = {
  where: Prisma.StatementWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.StatementCreateWithoutUserRestrictionInput,
    Prisma.StatementUncheckedCreateWithoutUserRestrictionInput
  >;
};

export type StatementCreateManyUserRestrictionInputEnvelope = {
  data:
    | Prisma.StatementCreateManyUserRestrictionInput
    | Prisma.StatementCreateManyUserRestrictionInput[];
  skipDuplicates?: boolean;
};

export type StatementUpsertWithWhereUniqueWithoutUserRestrictionInput = {
  where: Prisma.StatementWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.StatementUpdateWithoutUserRestrictionInput,
    Prisma.StatementUncheckedUpdateWithoutUserRestrictionInput
  >;
  create: Prisma.XOR<
    Prisma.StatementCreateWithoutUserRestrictionInput,
    Prisma.StatementUncheckedCreateWithoutUserRestrictionInput
  >;
};

export type StatementUpdateWithWhereUniqueWithoutUserRestrictionInput = {
  where: Prisma.StatementWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.StatementUpdateWithoutUserRestrictionInput,
    Prisma.StatementUncheckedUpdateWithoutUserRestrictionInput
  >;
};

export type StatementUpdateManyWithWhereWithoutUserRestrictionInput = {
  where: Prisma.StatementScalarWhereInput;
  data: Prisma.XOR<
    Prisma.StatementUpdateManyMutationInput,
    Prisma.StatementUncheckedUpdateManyWithoutUserRestrictionInput
  >;
};

export type StatementCreateManyPolicyInput = {
  id?: string;
  userIdRestrict?: string | null;
  groupIdRestrict?: string | null;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
};

export type StatementUpdateWithoutPolicyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  userRestriction?: Prisma.UserUpdateOneWithoutAppliedStatementsNestedInput;
  groupRestriction?: Prisma.GroupUpdateOneWithoutAppliedStatementsNestedInput;
};

export type StatementUncheckedUpdateWithoutPolicyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  userIdRestrict?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  groupIdRestrict?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type StatementUncheckedUpdateManyWithoutPolicyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  userIdRestrict?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  groupIdRestrict?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type StatementCreateManyGroupRestrictionInput = {
  id?: string;
  policyId: number;
  userIdRestrict?: string | null;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
};

export type StatementUpdateWithoutGroupRestrictionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  policy?: Prisma.PolicyUpdateOneRequiredWithoutStatementsNestedInput;
  userRestriction?: Prisma.UserUpdateOneWithoutAppliedStatementsNestedInput;
};

export type StatementUncheckedUpdateWithoutGroupRestrictionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  policyId?: Prisma.IntFieldUpdateOperationsInput | number;
  userIdRestrict?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type StatementUncheckedUpdateManyWithoutGroupRestrictionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  policyId?: Prisma.IntFieldUpdateOperationsInput | number;
  userIdRestrict?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type StatementCreateManyUserRestrictionInput = {
  id?: string;
  policyId: number;
  groupIdRestrict?: string | null;
  resource: string;
  viewMembers: boolean;
  editMembers: boolean;
  viewGroup: boolean;
  editGroupProfile: boolean;
  moveGroupOwner: boolean;
  viewScores: boolean;
  editScores: boolean;
  evaluateScores: boolean;
  viewBasicProfile: boolean;
  viewFullProfile: boolean;
  editProfile: boolean;
};

export type StatementUpdateWithoutUserRestrictionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  policy?: Prisma.PolicyUpdateOneRequiredWithoutStatementsNestedInput;
  groupRestriction?: Prisma.GroupUpdateOneWithoutAppliedStatementsNestedInput;
};

export type StatementUncheckedUpdateWithoutUserRestrictionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  policyId?: Prisma.IntFieldUpdateOperationsInput | number;
  groupIdRestrict?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type StatementUncheckedUpdateManyWithoutUserRestrictionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string;
  policyId?: Prisma.IntFieldUpdateOperationsInput | number;
  groupIdRestrict?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null;
  resource?: Prisma.StringFieldUpdateOperationsInput | string;
  viewMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editMembers?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewGroup?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editGroupProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  moveGroupOwner?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  evaluateScores?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewBasicProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  viewFullProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  editProfile?: Prisma.BoolFieldUpdateOperationsInput | boolean;
};

export type StatementSelect<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    policyId?: boolean;
    userIdRestrict?: boolean;
    groupIdRestrict?: boolean;
    resource?: boolean;
    viewMembers?: boolean;
    editMembers?: boolean;
    viewGroup?: boolean;
    editGroupProfile?: boolean;
    moveGroupOwner?: boolean;
    viewScores?: boolean;
    editScores?: boolean;
    evaluateScores?: boolean;
    viewBasicProfile?: boolean;
    viewFullProfile?: boolean;
    editProfile?: boolean;
    policy?: boolean | Prisma.PolicyDefaultArgs<ExtArgs>;
    userRestriction?: boolean | Prisma.Statement$userRestrictionArgs<ExtArgs>;
    groupRestriction?: boolean | Prisma.Statement$groupRestrictionArgs<ExtArgs>;
  },
  ExtArgs['result']['statement']
>;

export type StatementSelectCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    policyId?: boolean;
    userIdRestrict?: boolean;
    groupIdRestrict?: boolean;
    resource?: boolean;
    viewMembers?: boolean;
    editMembers?: boolean;
    viewGroup?: boolean;
    editGroupProfile?: boolean;
    moveGroupOwner?: boolean;
    viewScores?: boolean;
    editScores?: boolean;
    evaluateScores?: boolean;
    viewBasicProfile?: boolean;
    viewFullProfile?: boolean;
    editProfile?: boolean;
    policy?: boolean | Prisma.PolicyDefaultArgs<ExtArgs>;
    userRestriction?: boolean | Prisma.Statement$userRestrictionArgs<ExtArgs>;
    groupRestriction?: boolean | Prisma.Statement$groupRestrictionArgs<ExtArgs>;
  },
  ExtArgs['result']['statement']
>;

export type StatementSelectUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    policyId?: boolean;
    userIdRestrict?: boolean;
    groupIdRestrict?: boolean;
    resource?: boolean;
    viewMembers?: boolean;
    editMembers?: boolean;
    viewGroup?: boolean;
    editGroupProfile?: boolean;
    moveGroupOwner?: boolean;
    viewScores?: boolean;
    editScores?: boolean;
    evaluateScores?: boolean;
    viewBasicProfile?: boolean;
    viewFullProfile?: boolean;
    editProfile?: boolean;
    policy?: boolean | Prisma.PolicyDefaultArgs<ExtArgs>;
    userRestriction?: boolean | Prisma.Statement$userRestrictionArgs<ExtArgs>;
    groupRestriction?: boolean | Prisma.Statement$groupRestrictionArgs<ExtArgs>;
  },
  ExtArgs['result']['statement']
>;

export type StatementSelectScalar = {
  id?: boolean;
  policyId?: boolean;
  userIdRestrict?: boolean;
  groupIdRestrict?: boolean;
  resource?: boolean;
  viewMembers?: boolean;
  editMembers?: boolean;
  viewGroup?: boolean;
  editGroupProfile?: boolean;
  moveGroupOwner?: boolean;
  viewScores?: boolean;
  editScores?: boolean;
  evaluateScores?: boolean;
  viewBasicProfile?: boolean;
  viewFullProfile?: boolean;
  editProfile?: boolean;
};

export type StatementOmit<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'policyId'
  | 'userIdRestrict'
  | 'groupIdRestrict'
  | 'resource'
  | 'viewMembers'
  | 'editMembers'
  | 'viewGroup'
  | 'editGroupProfile'
  | 'moveGroupOwner'
  | 'viewScores'
  | 'editScores'
  | 'evaluateScores'
  | 'viewBasicProfile'
  | 'viewFullProfile'
  | 'editProfile',
  ExtArgs['result']['statement']
>;
export type StatementInclude<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  policy?: boolean | Prisma.PolicyDefaultArgs<ExtArgs>;
  userRestriction?: boolean | Prisma.Statement$userRestrictionArgs<ExtArgs>;
  groupRestriction?: boolean | Prisma.Statement$groupRestrictionArgs<ExtArgs>;
};
export type StatementIncludeCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  policy?: boolean | Prisma.PolicyDefaultArgs<ExtArgs>;
  userRestriction?: boolean | Prisma.Statement$userRestrictionArgs<ExtArgs>;
  groupRestriction?: boolean | Prisma.Statement$groupRestrictionArgs<ExtArgs>;
};
export type StatementIncludeUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  policy?: boolean | Prisma.PolicyDefaultArgs<ExtArgs>;
  userRestriction?: boolean | Prisma.Statement$userRestrictionArgs<ExtArgs>;
  groupRestriction?: boolean | Prisma.Statement$groupRestrictionArgs<ExtArgs>;
};

export type $StatementPayload<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'Statement';
  objects: {
    policy: Prisma.$PolicyPayload<ExtArgs>;
    userRestriction: Prisma.$UserPayload<ExtArgs> | null;
    groupRestriction: Prisma.$GroupPayload<ExtArgs> | null;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string;
      policyId: number;
      userIdRestrict: string | null;
      groupIdRestrict: string | null;
      resource: string;
      viewMembers: boolean;
      editMembers: boolean;
      viewGroup: boolean;
      editGroupProfile: boolean;
      moveGroupOwner: boolean;
      viewScores: boolean;
      editScores: boolean;
      evaluateScores: boolean;
      viewBasicProfile: boolean;
      viewFullProfile: boolean;
      editProfile: boolean;
    },
    ExtArgs['result']['statement']
  >;
  composites: {};
};

export type StatementGetPayload<
  S extends boolean | null | undefined | StatementDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$StatementPayload, S>;

export type StatementCountArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<StatementFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: StatementCountAggregateInputType | true;
};

export interface StatementDelegate<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['Statement'];
    meta: { name: 'Statement' };
  };
  /**
   * Find zero or one Statement that matches the filter.
   * @param {StatementFindUniqueArgs} args - Arguments to find a Statement
   * @example
   * // Get one Statement
   * const statement = await prisma.statement.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StatementFindUniqueArgs>(
    args: Prisma.SelectSubset<T, StatementFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__StatementClient<
    runtime.Types.Result.GetResult<
      Prisma.$StatementPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one Statement that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StatementFindUniqueOrThrowArgs} args - Arguments to find a Statement
   * @example
   * // Get one Statement
   * const statement = await prisma.statement.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StatementFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, StatementFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__StatementClient<
    runtime.Types.Result.GetResult<
      Prisma.$StatementPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first Statement that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatementFindFirstArgs} args - Arguments to find a Statement
   * @example
   * // Get one Statement
   * const statement = await prisma.statement.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StatementFindFirstArgs>(
    args?: Prisma.SelectSubset<T, StatementFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__StatementClient<
    runtime.Types.Result.GetResult<
      Prisma.$StatementPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first Statement that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatementFindFirstOrThrowArgs} args - Arguments to find a Statement
   * @example
   * // Get one Statement
   * const statement = await prisma.statement.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StatementFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, StatementFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__StatementClient<
    runtime.Types.Result.GetResult<
      Prisma.$StatementPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more Statements that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatementFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Statements
   * const statements = await prisma.statement.findMany()
   *
   * // Get first 10 Statements
   * const statements = await prisma.statement.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const statementWithIdOnly = await prisma.statement.findMany({ select: { id: true } })
   *
   */
  findMany<T extends StatementFindManyArgs>(
    args?: Prisma.SelectSubset<T, StatementFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$StatementPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a Statement.
   * @param {StatementCreateArgs} args - Arguments to create a Statement.
   * @example
   * // Create one Statement
   * const Statement = await prisma.statement.create({
   *   data: {
   *     // ... data to create a Statement
   *   }
   * })
   *
   */
  create<T extends StatementCreateArgs>(
    args: Prisma.SelectSubset<T, StatementCreateArgs<ExtArgs>>
  ): Prisma.Prisma__StatementClient<
    runtime.Types.Result.GetResult<
      Prisma.$StatementPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many Statements.
   * @param {StatementCreateManyArgs} args - Arguments to create many Statements.
   * @example
   * // Create many Statements
   * const statement = await prisma.statement.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends StatementCreateManyArgs>(
    args?: Prisma.SelectSubset<T, StatementCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many Statements and returns the data saved in the database.
   * @param {StatementCreateManyAndReturnArgs} args - Arguments to create many Statements.
   * @example
   * // Create many Statements
   * const statement = await prisma.statement.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many Statements and only return the `id`
   * const statementWithIdOnly = await prisma.statement.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends StatementCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, StatementCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$StatementPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a Statement.
   * @param {StatementDeleteArgs} args - Arguments to delete one Statement.
   * @example
   * // Delete one Statement
   * const Statement = await prisma.statement.delete({
   *   where: {
   *     // ... filter to delete one Statement
   *   }
   * })
   *
   */
  delete<T extends StatementDeleteArgs>(
    args: Prisma.SelectSubset<T, StatementDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__StatementClient<
    runtime.Types.Result.GetResult<
      Prisma.$StatementPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one Statement.
   * @param {StatementUpdateArgs} args - Arguments to update one Statement.
   * @example
   * // Update one Statement
   * const statement = await prisma.statement.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends StatementUpdateArgs>(
    args: Prisma.SelectSubset<T, StatementUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__StatementClient<
    runtime.Types.Result.GetResult<
      Prisma.$StatementPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more Statements.
   * @param {StatementDeleteManyArgs} args - Arguments to filter Statements to delete.
   * @example
   * // Delete a few Statements
   * const { count } = await prisma.statement.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends StatementDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, StatementDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more Statements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatementUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Statements
   * const statement = await prisma.statement.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends StatementUpdateManyArgs>(
    args: Prisma.SelectSubset<T, StatementUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more Statements and returns the data updated in the database.
   * @param {StatementUpdateManyAndReturnArgs} args - Arguments to update many Statements.
   * @example
   * // Update many Statements
   * const statement = await prisma.statement.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more Statements and only return the `id`
   * const statementWithIdOnly = await prisma.statement.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends StatementUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, StatementUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$StatementPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one Statement.
   * @param {StatementUpsertArgs} args - Arguments to update or create a Statement.
   * @example
   * // Update or create a Statement
   * const statement = await prisma.statement.upsert({
   *   create: {
   *     // ... data to create a Statement
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Statement we want to update
   *   }
   * })
   */
  upsert<T extends StatementUpsertArgs>(
    args: Prisma.SelectSubset<T, StatementUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__StatementClient<
    runtime.Types.Result.GetResult<
      Prisma.$StatementPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of Statements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatementCountArgs} args - Arguments to filter Statements to count.
   * @example
   * // Count the number of Statements
   * const count = await prisma.statement.count({
   *   where: {
   *     // ... the filter for the Statements we want to count
   *   }
   * })
   **/
  count<T extends StatementCountArgs>(
    args?: Prisma.Subset<T, StatementCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StatementCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a Statement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatementAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends StatementAggregateArgs>(
    args: Prisma.Subset<T, StatementAggregateArgs>
  ): Prisma.PrismaPromise<GetStatementAggregateType<T>>;

  /**
   * Group by Statement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StatementGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends StatementGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StatementGroupByArgs['orderBy'] }
      : { orderBy?: StatementGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, StatementGroupByArgs, OrderByArg> &
      InputErrors
  ): {} extends InputErrors
    ? GetStatementGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the Statement model
   */
  readonly fields: StatementFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Statement.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StatementClient<
  T,
  Null = never,
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  policy<T extends Prisma.PolicyDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.PolicyDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__PolicyClient<
    | runtime.Types.Result.GetResult<
        Prisma.$PolicyPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  userRestriction<T extends Prisma.Statement$userRestrictionArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.Statement$userRestrictionArgs<ExtArgs>>
  ): Prisma.Prisma__UserClient<
    runtime.Types.Result.GetResult<
      Prisma.$UserPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;
  groupRestriction<
    T extends Prisma.Statement$groupRestrictionArgs<ExtArgs> = {},
  >(
    args?: Prisma.Subset<T, Prisma.Statement$groupRestrictionArgs<ExtArgs>>
  ): Prisma.Prisma__GroupClient<
    runtime.Types.Result.GetResult<
      Prisma.$GroupPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the Statement model
 */
export interface StatementFieldRefs {
  readonly id: Prisma.FieldRef<'Statement', 'String'>;
  readonly policyId: Prisma.FieldRef<'Statement', 'Int'>;
  readonly userIdRestrict: Prisma.FieldRef<'Statement', 'String'>;
  readonly groupIdRestrict: Prisma.FieldRef<'Statement', 'String'>;
  readonly resource: Prisma.FieldRef<'Statement', 'String'>;
  readonly viewMembers: Prisma.FieldRef<'Statement', 'Boolean'>;
  readonly editMembers: Prisma.FieldRef<'Statement', 'Boolean'>;
  readonly viewGroup: Prisma.FieldRef<'Statement', 'Boolean'>;
  readonly editGroupProfile: Prisma.FieldRef<'Statement', 'Boolean'>;
  readonly moveGroupOwner: Prisma.FieldRef<'Statement', 'Boolean'>;
  readonly viewScores: Prisma.FieldRef<'Statement', 'Boolean'>;
  readonly editScores: Prisma.FieldRef<'Statement', 'Boolean'>;
  readonly evaluateScores: Prisma.FieldRef<'Statement', 'Boolean'>;
  readonly viewBasicProfile: Prisma.FieldRef<'Statement', 'Boolean'>;
  readonly viewFullProfile: Prisma.FieldRef<'Statement', 'Boolean'>;
  readonly editProfile: Prisma.FieldRef<'Statement', 'Boolean'>;
}

// Custom InputTypes
/**
 * Statement findUnique
 */
export type StatementFindUniqueArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Statement
   */
  select?: Prisma.StatementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Statement
   */
  omit?: Prisma.StatementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StatementInclude<ExtArgs> | null;
  /**
   * Filter, which Statement to fetch.
   */
  where: Prisma.StatementWhereUniqueInput;
};

/**
 * Statement findUniqueOrThrow
 */
export type StatementFindUniqueOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Statement
   */
  select?: Prisma.StatementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Statement
   */
  omit?: Prisma.StatementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StatementInclude<ExtArgs> | null;
  /**
   * Filter, which Statement to fetch.
   */
  where: Prisma.StatementWhereUniqueInput;
};

/**
 * Statement findFirst
 */
export type StatementFindFirstArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Statement
   */
  select?: Prisma.StatementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Statement
   */
  omit?: Prisma.StatementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StatementInclude<ExtArgs> | null;
  /**
   * Filter, which Statement to fetch.
   */
  where?: Prisma.StatementWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Statements to fetch.
   */
  orderBy?:
    | Prisma.StatementOrderByWithRelationInput
    | Prisma.StatementOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Statements.
   */
  cursor?: Prisma.StatementWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Statements from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Statements.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Statements.
   */
  distinct?:
    | Prisma.StatementScalarFieldEnum
    | Prisma.StatementScalarFieldEnum[];
};

/**
 * Statement findFirstOrThrow
 */
export type StatementFindFirstOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Statement
   */
  select?: Prisma.StatementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Statement
   */
  omit?: Prisma.StatementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StatementInclude<ExtArgs> | null;
  /**
   * Filter, which Statement to fetch.
   */
  where?: Prisma.StatementWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Statements to fetch.
   */
  orderBy?:
    | Prisma.StatementOrderByWithRelationInput
    | Prisma.StatementOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Statements.
   */
  cursor?: Prisma.StatementWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Statements from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Statements.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Statements.
   */
  distinct?:
    | Prisma.StatementScalarFieldEnum
    | Prisma.StatementScalarFieldEnum[];
};

/**
 * Statement findMany
 */
export type StatementFindManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Statement
   */
  select?: Prisma.StatementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Statement
   */
  omit?: Prisma.StatementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StatementInclude<ExtArgs> | null;
  /**
   * Filter, which Statements to fetch.
   */
  where?: Prisma.StatementWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Statements to fetch.
   */
  orderBy?:
    | Prisma.StatementOrderByWithRelationInput
    | Prisma.StatementOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing Statements.
   */
  cursor?: Prisma.StatementWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Statements from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Statements.
   */
  skip?: number;
  distinct?:
    | Prisma.StatementScalarFieldEnum
    | Prisma.StatementScalarFieldEnum[];
};

/**
 * Statement create
 */
export type StatementCreateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Statement
   */
  select?: Prisma.StatementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Statement
   */
  omit?: Prisma.StatementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StatementInclude<ExtArgs> | null;
  /**
   * The data needed to create a Statement.
   */
  data: Prisma.XOR<
    Prisma.StatementCreateInput,
    Prisma.StatementUncheckedCreateInput
  >;
};

/**
 * Statement createMany
 */
export type StatementCreateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many Statements.
   */
  data: Prisma.StatementCreateManyInput | Prisma.StatementCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * Statement createManyAndReturn
 */
export type StatementCreateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Statement
   */
  select?: Prisma.StatementSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the Statement
   */
  omit?: Prisma.StatementOmit<ExtArgs> | null;
  /**
   * The data used to create many Statements.
   */
  data: Prisma.StatementCreateManyInput | Prisma.StatementCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StatementIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * Statement update
 */
export type StatementUpdateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Statement
   */
  select?: Prisma.StatementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Statement
   */
  omit?: Prisma.StatementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StatementInclude<ExtArgs> | null;
  /**
   * The data needed to update a Statement.
   */
  data: Prisma.XOR<
    Prisma.StatementUpdateInput,
    Prisma.StatementUncheckedUpdateInput
  >;
  /**
   * Choose, which Statement to update.
   */
  where: Prisma.StatementWhereUniqueInput;
};

/**
 * Statement updateMany
 */
export type StatementUpdateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update Statements.
   */
  data: Prisma.XOR<
    Prisma.StatementUpdateManyMutationInput,
    Prisma.StatementUncheckedUpdateManyInput
  >;
  /**
   * Filter which Statements to update
   */
  where?: Prisma.StatementWhereInput;
  /**
   * Limit how many Statements to update.
   */
  limit?: number;
};

/**
 * Statement updateManyAndReturn
 */
export type StatementUpdateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Statement
   */
  select?: Prisma.StatementSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the Statement
   */
  omit?: Prisma.StatementOmit<ExtArgs> | null;
  /**
   * The data used to update Statements.
   */
  data: Prisma.XOR<
    Prisma.StatementUpdateManyMutationInput,
    Prisma.StatementUncheckedUpdateManyInput
  >;
  /**
   * Filter which Statements to update
   */
  where?: Prisma.StatementWhereInput;
  /**
   * Limit how many Statements to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StatementIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * Statement upsert
 */
export type StatementUpsertArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Statement
   */
  select?: Prisma.StatementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Statement
   */
  omit?: Prisma.StatementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StatementInclude<ExtArgs> | null;
  /**
   * The filter to search for the Statement to update in case it exists.
   */
  where: Prisma.StatementWhereUniqueInput;
  /**
   * In case the Statement found by the `where` argument doesn't exist, create a new Statement with this data.
   */
  create: Prisma.XOR<
    Prisma.StatementCreateInput,
    Prisma.StatementUncheckedCreateInput
  >;
  /**
   * In case the Statement was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.StatementUpdateInput,
    Prisma.StatementUncheckedUpdateInput
  >;
};

/**
 * Statement delete
 */
export type StatementDeleteArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Statement
   */
  select?: Prisma.StatementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Statement
   */
  omit?: Prisma.StatementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StatementInclude<ExtArgs> | null;
  /**
   * Filter which Statement to delete.
   */
  where: Prisma.StatementWhereUniqueInput;
};

/**
 * Statement deleteMany
 */
export type StatementDeleteManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Statements to delete
   */
  where?: Prisma.StatementWhereInput;
  /**
   * Limit how many Statements to delete.
   */
  limit?: number;
};

/**
 * Statement.userRestriction
 */
export type Statement$userRestrictionArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null;
  where?: Prisma.UserWhereInput;
};

/**
 * Statement.groupRestriction
 */
export type Statement$groupRestrictionArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Group
   */
  select?: Prisma.GroupSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Group
   */
  omit?: Prisma.GroupOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupInclude<ExtArgs> | null;
  where?: Prisma.GroupWhereInput;
};

/**
 * Statement without action
 */
export type StatementDefaultArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Statement
   */
  select?: Prisma.StatementSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Statement
   */
  omit?: Prisma.StatementOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StatementInclude<ExtArgs> | null;
};
