
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Username` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Username
 * 
 */
export type UsernameModel = runtime.Types.Result.DefaultSelection<Prisma.$UsernamePayload>

export type AggregateUsername = {
  _count: UsernameCountAggregateOutputType | null
  _min: UsernameMinAggregateOutputType | null
  _max: UsernameMaxAggregateOutputType | null
}

export type UsernameMinAggregateOutputType = {
  humanId: string | null
  userId: string | null
  createdAt: Date | null
}

export type UsernameMaxAggregateOutputType = {
  humanId: string | null
  userId: string | null
  createdAt: Date | null
}

export type UsernameCountAggregateOutputType = {
  humanId: number
  userId: number
  createdAt: number
  _all: number
}


export type UsernameMinAggregateInputType = {
  humanId?: true
  userId?: true
  createdAt?: true
}

export type UsernameMaxAggregateInputType = {
  humanId?: true
  userId?: true
  createdAt?: true
}

export type UsernameCountAggregateInputType = {
  humanId?: true
  userId?: true
  createdAt?: true
  _all?: true
}

export type UsernameAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Username to aggregate.
   */
  where?: Prisma.UsernameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Usernames to fetch.
   */
  orderBy?: Prisma.UsernameOrderByWithRelationInput | Prisma.UsernameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UsernameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Usernames from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Usernames.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Usernames
  **/
  _count?: true | UsernameCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UsernameMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UsernameMaxAggregateInputType
}

export type GetUsernameAggregateType<T extends UsernameAggregateArgs> = {
      [P in keyof T & keyof AggregateUsername]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUsername[P]>
    : Prisma.GetScalarType<T[P], AggregateUsername[P]>
}




export type UsernameGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UsernameWhereInput
  orderBy?: Prisma.UsernameOrderByWithAggregationInput | Prisma.UsernameOrderByWithAggregationInput[]
  by: Prisma.UsernameScalarFieldEnum[] | Prisma.UsernameScalarFieldEnum
  having?: Prisma.UsernameScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UsernameCountAggregateInputType | true
  _min?: UsernameMinAggregateInputType
  _max?: UsernameMaxAggregateInputType
}

export type UsernameGroupByOutputType = {
  humanId: string
  userId: string
  createdAt: Date
  _count: UsernameCountAggregateOutputType | null
  _min: UsernameMinAggregateOutputType | null
  _max: UsernameMaxAggregateOutputType | null
}

type GetUsernameGroupByPayload<T extends UsernameGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UsernameGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UsernameGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UsernameGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UsernameGroupByOutputType[P]>
      }
    >
  >



export type UsernameWhereInput = {
  AND?: Prisma.UsernameWhereInput | Prisma.UsernameWhereInput[]
  OR?: Prisma.UsernameWhereInput[]
  NOT?: Prisma.UsernameWhereInput | Prisma.UsernameWhereInput[]
  humanId?: Prisma.StringFilter<"Username"> | string
  userId?: Prisma.StringFilter<"Username"> | string
  createdAt?: Prisma.DateTimeFilter<"Username"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UsernameOrderByWithRelationInput = {
  humanId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type UsernameWhereUniqueInput = Prisma.AtLeast<{
  humanId?: string
  AND?: Prisma.UsernameWhereInput | Prisma.UsernameWhereInput[]
  OR?: Prisma.UsernameWhereInput[]
  NOT?: Prisma.UsernameWhereInput | Prisma.UsernameWhereInput[]
  userId?: Prisma.StringFilter<"Username"> | string
  createdAt?: Prisma.DateTimeFilter<"Username"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "humanId">

export type UsernameOrderByWithAggregationInput = {
  humanId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.UsernameCountOrderByAggregateInput
  _max?: Prisma.UsernameMaxOrderByAggregateInput
  _min?: Prisma.UsernameMinOrderByAggregateInput
}

export type UsernameScalarWhereWithAggregatesInput = {
  AND?: Prisma.UsernameScalarWhereWithAggregatesInput | Prisma.UsernameScalarWhereWithAggregatesInput[]
  OR?: Prisma.UsernameScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UsernameScalarWhereWithAggregatesInput | Prisma.UsernameScalarWhereWithAggregatesInput[]
  humanId?: Prisma.StringWithAggregatesFilter<"Username"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Username"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Username"> | Date | string
}

export type UsernameCreateInput = {
  humanId: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutUsernamesInput
}

export type UsernameUncheckedCreateInput = {
  humanId: string
  userId: string
  createdAt?: Date | string
}

export type UsernameUpdateInput = {
  humanId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutUsernamesNestedInput
}

export type UsernameUncheckedUpdateInput = {
  humanId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsernameCreateManyInput = {
  humanId: string
  userId: string
  createdAt?: Date | string
}

export type UsernameUpdateManyMutationInput = {
  humanId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsernameUncheckedUpdateManyInput = {
  humanId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsernameListRelationFilter = {
  every?: Prisma.UsernameWhereInput
  some?: Prisma.UsernameWhereInput
  none?: Prisma.UsernameWhereInput
}

export type UsernameOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UsernameCountOrderByAggregateInput = {
  humanId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UsernameMaxOrderByAggregateInput = {
  humanId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UsernameMinOrderByAggregateInput = {
  humanId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UsernameCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UsernameCreateWithoutUserInput, Prisma.UsernameUncheckedCreateWithoutUserInput> | Prisma.UsernameCreateWithoutUserInput[] | Prisma.UsernameUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UsernameCreateOrConnectWithoutUserInput | Prisma.UsernameCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UsernameCreateManyUserInputEnvelope
  connect?: Prisma.UsernameWhereUniqueInput | Prisma.UsernameWhereUniqueInput[]
}

export type UsernameUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UsernameCreateWithoutUserInput, Prisma.UsernameUncheckedCreateWithoutUserInput> | Prisma.UsernameCreateWithoutUserInput[] | Prisma.UsernameUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UsernameCreateOrConnectWithoutUserInput | Prisma.UsernameCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UsernameCreateManyUserInputEnvelope
  connect?: Prisma.UsernameWhereUniqueInput | Prisma.UsernameWhereUniqueInput[]
}

export type UsernameUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UsernameCreateWithoutUserInput, Prisma.UsernameUncheckedCreateWithoutUserInput> | Prisma.UsernameCreateWithoutUserInput[] | Prisma.UsernameUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UsernameCreateOrConnectWithoutUserInput | Prisma.UsernameCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UsernameUpsertWithWhereUniqueWithoutUserInput | Prisma.UsernameUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UsernameCreateManyUserInputEnvelope
  set?: Prisma.UsernameWhereUniqueInput | Prisma.UsernameWhereUniqueInput[]
  disconnect?: Prisma.UsernameWhereUniqueInput | Prisma.UsernameWhereUniqueInput[]
  delete?: Prisma.UsernameWhereUniqueInput | Prisma.UsernameWhereUniqueInput[]
  connect?: Prisma.UsernameWhereUniqueInput | Prisma.UsernameWhereUniqueInput[]
  update?: Prisma.UsernameUpdateWithWhereUniqueWithoutUserInput | Prisma.UsernameUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UsernameUpdateManyWithWhereWithoutUserInput | Prisma.UsernameUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UsernameScalarWhereInput | Prisma.UsernameScalarWhereInput[]
}

export type UsernameUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UsernameCreateWithoutUserInput, Prisma.UsernameUncheckedCreateWithoutUserInput> | Prisma.UsernameCreateWithoutUserInput[] | Prisma.UsernameUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UsernameCreateOrConnectWithoutUserInput | Prisma.UsernameCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UsernameUpsertWithWhereUniqueWithoutUserInput | Prisma.UsernameUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UsernameCreateManyUserInputEnvelope
  set?: Prisma.UsernameWhereUniqueInput | Prisma.UsernameWhereUniqueInput[]
  disconnect?: Prisma.UsernameWhereUniqueInput | Prisma.UsernameWhereUniqueInput[]
  delete?: Prisma.UsernameWhereUniqueInput | Prisma.UsernameWhereUniqueInput[]
  connect?: Prisma.UsernameWhereUniqueInput | Prisma.UsernameWhereUniqueInput[]
  update?: Prisma.UsernameUpdateWithWhereUniqueWithoutUserInput | Prisma.UsernameUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UsernameUpdateManyWithWhereWithoutUserInput | Prisma.UsernameUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UsernameScalarWhereInput | Prisma.UsernameScalarWhereInput[]
}

export type UsernameCreateWithoutUserInput = {
  humanId: string
  createdAt?: Date | string
}

export type UsernameUncheckedCreateWithoutUserInput = {
  humanId: string
  createdAt?: Date | string
}

export type UsernameCreateOrConnectWithoutUserInput = {
  where: Prisma.UsernameWhereUniqueInput
  create: Prisma.XOR<Prisma.UsernameCreateWithoutUserInput, Prisma.UsernameUncheckedCreateWithoutUserInput>
}

export type UsernameCreateManyUserInputEnvelope = {
  data: Prisma.UsernameCreateManyUserInput | Prisma.UsernameCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UsernameUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UsernameWhereUniqueInput
  update: Prisma.XOR<Prisma.UsernameUpdateWithoutUserInput, Prisma.UsernameUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UsernameCreateWithoutUserInput, Prisma.UsernameUncheckedCreateWithoutUserInput>
}

export type UsernameUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UsernameWhereUniqueInput
  data: Prisma.XOR<Prisma.UsernameUpdateWithoutUserInput, Prisma.UsernameUncheckedUpdateWithoutUserInput>
}

export type UsernameUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UsernameScalarWhereInput
  data: Prisma.XOR<Prisma.UsernameUpdateManyMutationInput, Prisma.UsernameUncheckedUpdateManyWithoutUserInput>
}

export type UsernameScalarWhereInput = {
  AND?: Prisma.UsernameScalarWhereInput | Prisma.UsernameScalarWhereInput[]
  OR?: Prisma.UsernameScalarWhereInput[]
  NOT?: Prisma.UsernameScalarWhereInput | Prisma.UsernameScalarWhereInput[]
  humanId?: Prisma.StringFilter<"Username"> | string
  userId?: Prisma.StringFilter<"Username"> | string
  createdAt?: Prisma.DateTimeFilter<"Username"> | Date | string
}

export type UsernameCreateManyUserInput = {
  humanId: string
  createdAt?: Date | string
}

export type UsernameUpdateWithoutUserInput = {
  humanId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsernameUncheckedUpdateWithoutUserInput = {
  humanId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsernameUncheckedUpdateManyWithoutUserInput = {
  humanId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UsernameSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  humanId?: boolean
  userId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["username"]>

export type UsernameSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  humanId?: boolean
  userId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["username"]>

export type UsernameSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  humanId?: boolean
  userId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["username"]>

export type UsernameSelectScalar = {
  humanId?: boolean
  userId?: boolean
  createdAt?: boolean
}

export type UsernameOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"humanId" | "userId" | "createdAt", ExtArgs["result"]["username"]>
export type UsernameInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UsernameIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UsernameIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UsernamePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Username"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    humanId: string
    userId: string
    createdAt: Date
  }, ExtArgs["result"]["username"]>
  composites: {}
}

export type UsernameGetPayload<S extends boolean | null | undefined | UsernameDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UsernamePayload, S>

export type UsernameCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UsernameFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UsernameCountAggregateInputType | true
  }

export interface UsernameDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Username'], meta: { name: 'Username' } }
  /**
   * Find zero or one Username that matches the filter.
   * @param {UsernameFindUniqueArgs} args - Arguments to find a Username
   * @example
   * // Get one Username
   * const username = await prisma.username.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UsernameFindUniqueArgs>(args: Prisma.SelectSubset<T, UsernameFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UsernameClient<runtime.Types.Result.GetResult<Prisma.$UsernamePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Username that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UsernameFindUniqueOrThrowArgs} args - Arguments to find a Username
   * @example
   * // Get one Username
   * const username = await prisma.username.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UsernameFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UsernameFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UsernameClient<runtime.Types.Result.GetResult<Prisma.$UsernamePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Username that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsernameFindFirstArgs} args - Arguments to find a Username
   * @example
   * // Get one Username
   * const username = await prisma.username.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UsernameFindFirstArgs>(args?: Prisma.SelectSubset<T, UsernameFindFirstArgs<ExtArgs>>): Prisma.Prisma__UsernameClient<runtime.Types.Result.GetResult<Prisma.$UsernamePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Username that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsernameFindFirstOrThrowArgs} args - Arguments to find a Username
   * @example
   * // Get one Username
   * const username = await prisma.username.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UsernameFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UsernameFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UsernameClient<runtime.Types.Result.GetResult<Prisma.$UsernamePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Usernames that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsernameFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Usernames
   * const usernames = await prisma.username.findMany()
   * 
   * // Get first 10 Usernames
   * const usernames = await prisma.username.findMany({ take: 10 })
   * 
   * // Only select the `humanId`
   * const usernameWithHumanIdOnly = await prisma.username.findMany({ select: { humanId: true } })
   * 
   */
  findMany<T extends UsernameFindManyArgs>(args?: Prisma.SelectSubset<T, UsernameFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsernamePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Username.
   * @param {UsernameCreateArgs} args - Arguments to create a Username.
   * @example
   * // Create one Username
   * const Username = await prisma.username.create({
   *   data: {
   *     // ... data to create a Username
   *   }
   * })
   * 
   */
  create<T extends UsernameCreateArgs>(args: Prisma.SelectSubset<T, UsernameCreateArgs<ExtArgs>>): Prisma.Prisma__UsernameClient<runtime.Types.Result.GetResult<Prisma.$UsernamePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Usernames.
   * @param {UsernameCreateManyArgs} args - Arguments to create many Usernames.
   * @example
   * // Create many Usernames
   * const username = await prisma.username.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UsernameCreateManyArgs>(args?: Prisma.SelectSubset<T, UsernameCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Usernames and returns the data saved in the database.
   * @param {UsernameCreateManyAndReturnArgs} args - Arguments to create many Usernames.
   * @example
   * // Create many Usernames
   * const username = await prisma.username.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Usernames and only return the `humanId`
   * const usernameWithHumanIdOnly = await prisma.username.createManyAndReturn({
   *   select: { humanId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UsernameCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UsernameCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsernamePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Username.
   * @param {UsernameDeleteArgs} args - Arguments to delete one Username.
   * @example
   * // Delete one Username
   * const Username = await prisma.username.delete({
   *   where: {
   *     // ... filter to delete one Username
   *   }
   * })
   * 
   */
  delete<T extends UsernameDeleteArgs>(args: Prisma.SelectSubset<T, UsernameDeleteArgs<ExtArgs>>): Prisma.Prisma__UsernameClient<runtime.Types.Result.GetResult<Prisma.$UsernamePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Username.
   * @param {UsernameUpdateArgs} args - Arguments to update one Username.
   * @example
   * // Update one Username
   * const username = await prisma.username.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UsernameUpdateArgs>(args: Prisma.SelectSubset<T, UsernameUpdateArgs<ExtArgs>>): Prisma.Prisma__UsernameClient<runtime.Types.Result.GetResult<Prisma.$UsernamePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Usernames.
   * @param {UsernameDeleteManyArgs} args - Arguments to filter Usernames to delete.
   * @example
   * // Delete a few Usernames
   * const { count } = await prisma.username.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UsernameDeleteManyArgs>(args?: Prisma.SelectSubset<T, UsernameDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Usernames.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsernameUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Usernames
   * const username = await prisma.username.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UsernameUpdateManyArgs>(args: Prisma.SelectSubset<T, UsernameUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Usernames and returns the data updated in the database.
   * @param {UsernameUpdateManyAndReturnArgs} args - Arguments to update many Usernames.
   * @example
   * // Update many Usernames
   * const username = await prisma.username.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Usernames and only return the `humanId`
   * const usernameWithHumanIdOnly = await prisma.username.updateManyAndReturn({
   *   select: { humanId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UsernameUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UsernameUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsernamePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Username.
   * @param {UsernameUpsertArgs} args - Arguments to update or create a Username.
   * @example
   * // Update or create a Username
   * const username = await prisma.username.upsert({
   *   create: {
   *     // ... data to create a Username
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Username we want to update
   *   }
   * })
   */
  upsert<T extends UsernameUpsertArgs>(args: Prisma.SelectSubset<T, UsernameUpsertArgs<ExtArgs>>): Prisma.Prisma__UsernameClient<runtime.Types.Result.GetResult<Prisma.$UsernamePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Usernames.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsernameCountArgs} args - Arguments to filter Usernames to count.
   * @example
   * // Count the number of Usernames
   * const count = await prisma.username.count({
   *   where: {
   *     // ... the filter for the Usernames we want to count
   *   }
   * })
  **/
  count<T extends UsernameCountArgs>(
    args?: Prisma.Subset<T, UsernameCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UsernameCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Username.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsernameAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UsernameAggregateArgs>(args: Prisma.Subset<T, UsernameAggregateArgs>): Prisma.PrismaPromise<GetUsernameAggregateType<T>>

  /**
   * Group by Username.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsernameGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UsernameGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UsernameGroupByArgs['orderBy'] }
      : { orderBy?: UsernameGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UsernameGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUsernameGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Username model
 */
readonly fields: UsernameFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Username.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UsernameClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Username model
 */
export interface UsernameFieldRefs {
  readonly humanId: Prisma.FieldRef<"Username", 'String'>
  readonly userId: Prisma.FieldRef<"Username", 'String'>
  readonly createdAt: Prisma.FieldRef<"Username", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Username findUnique
 */
export type UsernameFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Username
   */
  select?: Prisma.UsernameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Username
   */
  omit?: Prisma.UsernameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsernameInclude<ExtArgs> | null
  /**
   * Filter, which Username to fetch.
   */
  where: Prisma.UsernameWhereUniqueInput
}

/**
 * Username findUniqueOrThrow
 */
export type UsernameFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Username
   */
  select?: Prisma.UsernameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Username
   */
  omit?: Prisma.UsernameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsernameInclude<ExtArgs> | null
  /**
   * Filter, which Username to fetch.
   */
  where: Prisma.UsernameWhereUniqueInput
}

/**
 * Username findFirst
 */
export type UsernameFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Username
   */
  select?: Prisma.UsernameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Username
   */
  omit?: Prisma.UsernameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsernameInclude<ExtArgs> | null
  /**
   * Filter, which Username to fetch.
   */
  where?: Prisma.UsernameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Usernames to fetch.
   */
  orderBy?: Prisma.UsernameOrderByWithRelationInput | Prisma.UsernameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Usernames.
   */
  cursor?: Prisma.UsernameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Usernames from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Usernames.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Usernames.
   */
  distinct?: Prisma.UsernameScalarFieldEnum | Prisma.UsernameScalarFieldEnum[]
}

/**
 * Username findFirstOrThrow
 */
export type UsernameFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Username
   */
  select?: Prisma.UsernameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Username
   */
  omit?: Prisma.UsernameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsernameInclude<ExtArgs> | null
  /**
   * Filter, which Username to fetch.
   */
  where?: Prisma.UsernameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Usernames to fetch.
   */
  orderBy?: Prisma.UsernameOrderByWithRelationInput | Prisma.UsernameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Usernames.
   */
  cursor?: Prisma.UsernameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Usernames from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Usernames.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Usernames.
   */
  distinct?: Prisma.UsernameScalarFieldEnum | Prisma.UsernameScalarFieldEnum[]
}

/**
 * Username findMany
 */
export type UsernameFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Username
   */
  select?: Prisma.UsernameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Username
   */
  omit?: Prisma.UsernameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsernameInclude<ExtArgs> | null
  /**
   * Filter, which Usernames to fetch.
   */
  where?: Prisma.UsernameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Usernames to fetch.
   */
  orderBy?: Prisma.UsernameOrderByWithRelationInput | Prisma.UsernameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Usernames.
   */
  cursor?: Prisma.UsernameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Usernames from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Usernames.
   */
  skip?: number
  distinct?: Prisma.UsernameScalarFieldEnum | Prisma.UsernameScalarFieldEnum[]
}

/**
 * Username create
 */
export type UsernameCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Username
   */
  select?: Prisma.UsernameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Username
   */
  omit?: Prisma.UsernameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsernameInclude<ExtArgs> | null
  /**
   * The data needed to create a Username.
   */
  data: Prisma.XOR<Prisma.UsernameCreateInput, Prisma.UsernameUncheckedCreateInput>
}

/**
 * Username createMany
 */
export type UsernameCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Usernames.
   */
  data: Prisma.UsernameCreateManyInput | Prisma.UsernameCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Username createManyAndReturn
 */
export type UsernameCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Username
   */
  select?: Prisma.UsernameSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Username
   */
  omit?: Prisma.UsernameOmit<ExtArgs> | null
  /**
   * The data used to create many Usernames.
   */
  data: Prisma.UsernameCreateManyInput | Prisma.UsernameCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsernameIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Username update
 */
export type UsernameUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Username
   */
  select?: Prisma.UsernameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Username
   */
  omit?: Prisma.UsernameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsernameInclude<ExtArgs> | null
  /**
   * The data needed to update a Username.
   */
  data: Prisma.XOR<Prisma.UsernameUpdateInput, Prisma.UsernameUncheckedUpdateInput>
  /**
   * Choose, which Username to update.
   */
  where: Prisma.UsernameWhereUniqueInput
}

/**
 * Username updateMany
 */
export type UsernameUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Usernames.
   */
  data: Prisma.XOR<Prisma.UsernameUpdateManyMutationInput, Prisma.UsernameUncheckedUpdateManyInput>
  /**
   * Filter which Usernames to update
   */
  where?: Prisma.UsernameWhereInput
  /**
   * Limit how many Usernames to update.
   */
  limit?: number
}

/**
 * Username updateManyAndReturn
 */
export type UsernameUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Username
   */
  select?: Prisma.UsernameSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Username
   */
  omit?: Prisma.UsernameOmit<ExtArgs> | null
  /**
   * The data used to update Usernames.
   */
  data: Prisma.XOR<Prisma.UsernameUpdateManyMutationInput, Prisma.UsernameUncheckedUpdateManyInput>
  /**
   * Filter which Usernames to update
   */
  where?: Prisma.UsernameWhereInput
  /**
   * Limit how many Usernames to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsernameIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Username upsert
 */
export type UsernameUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Username
   */
  select?: Prisma.UsernameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Username
   */
  omit?: Prisma.UsernameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsernameInclude<ExtArgs> | null
  /**
   * The filter to search for the Username to update in case it exists.
   */
  where: Prisma.UsernameWhereUniqueInput
  /**
   * In case the Username found by the `where` argument doesn't exist, create a new Username with this data.
   */
  create: Prisma.XOR<Prisma.UsernameCreateInput, Prisma.UsernameUncheckedCreateInput>
  /**
   * In case the Username was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UsernameUpdateInput, Prisma.UsernameUncheckedUpdateInput>
}

/**
 * Username delete
 */
export type UsernameDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Username
   */
  select?: Prisma.UsernameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Username
   */
  omit?: Prisma.UsernameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsernameInclude<ExtArgs> | null
  /**
   * Filter which Username to delete.
   */
  where: Prisma.UsernameWhereUniqueInput
}

/**
 * Username deleteMany
 */
export type UsernameDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Usernames to delete
   */
  where?: Prisma.UsernameWhereInput
  /**
   * Limit how many Usernames to delete.
   */
  limit?: number
}

/**
 * Username without action
 */
export type UsernameDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Username
   */
  select?: Prisma.UsernameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Username
   */
  omit?: Prisma.UsernameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsernameInclude<ExtArgs> | null
}
