
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model Policy
 * 
 */
export type Policy = Prisma.PolicyModel
/**
 * Model Statement
 * 
 */
export type Statement = Prisma.StatementModel
/**
 * Model PolicyAssignment
 * 
 */
export type PolicyAssignment = Prisma.PolicyAssignmentModel
/**
 * Model GuidelineCollection
 * 
 */
export type GuidelineCollection = Prisma.GuidelineCollectionModel
/**
 * Model Guideline
 * 
 */
export type Guideline = Prisma.GuidelineModel
/**
 * Model Scoreboard
 * 
 */
export type Scoreboard = Prisma.ScoreboardModel
/**
 * Model PointRequest
 * 
 */
export type PointRequest = Prisma.PointRequestModel
/**
 * Model Evaluation
 * 
 */
export type Evaluation = Prisma.EvaluationModel
/**
 * Model EntryAwardRequest
 * 
 */
export type EntryAwardRequest = Prisma.EntryAwardRequestModel
/**
 * Model PointHistory
 * 
 */
export type PointHistory = Prisma.PointHistoryModel
/**
 * Model Group
 * 
 */
export type Group = Prisma.GroupModel
/**
 * Model Membership
 * 
 */
export type Membership = Prisma.MembershipModel
/**
 * Model MembershipStatus
 * 
 */
export type MembershipStatus = Prisma.MembershipStatusModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model Profile
 * 
 */
export type Profile = Prisma.ProfileModel
/**
 * Model ExternalAccountLink
 * 
 */
export type ExternalAccountLink = Prisma.ExternalAccountLinkModel
/**
 * Model Semester
 * 
 */
export type Semester = Prisma.SemesterModel
/**
 * Model CurrentSemester
 * 
 */
export type CurrentSemester = Prisma.CurrentSemesterModel
/**
 * Model User
 * * Central model representing a user in the PÉK (Profile and Community Management System)
 * * This model stores both profile information and system user data
 */
export type User = Prisma.UserModel
/**
 * Model Username
 * 
 */
export type Username = Prisma.UsernameModel
