
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import * as $Class from "./internal/class.ts"
import * as Prisma from "./internal/prismaNamespace.ts"

export * as $Enums from './enums.ts'
export * from "./enums.ts"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Policies
 * const policies = await prisma.policy.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Policy
 * 
 */
export type Policy = Prisma.PolicyModel
/**
 * Model Statement
 * 
 */
export type Statement = Prisma.StatementModel
/**
 * Model PolicyAssignment
 * 
 */
export type PolicyAssignment = Prisma.PolicyAssignmentModel
/**
 * Model GuidelineCollection
 * 
 */
export type GuidelineCollection = Prisma.GuidelineCollectionModel
/**
 * Model Guideline
 * 
 */
export type Guideline = Prisma.GuidelineModel
/**
 * Model Scoreboard
 * 
 */
export type Scoreboard = Prisma.ScoreboardModel
/**
 * Model PointRequest
 * 
 */
export type PointRequest = Prisma.PointRequestModel
/**
 * Model Evaluation
 * 
 */
export type Evaluation = Prisma.EvaluationModel
/**
 * Model EntryAwardRequest
 * 
 */
export type EntryAwardRequest = Prisma.EntryAwardRequestModel
/**
 * Model PointHistory
 * 
 */
export type PointHistory = Prisma.PointHistoryModel
/**
 * Model Group
 * 
 */
export type Group = Prisma.GroupModel
/**
 * Model Membership
 * 
 */
export type Membership = Prisma.MembershipModel
/**
 * Model MembershipStatus
 * 
 */
export type MembershipStatus = Prisma.MembershipStatusModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model Profile
 * 
 */
export type Profile = Prisma.ProfileModel
/**
 * Model ExternalAccountLink
 * 
 */
export type ExternalAccountLink = Prisma.ExternalAccountLinkModel
/**
 * Model Semester
 * 
 */
export type Semester = Prisma.SemesterModel
/**
 * Model CurrentSemester
 * 
 */
export type CurrentSemester = Prisma.CurrentSemesterModel
/**
 * Model User
 * * Central model representing a user in the PÉK (Profile and Community Management System)
 * * This model stores both profile information and system user data
 */
export type User = Prisma.UserModel
/**
 * Model Username
 * 
 */
export type Username = Prisma.UsernameModel
