
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import type * as Prisma from "./internal/prismaNamespace.ts"


export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type EnumPostCategoryFilter<$PrismaModel = never> = {
  equals?: $Enums.PostCategory | Prisma.EnumPostCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.PostCategory[] | Prisma.ListEnumPostCategoryFieldRefInput<$PrismaModel>
  notIn?: $Enums.PostCategory[] | Prisma.ListEnumPostCategoryFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPostCategoryFilter<$PrismaModel> | $Enums.PostCategory
}

export type EnumPostCategoryWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PostCategory | Prisma.EnumPostCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.PostCategory[] | Prisma.ListEnumPostCategoryFieldRefInput<$PrismaModel>
  notIn?: $Enums.PostCategory[] | Prisma.ListEnumPostCategoryFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPostCategoryWithAggregatesFilter<$PrismaModel> | $Enums.PostCategory
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPostCategoryFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPostCategoryFilter<$PrismaModel>
}

export type EnumRequestStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.RequestStatus | Prisma.EnumRequestStatusFieldRefInput<$PrismaModel>
  in?: $Enums.RequestStatus[] | Prisma.ListEnumRequestStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.RequestStatus[] | Prisma.ListEnumRequestStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumRequestStatusFilter<$PrismaModel> | $Enums.RequestStatus
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type EnumRequestStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.RequestStatus | Prisma.EnumRequestStatusFieldRefInput<$PrismaModel>
  in?: $Enums.RequestStatus[] | Prisma.ListEnumRequestStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.RequestStatus[] | Prisma.ListEnumRequestStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumRequestStatusWithAggregatesFilter<$PrismaModel> | $Enums.RequestStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumRequestStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumRequestStatusFilter<$PrismaModel>
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type EnumEntryAwardTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.EntryAwardType | Prisma.EnumEntryAwardTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EntryAwardType[] | Prisma.ListEnumEntryAwardTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EntryAwardType[] | Prisma.ListEnumEntryAwardTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEntryAwardTypeFilter<$PrismaModel> | $Enums.EntryAwardType
}

export type EnumEntryAwardTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EntryAwardType | Prisma.EnumEntryAwardTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EntryAwardType[] | Prisma.ListEnumEntryAwardTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EntryAwardType[] | Prisma.ListEnumEntryAwardTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEntryAwardTypeWithAggregatesFilter<$PrismaModel> | $Enums.EntryAwardType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEntryAwardTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEntryAwardTypeFilter<$PrismaModel>
}

export type EnumGroupPurposeFilter<$PrismaModel = never> = {
  equals?: $Enums.GroupPurpose | Prisma.EnumGroupPurposeFieldRefInput<$PrismaModel>
  in?: $Enums.GroupPurpose[] | Prisma.ListEnumGroupPurposeFieldRefInput<$PrismaModel>
  notIn?: $Enums.GroupPurpose[] | Prisma.ListEnumGroupPurposeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumGroupPurposeFilter<$PrismaModel> | $Enums.GroupPurpose
}

export type EnumGroupPurposeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.GroupPurpose | Prisma.EnumGroupPurposeFieldRefInput<$PrismaModel>
  in?: $Enums.GroupPurpose[] | Prisma.ListEnumGroupPurposeFieldRefInput<$PrismaModel>
  notIn?: $Enums.GroupPurpose[] | Prisma.ListEnumGroupPurposeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumGroupPurposeWithAggregatesFilter<$PrismaModel> | $Enums.GroupPurpose
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumGroupPurposeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumGroupPurposeFilter<$PrismaModel>
}

export type EnumMembershipKindFilter<$PrismaModel = never> = {
  equals?: $Enums.MembershipKind | Prisma.EnumMembershipKindFieldRefInput<$PrismaModel>
  in?: $Enums.MembershipKind[] | Prisma.ListEnumMembershipKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.MembershipKind[] | Prisma.ListEnumMembershipKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMembershipKindFilter<$PrismaModel> | $Enums.MembershipKind
}

export type EnumMembershipKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MembershipKind | Prisma.EnumMembershipKindFieldRefInput<$PrismaModel>
  in?: $Enums.MembershipKind[] | Prisma.ListEnumMembershipKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.MembershipKind[] | Prisma.ListEnumMembershipKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMembershipKindWithAggregatesFilter<$PrismaModel> | $Enums.MembershipKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMembershipKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMembershipKindFilter<$PrismaModel>
}

export type EnumDormitoryNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Dormitory | Prisma.EnumDormitoryFieldRefInput<$PrismaModel> | null
  in?: $Enums.Dormitory[] | Prisma.ListEnumDormitoryFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Dormitory[] | Prisma.ListEnumDormitoryFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumDormitoryNullableFilter<$PrismaModel> | $Enums.Dormitory | null
}

export type EnumGenderNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Gender | Prisma.EnumGenderFieldRefInput<$PrismaModel> | null
  in?: $Enums.Gender[] | Prisma.ListEnumGenderFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Gender[] | Prisma.ListEnumGenderFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumGenderNullableFilter<$PrismaModel> | $Enums.Gender | null
}

export type EnumStudentStatusNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.StudentStatus | Prisma.EnumStudentStatusFieldRefInput<$PrismaModel> | null
  in?: $Enums.StudentStatus[] | Prisma.ListEnumStudentStatusFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.StudentStatus[] | Prisma.ListEnumStudentStatusFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumStudentStatusNullableFilter<$PrismaModel> | $Enums.StudentStatus | null
}

export type EnumDormitoryNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Dormitory | Prisma.EnumDormitoryFieldRefInput<$PrismaModel> | null
  in?: $Enums.Dormitory[] | Prisma.ListEnumDormitoryFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Dormitory[] | Prisma.ListEnumDormitoryFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumDormitoryNullableWithAggregatesFilter<$PrismaModel> | $Enums.Dormitory | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDormitoryNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDormitoryNullableFilter<$PrismaModel>
}

export type EnumGenderNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Gender | Prisma.EnumGenderFieldRefInput<$PrismaModel> | null
  in?: $Enums.Gender[] | Prisma.ListEnumGenderFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Gender[] | Prisma.ListEnumGenderFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumGenderNullableWithAggregatesFilter<$PrismaModel> | $Enums.Gender | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumGenderNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumGenderNullableFilter<$PrismaModel>
}

export type EnumStudentStatusNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.StudentStatus | Prisma.EnumStudentStatusFieldRefInput<$PrismaModel> | null
  in?: $Enums.StudentStatus[] | Prisma.ListEnumStudentStatusFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.StudentStatus[] | Prisma.ListEnumStudentStatusFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumStudentStatusNullableWithAggregatesFilter<$PrismaModel> | $Enums.StudentStatus | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumStudentStatusNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumStudentStatusNullableFilter<$PrismaModel>
}

export type EnumExternalAccountProtocolFilter<$PrismaModel = never> = {
  equals?: $Enums.ExternalAccountProtocol | Prisma.EnumExternalAccountProtocolFieldRefInput<$PrismaModel>
  in?: $Enums.ExternalAccountProtocol[] | Prisma.ListEnumExternalAccountProtocolFieldRefInput<$PrismaModel>
  notIn?: $Enums.ExternalAccountProtocol[] | Prisma.ListEnumExternalAccountProtocolFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumExternalAccountProtocolFilter<$PrismaModel> | $Enums.ExternalAccountProtocol
}

export type EnumExternalAccountProtocolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ExternalAccountProtocol | Prisma.EnumExternalAccountProtocolFieldRefInput<$PrismaModel>
  in?: $Enums.ExternalAccountProtocol[] | Prisma.ListEnumExternalAccountProtocolFieldRefInput<$PrismaModel>
  notIn?: $Enums.ExternalAccountProtocol[] | Prisma.ListEnumExternalAccountProtocolFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumExternalAccountProtocolWithAggregatesFilter<$PrismaModel> | $Enums.ExternalAccountProtocol
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumExternalAccountProtocolFilter<$PrismaModel>
  _max?: Prisma.NestedEnumExternalAccountProtocolFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedEnumPostCategoryFilter<$PrismaModel = never> = {
  equals?: $Enums.PostCategory | Prisma.EnumPostCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.PostCategory[] | Prisma.ListEnumPostCategoryFieldRefInput<$PrismaModel>
  notIn?: $Enums.PostCategory[] | Prisma.ListEnumPostCategoryFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPostCategoryFilter<$PrismaModel> | $Enums.PostCategory
}

export type NestedEnumPostCategoryWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PostCategory | Prisma.EnumPostCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.PostCategory[] | Prisma.ListEnumPostCategoryFieldRefInput<$PrismaModel>
  notIn?: $Enums.PostCategory[] | Prisma.ListEnumPostCategoryFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPostCategoryWithAggregatesFilter<$PrismaModel> | $Enums.PostCategory
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPostCategoryFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPostCategoryFilter<$PrismaModel>
}

export type NestedEnumRequestStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.RequestStatus | Prisma.EnumRequestStatusFieldRefInput<$PrismaModel>
  in?: $Enums.RequestStatus[] | Prisma.ListEnumRequestStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.RequestStatus[] | Prisma.ListEnumRequestStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumRequestStatusFilter<$PrismaModel> | $Enums.RequestStatus
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedEnumRequestStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.RequestStatus | Prisma.EnumRequestStatusFieldRefInput<$PrismaModel>
  in?: $Enums.RequestStatus[] | Prisma.ListEnumRequestStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.RequestStatus[] | Prisma.ListEnumRequestStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumRequestStatusWithAggregatesFilter<$PrismaModel> | $Enums.RequestStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumRequestStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumRequestStatusFilter<$PrismaModel>
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedEnumEntryAwardTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.EntryAwardType | Prisma.EnumEntryAwardTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EntryAwardType[] | Prisma.ListEnumEntryAwardTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EntryAwardType[] | Prisma.ListEnumEntryAwardTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEntryAwardTypeFilter<$PrismaModel> | $Enums.EntryAwardType
}

export type NestedEnumEntryAwardTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EntryAwardType | Prisma.EnumEntryAwardTypeFieldRefInput<$PrismaModel>
  in?: $Enums.EntryAwardType[] | Prisma.ListEnumEntryAwardTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.EntryAwardType[] | Prisma.ListEnumEntryAwardTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEntryAwardTypeWithAggregatesFilter<$PrismaModel> | $Enums.EntryAwardType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEntryAwardTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEntryAwardTypeFilter<$PrismaModel>
}

export type NestedEnumGroupPurposeFilter<$PrismaModel = never> = {
  equals?: $Enums.GroupPurpose | Prisma.EnumGroupPurposeFieldRefInput<$PrismaModel>
  in?: $Enums.GroupPurpose[] | Prisma.ListEnumGroupPurposeFieldRefInput<$PrismaModel>
  notIn?: $Enums.GroupPurpose[] | Prisma.ListEnumGroupPurposeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumGroupPurposeFilter<$PrismaModel> | $Enums.GroupPurpose
}

export type NestedEnumGroupPurposeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.GroupPurpose | Prisma.EnumGroupPurposeFieldRefInput<$PrismaModel>
  in?: $Enums.GroupPurpose[] | Prisma.ListEnumGroupPurposeFieldRefInput<$PrismaModel>
  notIn?: $Enums.GroupPurpose[] | Prisma.ListEnumGroupPurposeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumGroupPurposeWithAggregatesFilter<$PrismaModel> | $Enums.GroupPurpose
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumGroupPurposeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumGroupPurposeFilter<$PrismaModel>
}

export type NestedEnumMembershipKindFilter<$PrismaModel = never> = {
  equals?: $Enums.MembershipKind | Prisma.EnumMembershipKindFieldRefInput<$PrismaModel>
  in?: $Enums.MembershipKind[] | Prisma.ListEnumMembershipKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.MembershipKind[] | Prisma.ListEnumMembershipKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMembershipKindFilter<$PrismaModel> | $Enums.MembershipKind
}

export type NestedEnumMembershipKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MembershipKind | Prisma.EnumMembershipKindFieldRefInput<$PrismaModel>
  in?: $Enums.MembershipKind[] | Prisma.ListEnumMembershipKindFieldRefInput<$PrismaModel>
  notIn?: $Enums.MembershipKind[] | Prisma.ListEnumMembershipKindFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMembershipKindWithAggregatesFilter<$PrismaModel> | $Enums.MembershipKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMembershipKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMembershipKindFilter<$PrismaModel>
}

export type NestedEnumDormitoryNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Dormitory | Prisma.EnumDormitoryFieldRefInput<$PrismaModel> | null
  in?: $Enums.Dormitory[] | Prisma.ListEnumDormitoryFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Dormitory[] | Prisma.ListEnumDormitoryFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumDormitoryNullableFilter<$PrismaModel> | $Enums.Dormitory | null
}

export type NestedEnumGenderNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Gender | Prisma.EnumGenderFieldRefInput<$PrismaModel> | null
  in?: $Enums.Gender[] | Prisma.ListEnumGenderFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Gender[] | Prisma.ListEnumGenderFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumGenderNullableFilter<$PrismaModel> | $Enums.Gender | null
}

export type NestedEnumStudentStatusNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.StudentStatus | Prisma.EnumStudentStatusFieldRefInput<$PrismaModel> | null
  in?: $Enums.StudentStatus[] | Prisma.ListEnumStudentStatusFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.StudentStatus[] | Prisma.ListEnumStudentStatusFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumStudentStatusNullableFilter<$PrismaModel> | $Enums.StudentStatus | null
}

export type NestedEnumDormitoryNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Dormitory | Prisma.EnumDormitoryFieldRefInput<$PrismaModel> | null
  in?: $Enums.Dormitory[] | Prisma.ListEnumDormitoryFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Dormitory[] | Prisma.ListEnumDormitoryFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumDormitoryNullableWithAggregatesFilter<$PrismaModel> | $Enums.Dormitory | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumDormitoryNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumDormitoryNullableFilter<$PrismaModel>
}

export type NestedEnumGenderNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Gender | Prisma.EnumGenderFieldRefInput<$PrismaModel> | null
  in?: $Enums.Gender[] | Prisma.ListEnumGenderFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.Gender[] | Prisma.ListEnumGenderFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumGenderNullableWithAggregatesFilter<$PrismaModel> | $Enums.Gender | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumGenderNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumGenderNullableFilter<$PrismaModel>
}

export type NestedEnumStudentStatusNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.StudentStatus | Prisma.EnumStudentStatusFieldRefInput<$PrismaModel> | null
  in?: $Enums.StudentStatus[] | Prisma.ListEnumStudentStatusFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.StudentStatus[] | Prisma.ListEnumStudentStatusFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumStudentStatusNullableWithAggregatesFilter<$PrismaModel> | $Enums.StudentStatus | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumStudentStatusNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumStudentStatusNullableFilter<$PrismaModel>
}

export type NestedEnumExternalAccountProtocolFilter<$PrismaModel = never> = {
  equals?: $Enums.ExternalAccountProtocol | Prisma.EnumExternalAccountProtocolFieldRefInput<$PrismaModel>
  in?: $Enums.ExternalAccountProtocol[] | Prisma.ListEnumExternalAccountProtocolFieldRefInput<$PrismaModel>
  notIn?: $Enums.ExternalAccountProtocol[] | Prisma.ListEnumExternalAccountProtocolFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumExternalAccountProtocolFilter<$PrismaModel> | $Enums.ExternalAccountProtocol
}

export type NestedEnumExternalAccountProtocolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ExternalAccountProtocol | Prisma.EnumExternalAccountProtocolFieldRefInput<$PrismaModel>
  in?: $Enums.ExternalAccountProtocol[] | Prisma.ListEnumExternalAccountProtocolFieldRefInput<$PrismaModel>
  notIn?: $Enums.ExternalAccountProtocol[] | Prisma.ListEnumExternalAccountProtocolFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumExternalAccountProtocolWithAggregatesFilter<$PrismaModel> | $Enums.ExternalAccountProtocol
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumExternalAccountProtocolFilter<$PrismaModel>
  _max?: Prisma.NestedEnumExternalAccountProtocolFilter<$PrismaModel>
}


