name: Static Analysis

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint-check:
    strategy:
      matrix:
        component: [backend, frontend]

    name: ESLint Check for ${{ matrix.component }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint check
        working-directory: ${{ matrix.component }}
        run: yarn lint

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    needs:
      - lint-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
